import { Permission } from './types';
import { ThemeVars, AppStrategicMapColors } from './types-next';

export const permissions: Permission[] = [
  'roles:view',
  'roles:export',
  'role:view',
  'role:add',
  'role:update',
  'role:delete',
  'users:view',
  'users:export',
  'user:view',
  'user:add',
  'user:update',
  'user:delete',
  'locations:view',
  'locations:export',
  'location:view',
  'location:add',
  'location:update',
  'location:delete',
  'organization-structure:view',
  'organization-structure:add',
  'organization-structure:edit',
  'organization-structure:delete',
  'organization-structure:update',
  'goals:view',
  'goals:export',
  'goal:add',
  'goal:edit',
  'goal:view',
  'goal:delete',
  'outputs:view',
  'outputs:export',
  'output:add',
  'output:edit',
  'output:view',
  'output:delete',
  'missions:view',
  'missions:export',
  'mission:add',
  'mission:edit',
  'mission:view',
  'mission:delete',
  'unitObjectives:view',
  'unitObjectives:export',
  'unitObjective:add',
  'unitObjective:edit',
  'unitObjective:view',
  'unitObjective:delete',
  'operations:view',
  'operations:export',
  'operation:add',
  'operation:edit',
  'operation:view',
  'operation:delete',
  'strategic-plans:view',
  'strategic-plans:export',
  'strategic-plan:add',
  'strategic-plan:edit',
  'strategic-plan:view',
  'metrics:view',
  'metrics:export',
  'metric:view',
  'metric:add',
  'metric:update',
  'metric:delete',
  'initiatives:view',
  'initiatives:export',
  'initiative:view',
  'initiative:add',
  'initiative:edit',
  'initiative:delete',
  'kpis:view',
  'kpis:export',
  'kpi:view',
  'kpi:add',
  'kpi:edit',
  'kpi:delete',
  'kpi:data-entry',
  'excellence-standards:view',
  'excellence-standards:export',
  'excellence-standard:view',
  'excellence-standard:add',
  'excellence-standard:edit',
  'excellence-standard:delete',
  'excellence-requirements:view',
  'excellence-requirements:export',
  'excellence-requirement:view',
  'excellence-requirement:add',
  'excellence-requirement:edit',
  'excellence-requirement:delete',
  'strategic-map:view',
  'challenges:view',
  'challenges:export',
  'challenge:view',
  'challenge:add',
  'challenge:edit',
  'challenge:delete',
];

export const allPermissionMap = permissions.reduce((ret, perm) => {
  ret[perm] = perm;
  return ret;
}, {} as { [x in Permission]: Permission });

export const Countries = [
  { id: '1', name: 'Country 1' },
  { id: '2', name: 'Country 2' },
  { id: '3', name: 'Country 3' },
  { id: '4', name: 'Country 4' },
  { id: '5', name: 'Country 5' },
];

export const BenchmarkTargets = [
  { id: '1', name: 'Type 1', countries: ['1', '2', '3', '4'] },
  { id: '2', name: 'Type 2', countries: ['1', '2'] },
  { id: '3', name: 'Type 3 ', countries: ['2', '3', '4'] },
];

export const DefaultStrategicMapColorMap: AppStrategicMapColors = {
  Container: { font: 'white', background: '#5578eb' },
  Link: { font: 'white', background: '#5578eb' },
  GenericItem: { font: 'white', background: '#0abb87' },
  KPI: { font: 'white', background: '#ffb822' },
  Operation: { font: 'white', background: '#fd397a' },
  Objective: { font: 'black', background: '#eee' },
  Goal: { font: 'white', background: '#262626' },
  DevelopmentGoal: { font: 'white', background: '#262626' },
  MofaGoal: { font: 'white', background: '#262626' },
  Enabler: { font: 'black', background: '#669873' },
  Outcome: { font: 'black', background: '#17ACE3' },
  Theme: { font: 'black', background: '#86C994' },
};

export const ColorThemeProps: Array<keyof ThemeVars> = ['headerBg'];
