- name: Install nginx
  apt: state=latest update_cache=yes cache_valid_time=3600 pkg={{item}}
  with_items:
    - nginx

- name: Change nginx config
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf mode=644

- name: Change default server
  copy: src=default dest=/etc/nginx/sites-available/default mode=644

- name: Restart nginx
  action: service name=nginx state=restarted
