development:
  secret_key_base: 26b6e0a4da14dad43f3b86cdcb0d519349b0be2439dd6e8505725546c09f5f7d5ac8728ac7201d68f5fee9241a52e537a262cfea7492d8c8ca4a89e6c8af4786
  jwt_secret: f41bdc7c70f5d80c47aeebe80b0337a5230709d08234790c5afec8a5ff66bf193a7ccaa1d22fbba94ef4bd48a6748f6141e3695b7272f2c0d57796efdd7d7517
  finance_portal_api:
    api_url: "https://portal-dev.gettaxi.me/api/v2/"
    api_prefix: "uk"
    auth_params:
      client_id: <%= ENV["FINANCE_PORTAL_API_CLIENT_ID"] %>
      client_secret: <%= ENV["FINANCE_PORTAL_API_CLIENT_SECRET"] %>
      scope: "driver_portal"
      grant_type: "client_credentials"
  gett_earnings_api:
    api_url: "https://api.gett.com/v1/"
    api_prefix: "billing/driver_earnings/uk"
    auth_params:
      client_id: <%= ENV["GETT_EARNINGS_API_CLIENT_ID"] %>
      client_secret: <%= ENV["GETT_EARNINGS_API_CLIENT_SECRET"] %>
      scope: "driverearnings"
      grant_type: "client_credentials"
  gett_fleet_api:
    api_url: "https://api.gett.com/v1/"
    api_prefix: "fleets"
    auth_params:
      client_id: <%= ENV["GETT_FLEET_API_CLIENT_ID"] %>
      client_secret: <%= ENV["GETT_FLEET_API_CLIENT_SECRET"] %>
      scope: "fleets region_uk"
      grant_type: "client_credentials"
  default_url_options:
    host: "http://localhost:3001"
  asset_host: "http://localhost:3000"
  system_user_email: 'admin@system.com'
  contact_us_email: "contact@us.com"
  allowed_gett_id:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
  nexmo:
    api_url: 'https://rest.nexmo.com/sms/json'
    api_key: 'api_key'
    security_secret: 'security_secret'
    enabled: 'false'
  faye:
    host: <%= ENV.fetch('FAYE_HOST', 'localhost') %>
    port: <%= ENV.fetch('FAYE_PORT', 3000) %>

test:
  secret_key_base: 80191eb45d71dbfed8e6c36d856a3193ec7f4abbdabc58de872069793c1db515e3e2935aaeae8a00281ddced1959745b8dee3d1fecda0d2ec727cf26e8c4bad2
  jwt_secret: 698d18af207e17febf961ce1441268930fdc83168fd9fa3c79783d1ce05b216e
  finance_portal_api:
    api_url: "https://portal-dev.gettaxi.me/api/v2/"
    api_prefix: "uk"
    auth_params:
      client_id: <%= ENV["FINANCE_PORTAL_API_CLIENT_ID"] %>
      client_secret: <%= ENV["FINANCE_PORTAL_API_CLIENT_SECRET"] %>
      scope: "driver_portal"
      grant_type: "client_credentials"
  gett_earnings_api:
    api_url: "https://api.gett.com/v1/"
    api_prefix: "billing/driver_earnings/uk"
    auth_params:
      client_id: <%= ENV["GETT_EARNINGS_API_CLIENT_ID"] %>
      client_secret: <%= ENV["GETT_EARNINGS_API_CLIENT_SECRET"] %>
      scope: "driverearnings"
      grant_type: "client_credentials"
  gett_fleet_api:
    api_url: "https://api.gett.com/v1/"
    api_prefix: "fleets"
    auth_params:
      client_id: <%= ENV["GETT_FLEET_API_CLIENT_ID"] %>
      client_secret: <%= ENV["GETT_FLEET_API_CLIENT_SECRET"] %>
      scope: "fleets region_uk"
      grant_type: "client_credentials"
  system_user_email: 'admin@system.com'
  contact_us_email: "contact@us.com"
  asset_host: "http://localhost:3000"
  nexmo:
    api_url: 'https://rest.nexmo.com/sms/json'
    api_key: 'api_key'
    security_secret: 'security_secret'
    enabled: 'true'
  faye:
    host: <%= ENV.fetch('FAYE_HOST', 'localhost') %>
    port: <%= ENV.fetch('FAYE_PORT', 3000) %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  jwt_secret: <%= ENV["JWT_SECRET"] %>
  rollbar_access_token: <%= ENV.fetch("ROLLBAR_ACCESS_TOKEN") { nil } %>
  finance_portal_api:
    api_url: "https://portal-dev.gettaxi.me/api/v2/"
    api_prefix: "uk"
    auth_params:
      client_id: <%= ENV["FINANCE_PORTAL_API_CLIENT_ID"] %>
      client_secret: <%= ENV["FINANCE_PORTAL_API_CLIENT_SECRET"] %>
      scope: "driver_portal"
      grant_type: "client_credentials"
  gett_earnings_api:
    api_url: "https://api.gett.com/v1/"
    api_prefix: "billing/driver_earnings/uk"
    auth_params:
      client_id: <%= ENV["GETT_EARNINGS_API_CLIENT_ID"] %>
      client_secret: <%= ENV["GETT_EARNINGS_API_CLIENT_SECRET"] %>
      scope: "driverearnings"
      grant_type: "client_credentials"
  gett_fleet_api:
    api_url: "https://api.gett.com/v1/"
    api_prefix: "fleets"
    auth_params:
      client_id: <%= ENV["GETT_FLEET_API_CLIENT_ID"] %>
      client_secret: <%= ENV["GETT_FLEET_API_CLIENT_SECRET"] %>
      scope: "fleets region_uk"
      grant_type: "client_credentials"
  smtp_settings:
    user_name: <%= ENV["SENDGRID_USER_NAME"] %>
    password: <%= ENV["SENDGRID_PASSWORD"] %>
    domain: "drivers.uk@gett.com"
    address: "smtp.sendgrid.net"
    port: 587
    authentication: :plain
  default_url_options:
    host: "http://driver-portal-dev.gett.systems"
  asset_host: "http://driver-portal-dev.gett.systems"
  email_to: "gettenterprise@gmail.com"
  system_user_email: 'admin@system.com'
  contact_us_email: "contact@us.com"
  fog_credentials:
    provider: "AWS"
    aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
    aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
    region: <%= ENV["AWS_REGION"] %>
  fog_directory: <%= ENV["AWS_BUCKET"] %>
  newrelic:
    app_name: "Driver Portal"
    license_key: "your_license_key_here"
  nexmo:
    api_url: 'https://rest.nexmo.com/sms/json'
    api_key: 'api_key'
    security_secret: 'security_secret'
    enabled: 'false'
  faye:
    host: <%= ENV.fetch('FAYE_HOST', 'localhost') %>
    port: <%= ENV.fetch('FAYE_PORT', 3000) %>
