sync_drivers:
  batch_size: 10
  sample_pages: 3
  ttl: 86400
sync_statements:
  batch_size: 10
  sample_pages: 3
sessions:
  ttl: 86400
generate_avatars: true
onboarding:
  min_rating: 4.5
  min_rides_number: 100
  max_vehicle_age: 5
