export enum CARDS {
  PERSONAL_INFO = 'PERSONAL_INFO',
  APPLICATIONS = 'APPLICATIONS',
  OFFERS = 'OFFERS',
  FAVORITES = 'FAVORITES',
  REVIEWS = 'REVIEWS',
  REMONT = 'REMONT',
  POLICIES = 'POLICIES',
  COMPARISONS = 'COMPARISONS',
  SERVICE = 'SERVICE',
}
