---
- name: create the postgresql user for application
  postgresql_user: name={{application_user}}
  become: true
  become_user: postgres

- name: create the postgresql database for application
  postgresql_db: name={{application_name}} owner={{application_user}} state=present
  become: true
  become_user: postgres
