- name: Install application deps
  apt: state=latest update_cache=yes cache_valid_time=3600 pkg={{item}}
  with_items:
    - libpq-dev
    - pkg-config
    - libmagickwand-dev
    - libmagickcore-dev
    - imagemagick
    - redis-server
