- name: Install rbenv dependencies
  action: apt state=latest update_cache=yes cache_valid_time=3600 pkg={{item}}
  with_items:
    - curl
    - git-core
    - build-essential
    - openssl
    - libreadline6
    - libreadline6-dev
    - zlib1g
    - zlib1g-dev
    - libssl-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt-dev
    - autoconf
    - libc6-dev
    - ncurses-dev
    - automake
    - libtool
    - bison
    - pkg-config
    - libgdbm-dev
    - libffi-dev

- name: Installs rbenv
  shell: |
    sudo -u {{ application_user }} -H bash -l -c '[[ -d ~/.rbenv ]] || git clone https://github.com/rbenv/rbenv.git ~/.rbenv'
    sudo -u {{ application_user }} -H bash -l -c '[[ -d ~/.rbenv ]] || cd ~/.rbenv && src/configure && make -C src'
    sudo -u {{ application_user }} -H bash -l -c "[[ -d ~/.rbenv ]] || echo 'export PATH=\"$HOME/.rbenv/bin:$PATH\"' >> ~/.bash_profile"
    sudo -u {{ application_user }} -H bash -l -c "[[ -d ~/.rbenv ]] || echo 'eval \"$(rbenv init -)\"' >> ~/.bash_profile"
    sudo -u {{ application_user }} -H bash -l -c '[[ -d ~/.rbenv ]] || exec $SHELL'
    sudo -u {{ application_user }} -H bash -l -c '[[ -d ~/.rbenv/plugins/ruby-build ]] || git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build'
    sudo -u {{ application_user }} -H bash -l -c "[[ -d ~/.rbenv/plugins/ruby-build ]] || echo 'export PATH=\"$HOME/.rbenv/plugins/ruby-build/bin:$PATH\"' >> ~/.bash_profile"
    sudo -u {{ application_user }} -H bash -l -c '[[ -d ~/.rbenv/plugins/ruby-build ]] || exec $SHELL'

- name: Ensure fragments bash dir exists
  file: dest=/home/{{application_user}}/.bash.d/ state=directory owner={{application_user}} group={{application_user}}

- name: Installs rbenv bash file
  copy: src=50_rbenv.bash dest=/home/{{application_user}}/.bash.d/50_rbenv.bash mode=700 owner={{application_user}} group={{application_user}}

- name: Copy default gems file
  copy: src=default-gems dest=/home/{{application_user}}/.rbenv/default-gems mode=660 owner={{application_user}} group={{application_user}}

- name: Checks if target ruby is installed
  shell: "sudo -u {{ application_user }} -H bash -l -c \"rbenv versions | grep {{ ruby_version }} | tr '*' ' ' | sed -e 's/\\s\\+//' | cut -f1 -d' '\""
  register: ruby_is_installed

- name: Installs ruby
  shell: "sudo -u {{ application_user }} -H bash -l -c 'CONFIGURE_OPTS=--disable-install-rdoc rbenv install {{ ruby_version }}'"
  when: ruby_is_installed.stdout != ruby_version
  # Takes no more than 600 secs on a small VM
  async: 600
  poll: 30

- name: Sets global ruby version
  shell: sudo -u {{ application_user }} -H bash -l -c 'rbenv global {{ ruby_version }}'
