const HSA = {
  planType: 'H.S.A',
  planName: '',
  selectedCarrier: {},
  selectedNetwork: {},
  rfpQuoteNetworkPlanId: null,
  benefits: [
    {
      name: 'Deductible',
      sysName: 'INDIVIDUAL_DEDUCTIBLE',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      placeholderIn: 'E.g., $3,000x2',
      placeholderOut: '$6,000x2',
    }, {
      name: 'Co-insurance',
      sysName: 'CO_INSURANCE',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      placeholderIn: 'E.g., 70%',
      placeholderOut: 'E.g., 50%',
    }, {
      name: 'OOP Limit',
      sysName: 'INDIVIDUAL_OOP_LIMIT',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      placeholderIn: 'E.g., $9,000x2',
      placeholderOut: 'E.g., $16,000x2',
    }, {
      name: 'PCP',
      sysName: 'PCP',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      placeholderIn: 'E.g., 70%',
      placeholderOut: 'E.g., 50%',
    }, {
      name: 'Specialist',
      sysName: 'SPECIALIST',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      placeholderIn: 'E.g., 70%',
      placeholderOut: 'E.g., 50%',
    }, {
      name: 'Inpatient Hospital',
      sysName: 'INPATIENT_HOSPITAL',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      placeholderIn: 'E.g., 70%',
      placeholderOut: 'E.g., 50%',
    }, {
      name: 'IP Per-Occurrence Ded',
      sysName: 'IP_PER_OCCURENCE_DEDUCTIBLE',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      placeholderIn: 'E.g., N/A',
      placeholderOut: 'E.g., N/A',
    }, {
      name: 'Outpatient Surgery',
      sysName: 'OUTPATIENT_SURGERY',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      placeholderIn: 'E.g., 70%',
      placeholderOut: 'E.g., 50%',
    }, {
      name: 'Emergency Room',
      sysName: 'EMERGENCY_ROOM',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      placeholderIn: 'E.g., 70%',
      placeholderOut: 'E.g., 70%',
    }, {
      name: 'Deductible Type',
      sysName: 'DEDUCTIBLE_TYPE',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      options: [{ key: 0, value: 'N/A', text: 'N/A' }, { key: 1, value: 'Embedded', text: 'Embedded' }, { key: 2, value: 'Non-Embedded', text: 'Non-Embedded' }],
    }, {
      name: 'Combine Med/Rx Deductible',
      sysName: 'COMBINE_MED_RX_DEDUCTIBLE',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      options: [{ key: 0, value: 'N/A', text: 'N/A' }, { key: 1, value: 'Separate', text: 'Separate' }, { key: 2, value: 'Combined', text: 'Combined' }],
    },
  ],
};

export default HSA;
