default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: artemis-fleets-development

test:
  <<: *default
  database: artemis-fleets-test

gett_base:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: gettaxi_uk_production
  host: 127.0.0.1
  port: 3307
  username: <%= ENV['GETT_DB_USER'] %>
  password: <%= ENV['GETT_DB_PASS'] %>
