branches:
  only:
  - master
language: node_js
node_js:
  - 6
before_install:
  - stty cols 80
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
install: npm install
cache:
  yarn: true
  directories:
  - node_modules
script:
- travis_wait 30 npm run test
notifications:
  email:
    on_failure: change
  slack: benrevo-team:fQkU7SnAJCCt8OQZaNF8hWtR

