services:
    em:
        alias: doctrine.orm.default_entity_manager

    db:
        alias: database_connection

    currency_manager:
        alias: ha.currency.manager

    flash_bag:
        class: Symfony\Component\HttpFoundation\Session\Flash\FlashBag
        factory_service: session
        factory_method: getFlashBag

    liip_imagine:
        alias: liip_imagine.gmagick

    locale_helper:
      alias: ha.locale_helper
