export const FETCH_TEAM_MEMBERS = 'FETCH_TEAM_MEMBERS';
export const FETCH_TEAM_SUCCEEDED = 'FETCH_TEAM_SUCCEEDED';
export const FETCH_TEAM_FAILED = 'FETCH_TEAM_FAILED';

export const SAVE_TEAM_MEMBERS = 'SAVE_TEAM_MEMBERS';
export const SAVE_TEAM_SUCCEEDED = 'SAVE_TEAM_SUCCEEDED';
export const SAVE_TEAM_FAILED = 'SAVE_TEAM_FAILED';

export const DELETE_TEAM_MEMBERS = 'DELETE_TEAM_SUCCEEDED';
export const DELETE_TEAM_SUCCEEDED = 'DELETE_TEAM_SUCCEEDED';
export const DELETE_TEAM_FAILED = 'DELETE_TEAM_FAILED';

export const UPDATE_TEAM = 'UPDATE_TEAM';
