export const GET_MARKETING_STATUS_LIST = 'GET_MARKETING_STATUS_LIST';
export const GET_MARKETING_STATUS_LIST_SUCCESS = 'GET_MARKETING_STATUS_LIST_SUCCESS';
export const GET_MARKETING_STATUS_LIST_ERROR = 'GET_MARKETING_STATUS_LIST_ERROR';

export const SAVE_MARKETING_STATUS_LIST = 'SAVE_MARKETING_STATUS_LIST';
export const SAVE_MARKETING_STATUS_LIST_SUCCESS = 'SAVE_MARKETING_STATUS_LIST_SUCCESS';
export const SAVE_MARKETING_STATUS_LIST_ERROR = 'SAVE_MARKETING_STATUS_LIST_ERROR';

export const SAVE_MARKETING_STATUS_LIST_ITEM = 'SAVE_MARKETING_STATUS_LIST_ITEM';
export const SAVE_MARKETING_STATUS_LIST_ITEM_SUCCESS = 'SAVE_MARKETING_STATUS_LIST_ITEM_SUCCESS';
export const SAVE_MARKETING_STATUS_LIST_ITEM_ERROR = 'SAVE_MARKETING_STATUS_LIST_ITEM_ERROR';

export const GET_VALIDATE = 'GET_VALIDATE';
export const GET_VALIDATE_SUCCESS = 'GET_VALIDATE_SUCCESS';
export const GET_VALIDATE_ERROR = 'GET_VALIDATE_ERROR';

export const DELETE_CARRIE_ITEM = 'DELETE_CARRIE_ITEM';

export const SELECT_CLIENTS_CARRIER = 'SELECT_CLIENTS_CARRIER';

export const NOT_STARTED = 'NOT_STARTED';
export const READY = 'READY';
export const COMPLETED = 'COMPLETED';

export const GET_PROGRAMS = 'GET_PROGRAMS';
export const GET_PROGRAMS_SUCCESS = 'GET_PROGRAMS_SUCCESS';
export const GET_PROGRAMS_ERROR = 'GET_PROGRAMS_ERROR';

export const VOL_LIFE_SECTION = 'vol_life';
export const VOL_STD_SECTION = 'vol_std';
export const VOL_LTD_SECTION = 'vol_ltd';

export const GET_CLSA_QUOTE = 'app/PresentationPage/GET_CLSA_QUOTE';
export const GET_CLSA_QUOTE_SUCCESS = 'app/PresentationPage/GET_CLSA_QUOTE_SUCCESS';
export const GET_CLSA_QUOTE_ERROR = 'app/PresentationPage/GET_CLSA_QUOTE_ERROR';

export const GET_CLIENT_ATTRIBUTES = 'app/PresentationPage/GET_CLIENT_ATTRIBUTES';
export const GET_CLIENT_ATTRIBUTES_SUCCESS = 'app/PresentationPage/GET_CLIENT_ATTRIBUTES_SUCCESS';
export const GET_CLIENT_ATTRIBUTES_ERROR = 'app/PresentationPage/GET_CLIENT_ATTRIBUTES_ERROR';
export const SET_CLIENT_ATTRIBUTES_CALL = 'app/PresentationPage/SET_CLIENT_ATTRIBUTES_CALL';
export const SET_CLIENT_ATTRIBUTES_SUCCESS = 'app/PresentationPage/SET_CLIENT_ATTRIBUTES_SUCCESS';
export const SET_CLIENT_ATTRIBUTES_ERROR = 'app/PresentationPage/SET_CLIENT_ATTRIBUTES_ERROR';

export const GET_NEXT_CLSA = 'app/PresentationPage/GET_NEXT_CLSA';

export const CLSA_MODAL_OPEN = 'app/PresentationPage/CLSA_MODAL_OPEN';
export const CLSA_MODAL_CLOSE = 'app/PresentationPage/CLSA_MODAL_CLOSE';

export const ZIP_ERROR = 'app/PresentationPage/ZIP_ERROR';
export const RESET_ZIP = 'app/PresentationPage/RESET_ZIP';
export const ZIP_SUCCESS_CALL = 'app/PresentationPage/ZIP_SUCCESS_CALL';

export const CHECK_UHC = 'app/PresentationPage/CHECK_UHC';
export const CHECK_UHC_SUCCESS = 'app/PresentationPage/CHECK_UHC_SUCCESS';
export const CHECK_UHC_ERROR = 'app/PresentationPage/CHECK_UHC_ERROR';
