apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aou-backend.apex-extend-logos-secret.fullname" . }}
  labels:
    {{- include "aou-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  logosApiUrl: {{ .Values.apexExtend.logosApiUrl }}
  logosApiKey: {{ .Values.apexExtend.logosApiKey }}
  logosApiSecret: {{ .Values.apexExtend.logosApiSecret }}
