apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aou-backend.apex-extend-secret.fullname" . }}
  labels:
    {{- include "aou-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  tradeApiUrl: {{ .Values.apex.extend.tradeApiUrl }}
  tradeApiEntity: {{ .Values.apex.extend.tradeApiEntity }}
  tradeApiGroup: {{ .Values.apex.extend.tradeApiGroup }}
  tradeApiKey: {{ .Values.apex.extend.tradeApiKey }}
  applicationsUrl: {{ .Values.apex.extend.applicationsUrl }}
  {{- if .Values.apex.extend.isTradeAccountIdBase64Encoded }}
  tradeAccountId: {{ .Values.apex.extend.tradeAccountId | b64dec | quote }}
  {{- else }}
  tradeAccountId: {{ .Values.apex.extend.tradeAccountId | quote }}
  {{- end }}
  userId: {{ .Values.apex.extend.userId | quote }}
  adminApiKey: {{ .Values.apex.extend.adminApiKey }}
  adminApiSecret: {{ .Values.apex.extend.adminApiSecret }}
