apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aou-backend.authentication-secret.fullname" . }}
  labels:
    {{- include "aou-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  readonlyAdminUserName: {{ .Values.authentication.readonlyAdminUserName }}
  marketdataUpdaterUserName: {{ .Values.authentication.marketdataUpdaterUserName }}
  marketdataUpdaterUserPassword: {{ .Values.authentication.marketdataUpdaterUserPassword }}
