apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aou-backend.aws-cognito-secret.fullname" . }}
  labels:
    {{- include "aou-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWKSClient: "{{ .Values.awsCognito.JWKSClient }}"
  audienceClaim: "{{ .Values.awsCognito.audienceClaim }}"
  issuerClaim: "{{ .Values.awsCognito.issuerClaim }}"
  userPoolId: "{{ .Values.awsCognito.userPoolId }}"
  clientId: "{{ .Values.awsCognito.clientId }}"