{{- if .Values.database.sslCACert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aou-backend.db-ca-cert-secret.fullname" . }}
  labels:
    {{- include "aou-backend.labels" . | nindent 4 }}
type: Opaque
data:
  .ca.pem: | {{ .Values.database.sslCACert | nindent 4 }}
{{- end }}
