apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aou-backend.db-creds-secret.fullname" . }}
  labels:
    {{- include "aou-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  host: {{ .Values.database.host | default (include "aou-backend.postgresql.fullname" .) | quote }}
  name: {{ .Values.database.name | quote }}
  user: {{ .Values.database.user | quote }}
  password: {{ .Values.database.password | quote }}
  port: {{ .Values.database.port | quote }}
  url: "postgres://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host | default (include "aou-backend.postgresql.fullname" .) }}:{{ .Values.database.port }}/{{ .Values.database.name }}{{ if .Values.database.sslCACert }}?sslmode=require{{ end }}"
