{{- if .Values.hasura.adminSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aou-backend.hasura-secret.fullname" . }}
  labels:
    {{- include "aou-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  adminSecret: "{{ .Values.hasura.adminSecret }}"
{{- end }}