{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "aou-backend.fullname" . }}
  labels:
    {{- include "aou-backend.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "core.{{ .Values.ingress.host }}, hasura.{{ .Values.ingress.host }}"
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  {{- if .Values.ingress.wafWaclArn }}
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.ingress.wafWaclArn }}
  {{- end }}
    alb.ingress.kubernetes.io/tags: environment={{ .Values.environment }}
  {{- if .Values.ingress.sslCert }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.sslCert }}
  {{- end }}
spec:
  rules:
    - host: "core.{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "aou-backend.apollo.fullname" . }}
                port:
                  number: {{ .Values.services.apollo.port }}
    - host: "hasura.{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "aou-backend.hasura.fullname" . }}
                port:
                  number: {{ .Values.services.hasura.port }}
{{- end }}
