replicaCount: 1

containers:
  - image: registry.rgsbank.ru/cde107/marketplace/marketplace-ui/nginx
    name: nginx
    ports:
      - containerPort: 80
        name: nginx
  - image: registry.rgsbank.ru/cde107/marketplace/marketplace-ui
    name: node
    resources:
      memory: '512Mi'
      cpu: '500m'
    ports:
      - containerPort: 3000
        name: web
    env:
      - name: CURRENT_ENV
        value: staging
      - name: S3_SECRET_ACCESS_KEY
        value: zwJL4N5xkWg2e7Ye
      - name: S3_ENDPOINT
        value: https://cdn.bankauto.ru
