DELETE FROM form_question WHERE question_id = (SELECT question_id FROM question WHERE code = 'tax_id') and form_id = (SELECT form_id FROM form WHERE name = 'group-application');
UPDATE form_question SET `invisible` = TRUE WHERE question_id = (SELECT question_id FROM question WHERE `code` = 'aids') AND form_id = (SELECT form_id FROM form WHERE name = 'group-application');
UPDATE form_question SET `invisible` = TRUE WHERE question_id = (SELECT question_id FROM question WHERE `code` = 'disclosure_persons') AND form_id = (SELECT form_id FROM form WHERE NAME = 'group-application');

UPDATE `question` SET `code` = 'medical_rates_1_tier_1' WHERE `code` = 'medical_rates_1_by_tier_1';
UPDATE `question` SET `code` = 'medical_rates_1_tier_2' WHERE `code` = 'medical_rates_1_by_tier_2';
UPDATE `question` SET `code` = 'medical_rates_1_tier_3' WHERE `code` = 'medical_rates_1_by_tier_3';
UPDATE `question` SET `code` = 'medical_rates_1_tier_4' WHERE `code` = 'medical_rates_1_by_tier_4';
UPDATE `question` SET `code` = 'medical_rates_2_tier_1' WHERE `code` = 'medical_rates_2_by_tier_1';
UPDATE `question` SET `code` = 'medical_rates_2_tier_2' WHERE `code` = 'medical_rates_2_by_tier_2';
UPDATE `question` SET `code` = 'medical_rates_2_tier_3' WHERE `code` = 'medical_rates_2_by_tier_3';
UPDATE `question` SET `code` = 'medical_rates_2_tier_4' WHERE `code` = 'medical_rates_2_by_tier_4';
UPDATE `question` SET `code` = 'medical_rates_3_tier_1' WHERE `code` = 'medical_rates_3_by_tier_1';
UPDATE `question` SET `code` = 'medical_rates_3_tier_2' WHERE `code` = 'medical_rates_3_by_tier_2';
UPDATE `question` SET `code` = 'medical_rates_3_tier_3' WHERE `code` = 'medical_rates_3_by_tier_3';
UPDATE `question` SET `code` = 'medical_rates_3_tier_4' WHERE `code` = 'medical_rates_3_by_tier_4';
UPDATE `question` SET `code` = 'medical_contribution_1_tier_1' WHERE `code` = 'medical_contribution_1_by_tier_1';
UPDATE `question` SET `code` = 'medical_contribution_1_tier_2' WHERE `code` = 'medical_contribution_1_by_tier_2';
UPDATE `question` SET `code` = 'medical_contribution_1_tier_3' WHERE `code` = 'medical_contribution_1_by_tier_3';
UPDATE `question` SET `code` = 'medical_contribution_1_tier_4' WHERE `code` = 'medical_contribution_1_by_tier_4';
UPDATE `question` SET `code` = 'medical_contribution_2_tier_1' WHERE `code` = 'medical_contribution_2_by_tier_1';
UPDATE `question` SET `code` = 'medical_contribution_2_tier_2' WHERE `code` = 'medical_contribution_2_by_tier_2';
UPDATE `question` SET `code` = 'medical_contribution_2_tier_3' WHERE `code` = 'medical_contribution_2_by_tier_3';
UPDATE `question` SET `code` = 'medical_contribution_2_tier_4' WHERE `code` = 'medical_contribution_2_by_tier_4';
UPDATE `question` SET `code` = 'medical_contribution_3_tier_1' WHERE `code` = 'medical_contribution_3_by_tier_1';
UPDATE `question` SET `code` = 'medical_contribution_3_tier_2' WHERE `code` = 'medical_contribution_3_by_tier_2';
UPDATE `question` SET `code` = 'medical_contribution_3_tier_3' WHERE `code` = 'medical_contribution_3_by_tier_3';
UPDATE `question` SET `code` = 'medical_contribution_3_tier_4' WHERE `code` = 'medical_contribution_3_by_tier_4';

INSERT IGNORE INTO `question` (`code`, `title`, `multiselectable`) VALUES ('company_federal_tax_id', 'Company federal tax ID', FALSE);
INSERT IGNORE INTO `question` (`code`, `title`, `multiselectable`) VALUES ('customer_name_on_id_cards', 'Customer name on ID cards', FALSE);
INSERT IGNORE INTO `question` (`code`, `title`, `multiselectable`) VALUES ('billing_contact_name', 'Billing Contact name', FALSE);
INSERT IGNORE INTO `question` (`code`, `title`, `multiselectable`) VALUES ('billing_contact_office_telephone_number', 'Billing Contact office telephone number', FALSE);
INSERT IGNORE INTO `question` (`code`, `title`, `multiselectable`) VALUES ('billing_contact_fax_number', 'Billing Contact fax number', FALSE);
INSERT IGNORE INTO `question` (`code`, `title`, `multiselectable`) VALUES ('billing_contact_email_address', 'Billing Contact E-mail address', FALSE);
INSERT IGNORE INTO `question` (`code`, `title`, `multiselectable`) VALUES ('day_to_day_contact_name', 'Day to day contact name', FALSE);
INSERT IGNORE INTO `question` (`code`, `title`, `multiselectable`) VALUES ('office_telephone_number', 'Office telephone number', FALSE);
INSERT IGNORE INTO `question` (`code`, `title`, `multiselectable`) VALUES ('fax_number', 'Fax number', FALSE);
INSERT IGNORE INTO `question` (`code`, `title`, `multiselectable`) VALUES ('email_address', 'E-mail address', FALSE);
INSERT IGNORE INTO `question` (`code`, `title`, `multiselectable`) VALUES ('type_of_business', 'Type of business (industry or service)', FALSE);

INSERT INTO `form_question` (`required`, `question_id`, `form_id`) VALUES (FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'company_federal_tax_id'), (SELECT `form_id` FROM `form` WHERE name = 'group-application'));
INSERT INTO `form_question` (`required`, `question_id`, `form_id`) VALUES (FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'customer_name_on_id_cards'), (SELECT `form_id` FROM `form` WHERE name = 'group-application'));
INSERT INTO `form_question` (`required`, `question_id`, `form_id`) VALUES (FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'billing_contact_name'), (SELECT `form_id` FROM `form` WHERE name = 'group-application'));
INSERT INTO `form_question` (`required`, `question_id`, `form_id`) VALUES (FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'billing_contact_office_telephone_number'), (SELECT `form_id` FROM `form` WHERE name = 'group-application'));
INSERT INTO `form_question` (`required`, `question_id`, `form_id`) VALUES (FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'billing_contact_fax_number'), (SELECT `form_id` FROM `form` WHERE name = 'group-application'));
INSERT INTO `form_question` (`required`, `question_id`, `form_id`) VALUES (FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'billing_contact_email_address'), (SELECT `form_id` FROM `form` WHERE name = 'group-application'));
INSERT INTO `form_question` (`required`, `question_id`, `form_id`) VALUES (FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'day_to_day_contact_name'), (SELECT `form_id` FROM `form` WHERE name = 'group-application'));
INSERT INTO `form_question` (`required`, `question_id`, `form_id`) VALUES (FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'office_telephone_number'), (SELECT `form_id` FROM `form` WHERE name = 'group-application'));
INSERT INTO `form_question` (`required`, `question_id`, `form_id`) VALUES (FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'fax_number'), (SELECT `form_id` FROM `form` WHERE name = 'group-application'));
INSERT INTO `form_question` (`required`, `question_id`, `form_id`) VALUES (FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'email_address'), (SELECT `form_id` FROM `form` WHERE name = 'group-application'));
INSERT INTO `form_question` (`required`, `question_id`, `form_id`) VALUES (FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'type_of_business'), (SELECT `form_id` FROM `form` WHERE name = 'group-application'));
INSERT INTO `variant` (`number`, `option`, `question_id`) VALUES (5, 'Non-Owners', (SELECT `question_id` FROM `question` WHERE CODE = 'classes_excluded'));
