delete from variant where question_id in (select q.question_id from question q where q.code in (
'are_open_enrollment_meetings_planned', 
'does_the_group_want_enrollment_packets',
'meeting_anthem_representation_needed_1',
'meeting_spanish_required_1',
'meeting_anthem_representation_needed_2',
'meeting_spanish_required_2',
'meeting_anthem_representation_needed_3',
'meeting_spanish_required_3',
'meeting_anthem_representation_needed_4',
'meeting_spanish_required_4',
'meeting_anthem_representation_needed_5',
'meeting_spanish_required_5'));

delete from form_question where form_id = (select f.form_id from form f where f.name = 'kit_requests');

delete from form where name = 'kit_requests';

delete from question where code in (
'are_open_enrollment_meetings_planned', 
'meetings_planned_count',
'does_the_group_want_enrollment_packets',
'english_enrollment_packets_required',	    
'spanish_enrollment_packets_required',  	
'meeting_date_1',
'meeting_address_1',
'meeting_city_1',
'meeting_state_1',
'meeting_zip_1',
'meeting_estimated_attendance_1',
'meeting_anthem_representation_needed_1',
'meeting_spanish_required_1', 
'meeting_special_instructions_1',    
'meeting_english_enrollment_packets_required_1',	  
'meeting_spanish_enrollment_packets_required_1',
'meeting_date_2',
'meeting_address_2',
'meeting_city_2',
'meeting_state_2',
'meeting_zip_2',
'meeting_estimated_attendance_2',
'meeting_anthem_representation_needed_2',
'meeting_spanish_required_2', 
'meeting_special_instructions_2',    
'meeting_english_enrollment_packets_required_2',	  
'meeting_spanish_enrollment_packets_required_2',
'meeting_date_3',
'meeting_address_3',
'meeting_city_3',
'meeting_state_3',
'meeting_zip_3',
'meeting_estimated_attendance_3',
'meeting_anthem_representation_needed_3',
'meeting_spanish_required_3', 
'meeting_special_instructions_3',    
'meeting_english_enrollment_packets_required_3',	  
'meeting_spanish_enrollment_packets_required_3',
'meeting_date_4',
'meeting_address_4',
'meeting_city_4',
'meeting_state_4',
'meeting_zip_4',
'meeting_estimated_attendance_4',
'meeting_anthem_representation_needed_4',
'meeting_spanish_required_4', 
'meeting_special_instructions_4',    
'meeting_english_enrollment_packets_required_4',	  
'meeting_spanish_enrollment_packets_required_4',
'meeting_date_5',
'meeting_address_5',
'meeting_city_5',
'meeting_state_5',
'meeting_zip_5',
'meeting_estimated_attendance_5',
'meeting_anthem_representation_needed_5',
'meeting_spanish_required_5', 
'meeting_special_instructions_5',    
'meeting_english_enrollment_packets_required_5',	  
'meeting_spanish_enrollment_packets_required_5');

