INSERT INTO `benefit_name` (`display_name`, `name`, `ordinal`) VALUES 
('Non-Surgical Endodontics', 'NON_SURGICAL_ENDODONTICS', 0),
('Surgical Endodontics', 'SURGICAL_ENDODONTICS', 0),
('Non-Surigcal Periodontics', 'NON_SURGICAL_PERIODONTICS', 0),
('Surgical Periodontics', 'SURGICAL_PERIODONTICS', 0),
('Simple Oral Surgery', 'SIMPLE_ORAL_SURGERY', 0),
('Complex Oral Surgery', 'COMPLEX_ORAL_SURGERY', 0),
('Prosthdontic Repairs & Adjustments', 'PROSTHDONTIC', 0),
('Basic Services', 'BASIC_WAITING_PERIOD', 0),
('Major Services', 'MAJOR_WAITING_PERIOD', 0),
('Orthodontic Waiting Period', 'ORTHODONTIA_WAITING_PERIOD', 0),
('Individual Office Visit Copay', 'OFFICE_COPAY', 0),
('Individual Lifetime Deductible', 'LIFETIME_DEDUCTIBLE', 0),
('Annual Maximum Carryover', 'CALENDAR_YEAR_MAXIMUM_CARRYOVER', 0),
('Carry In', 'CARRY_IN', 0),
('Diagnostic & Preventive Applies?', 'PREVENTIVE_APPLIES', 0),
('Child Dependent Age', 'CHILD_DEPENDENT_AGE', 0),
('Child Orthontic Dependent Age', 'CHILD_ORTHONTIC_DEPENDENT_AGE', 0),
('Sealants', 'SEALANTS', 0),
('Posterior Composites', 'POSTERIOR_COMPOSITES', 0),
('Brush Biopsy', 'BRUSH_BIOPSY', 0),
('Cosmetics', 'COSMETICS', 0),
('Temporomandibular joints', 'TMJ', 0),
('Bitewing X-Rays', 'BITEWING_X_RAY', 0),
('Full Mouth X-Rays', 'FULL_MOUTH_X_RAY', 0),
('Fluoride', 'FLUORIDE', 0),
('Crowns, Veneers, Dentures, Bridges', 'CROWNS', 0);

