INSERT INTO `form` (`name`, `carrier_id`) VALUES ('group-application-other', (SELECT `carrier_id` FROM `carrier` WHERE name = 'UHC'));

INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('covered_by_united_healthcare_date', 'Has the group been insured/covered by united healthcare in the last 12 months. (date)', FALSE);
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('currently_pregnant_number', 'Are you aware of ANY employee OR dependent who IS currently pregnant (number)', FALSE);
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('was_there_more_than_one_wa', 'Was there more then one writing agent?', FALSE);
INSERT INTO variant (`number`, `option`, `question_id`) VALUES (1, 'Yes', (SELECT `question_id` FROM `question` WHERE CODE = 'was_there_more_than_one_wa'));
INSERT INTO variant (`number`, `option`, `question_id`) VALUES (1, 'No', (SELECT `question_id` FROM `question` WHERE CODE = 'was_there_more_than_one_wa'));
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('covered_by_united_healthcare_date_from', 'Date coverage terminated from', FALSE);
UPDATE question SET code = 'covered_by_united_healthcare_date_to', title = 'Date coverage terminated to' WHERE code = 'covered_by_united_healthcare_date';

INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('indicate_whether_employee_dependent_4', 'Indicate whether employee or dependent', FALSE);
INSERT INTO variant (`number`, `option`, `question_id`) VALUES (1, 'Employee', (SELECT `question_id` FROM `question` WHERE CODE = 'indicate_whether_employee_dependent_4'));
INSERT INTO variant (`number`, `option`, `question_id`) VALUES (2, 'Dependent', (SELECT `question_id` FROM `question` WHERE CODE = 'indicate_whether_employee_dependent_4'));
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('indicate_whether_employee_dependent_5', 'Indicate whether employee or dependent', FALSE);
INSERT INTO variant (`number`, `option`, `question_id`) VALUES (1, 'Employee', (SELECT `question_id` FROM `question` WHERE CODE = 'indicate_whether_employee_dependent_5'));
INSERT INTO variant (`number`, `option`, `question_id`) VALUES (2, 'Dependent', (SELECT `question_id` FROM `question` WHERE CODE = 'indicate_whether_employee_dependent_5'));
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('indicate_whether_employee_dependent_6', 'Indicate whether employee or dependent', FALSE);
INSERT INTO variant (`number`, `option`, `question_id`) VALUES (1, 'Employee', (SELECT `question_id` FROM `question` WHERE CODE = 'indicate_whether_employee_dependent_6'));
INSERT INTO variant (`number`, `option`, `question_id`) VALUES (2, 'Dependent', (SELECT `question_id` FROM `question` WHERE CODE = 'indicate_whether_employee_dependent_6'));
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('indicate_whether_employee_dependent_7', 'Indicate whether employee or dependent', FALSE);
INSERT INTO variant (`number`, `option`, `question_id`) VALUES (1, 'Employee', (SELECT `question_id` FROM `question` WHERE CODE = 'indicate_whether_employee_dependent_7'));
INSERT INTO variant (`number`, `option`, `question_id`) VALUES (2, 'Dependent', (SELECT `question_id` FROM `question` WHERE CODE = 'indicate_whether_employee_dependent_7'));
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('nature_of_illness_4', 'Nature of illness', FALSE);
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('nature_of_illness_5', 'Nature of illness', FALSE);
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('nature_of_illness_6', 'Nature of illness', FALSE);
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('nature_of_illness_7', 'Nature of illness', FALSE);
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('date_of_onset_4', 'Date of onset', FALSE);
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('date_of_onset_5', 'Date of onset', FALSE);
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('date_of_onset_6', 'Date of onset', FALSE);
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('date_of_onset_7', 'Date of onset', FALSE);
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('approximate_amount_of_claim_4', 'Approximate amount of claim', FALSE);
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('approximate_amount_of_claim_5', 'Approximate amount of claim', FALSE);
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('approximate_amount_of_claim_6', 'Approximate amount of claim', FALSE);
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('approximate_amount_of_claim_7', 'Approximate amount of claim', FALSE);
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('length_of_disability_4', 'Length of disability', FALSE);
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('length_of_disability_5', 'Length of disability', FALSE);
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('length_of_disability_6', 'Length of disability', FALSE);
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('length_of_disability_7', 'Length of disability', FALSE);
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('current_health_status_4', 'Current health status', FALSE);
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('current_health_status_5', 'Current health status', FALSE);
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('current_health_status_6', 'Current health status', FALSE);
INSERT INTO question (`code`, `title`, `multiselectable`) VALUES ('current_health_status_7', 'Current health status', FALSE);

INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (62, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'commission_payable_to_other'), (SELECT `form_id` FROM `form` WHERE name = 'group-application'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (63, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'covered_by_united_healthcare_date_to'), (SELECT `form_id` FROM `form` WHERE name = 'group-application'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (63, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'covered_by_united_healthcare_date_from'), (SELECT `form_id` FROM `form` WHERE name = 'group-application'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (64, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'currently_pregnant_number'), (SELECT `form_id` FROM `form` WHERE name = 'group-application'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'company_federal_tax_id'), (SELECT `form_id` FROM `form` WHERE name = 'questionnaire'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'indicate_whether_employee_dependent_4'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'indicate_whether_employee_dependent_5'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'indicate_whether_employee_dependent_6'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'indicate_whether_employee_dependent_7'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'nature_of_illness_4'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'nature_of_illness_5'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'nature_of_illness_6'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'nature_of_illness_7'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'date_of_onset_4'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'date_of_onset_5'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'date_of_onset_6'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'date_of_onset_7'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'approximate_amount_of_claim_4'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'approximate_amount_of_claim_5'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'approximate_amount_of_claim_6'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'approximate_amount_of_claim_7'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'length_of_disability_4'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'length_of_disability_5'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'length_of_disability_6'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'length_of_disability_7'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'current_health_status_4'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'current_health_status_5'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'current_health_status_6'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));
INSERT INTO `form_question` (`index_number`, `required`, `question_id`, `form_id`) VALUES (65, FALSE, (SELECT `question_id` FROM `question` WHERE CODE = 'current_health_status_7'), (SELECT `form_id` FROM `form` WHERE name = 'group-application-other'));

