const IMAGES = {
  slider: {
    thumb: require('./image/slider-thumb.png'),
  },
  heart: require('./image/heart/heart.png'),
  heartFilled: require('./image/heart/heart-filled-red.png'),
  basket: require('./image/basket/basket.png'),
  trash: require('./image/trash/trash.png'),
  minus: require('./image/minus/minus.png'),
  plus: require('./image/plus/plus.png'),
  calendar: require('./image/calendar/calendar.png'),
  catalogGreen: require('./image/dirSmallGreen/dir-small-green.png'),
  chevronDownGray: require('./image/chevron/chevron-down-gray.png'),
  chevronDownGreen: require('./image/chevronDownGreen/chevron-down-green.png'),
  chevronRightGray: require('./image/chevron/chevron-right-gray.png'),
  metro: require('./image/metro/metro.png'),
  outOfStock: require('./image/outOfStock/out-of-stock.png'),
  discount: require('./image/discount/discount.png'),
  discountEmpty: require('./image/discount/discountEmpty.png'),
  sale: require('./image/discount/sale.png'),
  searchGreen: require('./image/search/search-green.png'),
  logo: require('./image/logo/logo.png'),
  searchGray: require('./image/search/search-gray.png'),
  noUserPhoto: require('./image/photo/no-user-photo.png'),
  photoRemove: require('./image/photo/remove.png'),
  photoChange: require('./image/photo/change.png'),
  locationGray: require('./image/loc/loc.png'),
  contacts: require('./image/contacts/contacts.png'),
  locationGreen: require('./image/loc/loc-green.png'),
  cartPharmacyChecked: require('./image/cartChecked/cart-checked.png'),
  cartPharmacy: require('./image/cartArrowDown/cart-arrow-down.png'),
  man: require('./image/man/man.png'),
  mail: require('./image/mail/mail.png'),
  phone: require('./image/phone/phone.png'),
  loader: {
    small: {
      green: require('./image/loader/loader-small.png'),
      white: require('./image/loader/loader-small-white.png'),
    },
    medium: {
      green: require('./image/loader/loader-medium.png'),
      white: require('./image/loader/loader-medium-white.png'),
    },
    large: {
      green: require('./image/loader/loader-large.png'),
      white: require('./image/loader/loader-large-white.png'),
    },
    huge: {
      green: require('./image/loader/loader-huge.png'),
      white: require('./image/loader/loader-huge-white.png'),
    },
  },
  markers: {
    cheapest: require('./image/markers/cheapest.png'),
    cheapestFavourite: require('./image/markers/cheapest-fav.png'),
    full: require('./image/markers/full.png'),
    fullFavourite: require('./image/markers/full-fav.png'),
    nearest: require('./image/markers/nearest.png'),
    nearestFavourite: require('./image/markers/nearest-fav.png'),
    partial: require('./image/markers/partial.png'),
    partialFavourite: require('./image/markers/partial-fav.png'),
    selected: require('./image/markers/selected.png'),
    user: require('./image/markers/user.png'),
  },
  slides: {
    pill: require('./image/pill/pill.png'),
    discounts: require('./image/discounts/discounts.png'),
    bonuses: require('./image/bonuses/bonuses.png'),
  },
  tabs: {
    catalogActive: require('./image/tabCatalog/tabCatalog-active.png'),
    catalog: require('./image/tabCatalog/tabCatalog.png'),
    pharmaciesActive: require('./image/tabPharmacy/tabPharmacy-active.png'),
    pharmacies: require('./image/tabPharmacy/tabPharmacy.png'),
    homeActive: require('./image/tabHome/tabHome-active.png'),
    home: require('./image/tabHome/tabHome.png'),
    favoritesActive: require('./image/tabFavorites/tabFavorites-active.png'),
    favorites: require('./image/tabFavorites/tabFavorites.png'),
    menuActive: require('./image/tabMenu/tabMenu-active.png'),
    menu: require('./image/tabMenu/tabMenu.png'),
  },
};

export default IMAGES;
