/*
 *
 * CarrierPage constants
 *
 */
export const FETCH_CLIENTS = 'SEND_CLIENTS';
export const FETCH_CLIENTS_FAILED = 'FETCH_CLIENTS_FAILED';
export const FETCH_CLIENTS_SUCCEEDED = 'FETCH_CLIENTS_SUCCEEDED';
export const SAVE_CLIENT_SUCCEEDED = 'SAVE_CLIENT_SUCCEEDED';
export const SAVE_CLIENT_FAILED = 'SAVE_CLIENT_FAILED';

export const SEND_INVITE_CLIENT = 'SEND_INVITE_CLIENT';
export const SEND_INVITE_CLIENT_SUCCESS = 'SEND_INVITE_CLIENT_SUCCESS';
export const SEND_INVITE_CLIENT_ERROR = 'SEND_INVITE_CLIENT_ERROR';
export const SEND_CHANGE_PASSWORD_SUCCESS = 'SEND_CHANGE_PASSWORD_SUCCESS';
export const SEND_CHANGE_PASSWORD_ERROR = 'SEND_CHANGE_PASSWORD_ERROR';
