language: java
jdk:
- oraclejdk8
before_script:
- pip install --user awscli
deploy:
  provider: script
  script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy
  skip_cleanup: true
  on:
    branch: develop
    
script: mvn clean test -DsuiteXmlFile=resources/rfp_tests.xml
