export const COUNTIES = [
  { text: 'Alameda', value: 'Alameda' },
  { text: 'Alpine', value: 'Alpine' },
  { text: 'Amador', value: 'Amador' },
  { text: 'Butte', value: 'Butte' },
  { text: 'Calaveras', value: 'Calaveras' },
  { text: 'Colusa', value: 'Colusa' },
  { text: 'Contra Costa', value: 'Contra Costa' },
  { text: 'Del Norte', value: 'Del Norte' },
  { text: 'El Dorado', value: 'El Dorado' },
  { text: 'Fresno', value: 'Fresno' },
  { text: 'Glenn', value: 'Glenn' },
  { text: 'Humboldt', value: 'Humboldt' },
  { text: 'Imperial', value: 'Imperial' },
  { text: 'Inyo', value: 'Inyo' },
  { text: 'Kern', value: 'Kern' },
  { text: 'Kings', value: 'Kings' },
  { text: 'Lake', value: 'Lake' },
  { text: 'Lassen', value: 'Lassen' },
  { text: 'Los Angeles', value: 'Los Angeles' },
  { text: 'Madera', value: 'Madera' },
  { text: 'Marin', value: 'Marin' },
  { text: 'Mariposa', value: 'Mariposa' },
  { text: 'Mendocino', value: 'Mendocino' },
  { text: 'Merced', value: 'Merced' },
  { text: 'Modoc', value: 'Modoc' },
  { text: 'Mono', value: 'Mono' },
  { text: 'Monterey', value: 'Monterey' },
  { text: 'Napa', value: 'Napa' },
  { text: 'Nevada', value: 'Nevada' },
  { text: 'Orange', value: 'Orange' },
  { text: 'Placer', value: 'Placer' },
  { text: 'Plumas', value: 'Plumas' },
  { text: 'Riverside', value: 'Riverside' },
  { text: 'Sacramento', value: 'Sacramento' },
  { text: 'San Benito', value: 'San Benito' },
  { text: 'San Bernardino', value: 'San Bernardino' },
  { text: 'San Diego', value: 'San Diego' },
  { text: 'San Francisco', value: 'San Francisco' },
  { text: 'San Joaquin', value: 'San Joaquin' },
  { text: 'San Luis Obispo', value: 'San Luis Obispo' },
  { text: 'San Mateo', value: 'San Mateo' },
  { text: 'Santa Barbara', value: 'Santa Barbara' },
  { text: 'Santa Clara', value: 'Santa Clara' },
  { text: 'Santa Cruz', value: 'Santa Cruz' },
  { text: 'Shasta', value: 'Shasta' },
  { text: 'Sierra', value: 'Sierra' },
  { text: 'Siskiyou', value: 'Siskiyou' },
  { text: 'Solano', value: 'Solano' },
  { text: 'Sonoma', value: 'Sonoma' },
  { text: 'Stanislaus', value: 'Stanislaus' },
  { text: 'Sutter', value: 'Sutter' },
  { text: 'Tehama', value: 'Tehama' },
  { text: 'Trinity', value: 'Trinity' },
  { text: 'Tulare', value: 'Tulare' },
  { text: 'Tuolumne', value: 'Tuolumne' },
  { text: 'Ventura', value: 'Ventura' },
  { text: 'Yolo', value: 'Yolo' },
  { text: 'Yuba', value: 'Yuba' },
];
