export const Constants = {
	TAGS: {
		STRONG: "strong"
	},
	RUNNER: {
		PAGES: {
			HOMEPAGE: 'HOMEPAGE',
			CLIENT_INFORMATION: 'CLIENT_INFORMATION',
			RFP_MEDICAL_INFORMATION: 'RFP_MEDICAL_INFORMATION',
			RFP_MEDICAL_OPTIONS: 'RFP_MEDICAL_OPTIONS',
			RFP_MEDICAL_CONTRIBUTIONS: 'RFP_MEDICAL_CONTRIBUTIONS',
			RFP_MEDICAL_QUOTE: 'RFP_MEDICAL_QUOTE',
			RFP_DENTAL_INFORMATION: 'RFP_DENTAL_INFORMATION',
			RFP_DENTAL_OPTIONS: 'RFP_DENTAL_OPTIONS',
			RFP_DENTAL_CONTRIBUTIONS: 'RFP_DENTAL_CONTRIBUTIONS',
			RFP_DENTAL_QUOTE: 'RFP_DENTAL_QUOTE',
			RFP_VISION_INFORMATION: 'RFP_VISION_INFORMATION',
			RFP_VISION_OPTIONS: 'RFP_VISION_OPTIONS',
			RFP_VISION_CONTRIBUTIONS: 'RFP_VISION_CONTRIBUTIONS',
			RFP_VISION_QUOTE: 'RFP_VISION_QUOTE'
		}
	}
}