module.exports = {
  'icon-url': '"/assets/iconfont/iconfont"',
  'primary-color': '#fdb924',
  'border-radius-base': '2px',
  'font-size-base': '14px',
  'font-family': 'Roboto',
  'link-hover-color': '#1968d0',
  'link-active-color': '#1875f0',
  'input-height-sm': '28px',
  'input-height-base': '34px',
  'input-height-lg': '40px',
  'input-placeholder-color': '#c5c5c5',
  'btn-default-color': '#fdb924',
  'btn-primary-color': '#373737',
  'btn-default-border': '#fdb924',
  'btn-danger-color': '#ff0000',
  'btn-danger-bg': '#fff',
  'btn-danger-border': '#ff0000',
  'btn-height-base': '34px',
  'btn-height-lg': '40px',
  'btn-height-sm': '28px',
  'radio-dot-color': '#808080',
  'screen-md': '1025px',
  'table-row-hover-bg': '#f5f5f5'
};
