FROM hasura/graphql-engine:v2.1.1

ENV DB_HOST=postgres_local
ENV DB_PORT=5432
ENV DB_NAME=aou-local
ENV DB_USER=postgres
ENV DB_MAX_PING_ATTEMPTS=30

COPY ./utils/wait-for-postgresql.sh /utils/

RUN apt-get update && apt-get -y install postgresql-client

CMD /utils/wait-for-postgresql.sh $DB_HOST $DB_PORT $DB_NAME $DB_USER $DB_MAX_PING_ATTEMPTS && /bin/graphql-engine serve
