FROM node:lts-alpine

# Copy source
COPY ./core-be /core-be
COPY ./utils/tsconfig.json ./utils/wait-for-postgresql.sh /utils/

# Working directory
WORKDIR /core-be

# Install dependencies
RUN apk --update add --no-cache postgresql-client && cd /core-be && npm ci --unsafe-perm

ENV NODE_ENV=development
ENV DB_HOST=postgres_local
ENV DB_PORT=5432
ENV DB_NAME=aou-local
ENV DB_USER=postgres
ENV DB_MAX_PING_ATTEMPTS=30

# Start job
CMD /utils/wait-for-postgresql.sh $DB_HOST $DB_PORT $DB_NAME $DB_USER $DB_MAX_PING_ATTEMPTS && npm run typeorm-dev migration:run
