export const GA_CLIENTS_GET = 'app/PlansPage/GA_CLIENTS_GET';
export const GA_CLIENTS_GET_SUCCESS = 'app/PlansPage/GA_CLIENTS_GET_SUCCESS';
export const GA_CLIENTS_GET_ERROR = 'app/PlansPage/GA_CLIENTS_GET_ERROR';

export const REMOVE_ACCESS_TO_CLIENT = 'app/PlansPage/REMOVE_ACCESS_TO_CLIENT';
export const REMOVE_ACCESS_TO_CLIENT_SUCCESS = 'app/PlansPage/REMOVE_ACCESS_TO_CLIENT_SUCCESS';
export const REMOVE_ACCESS_TO_CLIENT_ERROR = 'app/PlansPage/REMOVE_ACCESS_TO_CLIENT_ERROR';
