# See https://symfonycasts.com/screencast/ansistrano/ci-auto-deploy
version: 2

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build

jobs:
  build:
    docker:
    - image: 1and1internet/ubuntu-16-apache-php-7.2
    - image: redis:4.0.8
    - image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
      environment:
        - discovery.type=single-node
        - http.host=0.0.0.0
        - transport.host=127.0.0.1
        - xpack.security.enabled=false
        - ES_JAVA_OPTS=-Xms750m -Xmx750m
    - image: mysql:8.0.12
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes

    steps:
    - checkout
    - run:
        name: box provisioning
        command: |
          apt update
          composer self-update
          composer install --prefer-dist --no-interaction
          cp app/config/parameters.yml.dist app/config/parameters.yml
          php app/console doctrine:database:create --env=test
          php app/console doctrine:schema:create --env=test

    - run:
        name: Run web server
        command: php app/console server:run --env=test -vvv localhost:8080
        background: true

    - run: php app/console lint:yaml app/
    - run: php app/console lint:yaml src/
    - run: php bin/phpunit -c app/