const DPPO = {
  planType: 'DPPO',
  planName: '',
  selectedCarrier: {},
  selectedNetwork: {},
  rfpQuoteNetworkPlanId: null,
  benefits: [
    {
      name: 'Calendar Year Maximum',
      sysName: 'CALENDAR_YEAR_MAXIMUM',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      placeholderIn: 'e.g., $1,500',
      placeholderOut: 'e.g., $1,500',
    }, {
      name: 'Individual Deductible',
      sysName: 'DENTAL_INDIVIDUAL',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      placeholderIn: 'e.g., $50',
      placeholderOut: 'e.g., $50',
    }, {
      name: 'Family Deductible',
      sysName: 'DENTAL_FAMILY',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      placeholderIn: 'e.g., $150',
      placeholderOut: 'e.g., $150',
    }, {
      name: 'Waived for Preventive?',
      sysName: 'WAIVED_FOR_PREVENTIVE',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      placeholderIn: 'e.g., Yes',
      placeholderOut: 'e.g., No',
    }, {
      name: 'Class I - Preventive',
      sysName: 'CLASS_1_PREVENTIVE',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      placeholderIn: 'e.g., 100%',
      placeholderOut: 'e.g., 100%',
    }, {
      name: 'Class II - Basic',
      sysName: 'CLASS_2_BASIC',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      placeholderIn: 'e.g., 80%',
      placeholderOut: 'e.g., 80%',
    }, {
      name: 'Class III - Major',
      sysName: 'CLASS_3_MAJOR',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      placeholderIn: 'e.g., 60%',
      placeholderOut: 'e.g., 60%',
    }, {
      name: 'Class IV - Orthodontia',
      sysName: 'CLASS_4_ORTHODONTIA',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      placeholderIn: 'e.g., 50% or N/A',
      placeholderOut: 'e.g., 50% or N/A',
    }, {
      name: 'Orthodontia Lifetime Max',
      sysName: 'ORTHODONTIA_LIFETIME_MAX',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      placeholderIn: 'e.g., $1,000 or N/A',
      placeholderOut: 'e.g., $1,000 or N/A',
    }, {
      name: 'Orthodontia Eligibility',
      sysName: 'ORTHO_ELIGIBILITY',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      placeholderIn: 'e.g., Adult & Child',
      placeholderOut: 'e.g., Adult & Child',
    }, {
      name: 'Dental Reimbursement Schedule',
      sysName: 'REIMBURSEMENT_SCHEDULE',
      typeOut: 'STRING',
      valueOut: '',
      placeholderIn: 'e.g., N/A',
      placeholderOut: 'e.g., 90th UCR',
    }, {
      name: 'Implant Coverage',
      sysName: 'IMPLANT_COVERAGE',
      typeIn: 'STRING',
      typeOut: 'STRING',
      valueIn: '',
      valueOut: '',
      placeholderIn: 'e.g., 50% or N/A',
      placeholderOut: 'e.g., 50% or N/A',
    },
  ],
};

export default DPPO;
