# source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge',
  'DevSupport',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTBlob',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket'
]

pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
pod 'RNI18n', :path => '../node_modules/react-native-i18n'
pod 'RNSVG', :path => '../node_modules/react-native-svg'
pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

pod 'GoogleMaps', '2.5.0'
pod 'react-native-maps', :path => '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'

pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'

pod 'Firebase/Core', '~> 5.14.0'
pod 'Firebase/Messaging', '~> 5.14.0'

pod 'lottie-ios', :path => '../node_modules/lottie-ios'
pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

pod 'TouchID', :path => '../node_modules/react-native-touch-id'
pod 'RNKeychain', :path => '../node_modules/react-native-keychain'

pod 'react-native-haptic', :path => '../node_modules/react-native-haptic'

target 'oteApp'

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == "React"
#       target.remove_from_project
#     end
#   end
# end

post_install do |installer|
  installer.pods_project.targets.each do |target|

    # The following is needed to ensure the "archive" step works in XCode.
    # It removes React & Yoga from the Pods project, as it is already included in the main project.
    # Without this, you'd see errors when you archive like:
    # "Multiple commands produce ... libReact.a"
    # "Multiple commands produce ... libyoga.a"

    targets_to_ignore = %w(React yoga)

    if targets_to_ignore.include? target.name
      target.remove_from_project
    end

  end
end
