import React from 'react';
import PropTypes from 'prop-types';
import { Modal, Header, Button } from 'semantic-ui-react';
import { Link } from 'react-router';

class EULAModal extends React.Component { // eslint-disable-line react/prefer-stateless-function

  static propTypes = {
    open: PropTypes.bool.isRequired,
    closeModal: PropTypes.func.isRequired,
    acceptModal: PropTypes.func.isRequired,
  };

  render() {
    const { open, closeModal, acceptModal } = this.props;

    return (
      <Modal open={open} className="profile-eula">
        <Modal.Content>

          <Modal.Description>
            <Header as="h1">End User License Agreement</Header>
            <Header as="h1">BenRevo Licensed Service</Header>
            <p className="eula-important">IMPORTANT – PLEASE READ CAREFULLY THE TERMS OF THIS SOFTWARE LICENSE AGREEMENT (“AGREEMENT”).  BY CLICKING ON THE “I AGREE” BUTTON: (1) YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTAND, AND AGREE TO BE BOUND BY THIS AGREEMENT; AND, (2) YOU REPRESENT THAT YOU HAVE THE AUTHORITY TO ENTER INTO THIS AGREEMENT PERSONALLY, OR IF YOU HAVE NAMED A COMPANY AS CUSTOMER, ON BEHALF OF THAT COMPANY (YOU OR ANY SUCH COMPANY, THE “CUSTOMER”), AND TO BIND THE CUSTOMER TO THE TERMS OF THIS AGREEMENT.  IF YOU DO NOT AGREE TO ALL TERMS AND CONDITIONS OF THIS AGREEMENT, OR IF YOU DO NOT HAVE SUCH AUTHORITY, YOU SHOULD CLICK ON THE “CANCEL” BUTTON TO DISCONTINUE THE PROCESS OF ACCESSING THE LICENSED SERVICE, AS YOU WILL NOT BE GRANTED A LICENSE TO USE THE LICENSED SERVICE. </p>
            <p><b><span>1.</span>AGREEMENT.</b> This Agreement is a legal agreement between Customer and BenRevo, Inc. (“Company”) for the access to and use of Company’s online services, which includes computer software and may include associated, media, printed materials and “online” or electronic documentation (the “Licensed Service”).  By accepting this Agreement, you are also accepting the additional terms and conditions, if any, set forth therein.</p>
            <p><b><span>2.</span>LICENSE.</b> Subject to the terms and conditions of this Agreement, Company grants to Customer a nontransferable, nonexclusive, royalty-free, revocable, worldwide license (without the right to sublicense) to permit those individuals authorized by Customer (“Users”) to access, use, execute and display the Licensed Service solely for Customer’s own internal business operations.</p>
            <p><b><span>3.</span>RESTRICTIONS.</b> The rights granted to Customer in this Agreement are subject to the following restrictions: (a) Customer shall not license, sell, rent, lease, transfer, assign, distribute, host, outsource, disclose or otherwise commercially exploit the Licensed Service or make the Licensed Service available to any third party other than an authorized User; (b) Customer shall not modify, make derivative works of, disassemble, reverse compile or reverse engineer any part of the Licensed Service; (c) Customer shall not access the Licensed Service in order to build a similar or competitive product or service; (d) except as expressly stated herein, no part of the Licensed Service may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means, including but not limited to electronic, mechanical, photocopying, recording or other means; and (e) any future release, update, or other addition to functionality of the Licensed Service shall be subject to the terms of this Agreement, unless Company expressly states otherwise.  Neither Company nor any of its suppliers is obligated to provide any services, updates or upgrades to the Licensed Service.  Customer shall preserve all copyright and other proprietary rights notices in the Licensed Service and all copies thereof.</p>
            <p><b><span>4.</span>OWNERSHIP.</b> All right, title, and interest, including all intellectual property rights, in and to the Licensed Service (including any and all copies thereof) shall be owned and retained by Company or its suppliers.  Any rights not expressly granted by Company in the Agreement are reserved.  Customer acknowledges that it acquires no ownership interest in the Licensed Service.</p>
            <p><b><span>5.</span>DISCLAIMER OF WARRANTIES.</b> THE LICENSED SERVICE IS PROVIDED TO CUSTOMER FREE OF CHARGE, AND ON AN “AS-IS” BASIS.  COMPANY PROVIDES NO TECHNICAL SUPPORT, WARRANTIES OR REMEDIES FOR THE LICENSED SERVICE.  COMPANY AND ITS SUPPLIERS DISCLAIM ALL EXPRESS, IMPLIED OR STATUTORY WARRANTIES RELATING TO THE LICENSED SERVICE, AND OTHERWISE UNDER THIS AGREEMENT, INCLUDING BUT NOT LIMITED TO, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.  COMPANY DOES NOT WARRANT THAT USE OF THE LICENSED SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE LICENSED SERVICE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.  FURTHER, COMPANY DOES NOT WARRANT THE ACCURACY OR COMPLETENESS OF ANY DATA, INCLUDING WITHOUT LIMITATION, ANY QUOTES OR OTHER DATA REGARDING THIRD-PARTY PRODUCTS OR SERVICES, PROVIDED VIA THE LICENSED SERVICE AND CUSTOMER ACKNOWLEDGES AND AGREES THAT CUSTOMER ASSUMES ALL RISKS IN USING AND RELYING UPON ANY AND ALL SUCH DATA.</p>
            <p><b><span>6.</span>LIMITATION OF REMEDIES AND DAMAGES.</b> TO THE MAXIMUM EXTENT PERMITTED BY LAW, NEITHER COMPANY NOR ITS SUPPLIERS SHALL BE RESPONSIBLE OR LIABLE WITH RESPECT TO THE LICENSED SERVICE OR ANY OTHER SUBJECT MATTER OF THIS AGREEMENT OR TERMS OR CONDITIONS RELATED THERETO UNDER ANY CONTRACT, NEGLIGENCE, STRICT LIABILITY OR OTHER THEORY: (A) FOR LOSS OR INACCURACY OF DATA OR COST OF PROCUREMENT OF SUBSTITUTE GOODS, SERVICES OR TECHNOLOGY, (B) FOR ANY LOST REVENUES OF LOST PROFITS; OR (C) FOR ANY INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES.  TO THE MAXIMUM EXTENT PERMITTED BY LAW, COMPANY’S AGGREGATE CUMULATIVE LIABILITY HEREUNDER SHALL NOT EXCEED THE GREATER OF ONE HUNDRED U.S. DOLLARS ($100.00) OR THE AMOUNT PAID BY CUSTOMER FOR THE LICENSED SERVICE THAT CAUSED SUCH DAMAGE.</p>
            <p><b><span>7.</span>INDEMNITY.</b> You agree to indemnify and hold harmless Company, and its employees, officers, directors, contractors, customers and agents from and against any and all claims, demands, suits, or other legal action brought by a third party against any of the foregoing indemnitees, (each, a “Claim”) and shall pay any and all liabilities, damages, costs, and expenses (including, without limitation, reasonable attorneys’ fees) (“Losses”) suffered or incurred by any of the foregoing indemnitees in connection with such Claim to the extent such Losses arise from or otherwise result from Your breach of this Agreement and/or Your use of the Licensed Service.</p>
            <p><b><span>8.</span>BASIS OF BARGAIN.</b> The warranty disclaimer and limitation of liability set forth above are fundamental elements of the basis of the agreement between Company and Customer.  Company would not be able to provide the Licensed Service on an economic basis without such limitations.  The warranty disclaimer and limitation of liability inure to the benefit of Company’s suppliers.</p>
            <p><b><span>9.</span>TERM AND TERMINATION.</b> This Agreement and the licenses granted hereunder are effective on the date Customer accepts this Agreement by agreeing to its terms as set forth herein, and shall continue unless and until this Agreement is terminated by either party pursuant to this section.  Company may terminate this Agreement immediately upon notice to Customer: (i) in the event that Customer materially breaches any of the terms hereof; or, (ii) if Company discontinues the Licensed Service; or, (iii) if Customer changes the business model of the Licensed Service to a fee-bearing service.  Customer may terminate this Agreement at any time, with or without cause.  Customer may terminate this Agreement by sending either an email to support@benrevo.com with Customer’s name and the subject “TERMINATION OF LICENSE” or a letter by United States mail to: support@benrevo.com or to such other address as Company may specify in writing by posting the new address on the Company website.  Upon termination, the license granted hereunder shall terminate and Customer shall immediately cease all access to and use of the Licensed Service, and shall destroy any copies of materials regarding the Licensed Service in its possession, but the terms of this Agreement which are intended to survive termination, including, without limitation, terms regarding ownership, warranty disclaimers, limitations of liability, indemnity and general terms, will remain in effect.</p>
            <p><b><span>10.</span>MODIFICATIONS.</b> Company reserves the right to change the terms and conditions of this Agreement or its policies relating to the Licensed Service at any time.  We will notify you of any material changes to this Agreement by sending you an e-mail to the last e-mail address you provided to us or by prominently posting notice of the changes on our website.  Any material changes to this Agreement will be effective upon the earliest of thirty (30) calendar days following our dispatch of an e-mail notice to you or thirty (30) calendar days following our posting of notice of the changes on our website.  These changes will be effective immediately for new users of our Licensed Service.  Please note that at all times you are responsible for providing us with your most current e-mail address.  In the event that the last e-mail address that you have provided us is not valid, or for any reason is not capable of delivering to you the notice described above, our dispatch of the e-mail containing such notice will nonetheless constitute effective notice of the changes described in the notice.  If you do not agree with the changes to this Agreement, you must notify us prior to the effective date of the changes that you wish to terminate your license to the Licensed Service.  Continued use of the Licensed Service, following notice of such changes, shall indicate your acknowledgement of such changes and agreement to be bound by the terms and conditions of such changes.</p>
            <p><b><span>11.</span>EXPORT.</b> The Licensed Service and related technology are subject to U.S. export control laws and may be subject to export or import regulations in other countries.  Customer agrees not to export, reexport, or transfer, directly or indirectly, any U.S. technical data acquired from Company, or any products utilizing such data, in violation of the United States export laws or regulations.  Customer will indemnify and hold Company harmless from any and all claims, losses, liabilities, damages, fines, penalties, costs and expenses (including attorney’s fees) arising from or relating to any breach by Customer of its obligations under this section.  Customer’s obligations under this section shall survive the expiration or termination of this Agreement.</p>
            <p><b><span>12.</span>GENERAL TERMS.</b> Neither the rights nor the obligations arising under this Agreement are assignable by Customer, and any such attempted assignment or transfer shall be void and without effect.  Company may freely assign this Agreement to any third party.  This Agreement shall be governed by and construed in accordance with the laws of the State of California and the United States without regard to the conflict of laws provisions therein that would require application of the laws of another jurisdiction.  Any action under or relating to this Agreement shall be brought solely in the state and federal courts located in California with sole venue in the courts located in San Diego County, California and each party hereby submits to the personal jurisdiction of such courts, except that Company may seek relief in any court of competent jurisdiction to protect or enforce its intellectual property and proprietary rights.  The United Nations Convention on Contracts for the International Sale of Goods shall not apply to this Agreement.  In the event that any provision of this Agreement is found to be contrary to law, then such provision shall be construed as nearly as possible to reflect the intention of the parties, with the other provisions remaining in full force and effect.  Any notice to Customer may be provided by email.  This Agreement constitutes the entire agreement between the parties pertaining to the subject matter hereof, and any and all written or oral agreements previously existing between the parties are expressly canceled.  Except as otherwise expressly provided in this Agreement, any modifications of this Agreement must be in writing and agreed to by both parties.</p>
            <p className="eula-important">
              QUESTIONS OR ADDITIONAL INFORMATION.  If you have questions regarding this Agreement, or wish to obtain additional information, please send an e-mail to <Link href="mailto:support@benrevo.com">support@benrevo.com</Link>.
            </p>
          </Modal.Description>
        </Modal.Content>
        <Modal.Actions>
          <Button className="blue" onClick={acceptModal}>I Accept</Button>
          <Button basic onClick={closeModal}>Cancel</Button>
        </Modal.Actions>
      </Modal>
    );
  }
}

export default EULAModal;
