# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  utf8mb4
                default_table_options:
                    charset: utf8mb4 # https://symfony.com/doc/3.3/doctrine.html#configuring-the-database
                    collate: utf8mb4_0900_ai_ci #MySQL8-specific
            geonames:
                driver:   %database_driver_geonames%
                host:     %database_host_geonames%
                port:     %database_port_geonames%
                dbname:   %database_name_geonames%
                user:     %database_user_geonames%
                password: %database_password_geonames%
                charset:  UTF8 #TODO change on utf8mb4
            sothebys:
                driver:   %database_driver_sothebys%
                host:     %database_host_sothebys%
                port:     %database_port_sothebys%
                dbname:   %database_name_sothebys%
                user:     %database_user_sothebys%
                password: %database_password_geonames%
                charset:  UTF8 #TODO change on utf8mb4

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            Embeddable:
                prefix: AppBundle\Entity\Embeddable
                dir: %kernel.root_dir%/../src/AppBundle/Entity/Embeddable
                type: annotation

doctrine_migrations:
    dir_name: %kernel.root_dir%/migrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations