dunglas_angular_csrf:
    token:
        # The CSRF token id
        id: api
    header:
        # The name of the HTTP header to check (default to the AngularJS default)
        name: X-XSRF-TOKEN
    cookie:
        # The name of the cookie to set (default to the AngularJS default)
        name: XSRF-TOKEN
        # Expiration time of the cookie
        expire: 0
        # Path of the cookie
        path: /
        # Domain of the cookie
        domain: luxuryaffairs.co.uk
        # If true, set the cookie only on HTTPS connection
        secure: false
        # Patterns of URLs to set the cookie
        set_on:
            - { path: "^/", methods: [GET, HEAD, OPTIONS] }

    # Patterns of URLs to check for a valid CSRF token
    # See:
    # http://www.django-rest-framework.org/topics/ajax-csrf-cors/#csrf-protection
    # https://stackoverflow.com/a/4466031/2235085
    secure:
        - { path: "^/api", methods: [POST, PUT, PATCH, DELETE] }
