fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User\User
    from_email:
        address:        %email_noreply%
        sender_name:    %app_name%
    service:
        mailer: fos_user.mailer.twig_swift # use twig to send HTML emails
    registration:
        form:
            type: ha_user_registration
        confirmation:
            enabled: false
    resetting:
        email:
            template: AppBundle:email/user:reset.email.twig
