export const data = [
  {
    symbol: 'SPRT',
    company: 'support.com Inc.',
    price: '$2.79',
    change: 4.62,
    marketValue: { shortFormattedCurrency: '$10' },
  },
  {
    symbol: 'ROOT',
    company: 'Root Inc. Cl A',
    price: '$8.73',
    change: -7.25,
    marketValue: { shortFormattedCurrency: '$12' },
  },
  {
    symbol: 'ACY',
    company: 'AeroCentury Corp.',
    price: '$7.35',
    change: 2.78,
    marketValue: { shortFormattedCurrency: '$23' },
  },
  {
    symbol: 'PUMB',
    company: 'PubMatic Inc.',
    price: '$35.64',
    change: -3.65,
    marketValue: { shortFormattedCurrency: '$51' },
  },
  {
    symbol: 'ESPR',
    company: 'PubMatic Inc.',
    price: '$35.64',
    change: -3.65,
    marketValue: { shortFormattedCurrency: '$1' },
  },
  {
    symbol: 'OTRK',
    company: 'PubMatic Inc.',
    price: '$35.64',
    change: -3.65,
    marketValue: { shortFormattedCurrency: '$5' },
  },
  {
    symbol: 'BLNK',
    company: 'PubMatic Inc.',
    price: '$35.64',
    change: -3.65,
    marketValue: { shortFormattedCurrency: '$84' },
  },
  {
    symbol: 'CLOV',
    company: 'PubMatic Inc.',
    price: '$35.64',
    change: -3.65,
    marketValue: { shortFormattedCurrency: '$33' },
  },
  {
    symbol: 'MAXN',
    company: 'PubMatic Inc.',
    price: '$35.64',
    change: 3.65,
    marketValue: { shortFormattedCurrency: '$23' },
  },
  {
    symbol: 'ATNF',
    company: 'PubMatic Inc.',
    price: '$35.64',
    change: -3.65,
    marketValue: { shortFormattedCurrency: '$34' },
  },
  {
    symbol: 'ASO',
    company: 'PubMatic Inc.',
    price: '$35.64',
    change: -3.65,
    marketValue: { shortFormattedCurrency: '$19' },
  },
  {
    symbol: 'GEO',
    company: 'PubMatic Inc.',
    price: '$35.64',
    change: -3.65,
    marketValue: { shortFormattedCurrency: '$308' },
  },
  {
    symbol: 'WKHS',
    company: 'PubMatic Inc.',
    price: '$35.64',
    change: -3.65,
    marketValue: { shortFormattedCurrency: '$204' },
  },
  {
    symbol: 'FLGT',
    company: 'PubMatic Inc.',
    price: '$35.64',
    change: -3.65,
    marketValue: { shortFormattedCurrency: '$111' },
  },
];
