apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: app
  name: {{ .Release.Name }}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.service.external_port }}
    targetPort: {{ .Values.service.target_port }}
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    component: app
  sessionAffinity: None
  type: {{ .Values.service.type }}
