parameters:
    user_settings:
        - "notificationNetwork"
        - "notificationStories"
        - "notificationsAll"
        - "facebookAutoshare"
        - "twitterAutoshare"
        - "linkedinAutoshare"
        - "networksOnProfile"


