<?php

namespace Test\AppBundle\Import_\Adapter\Sothebys;

use AppBundle\Import\Adapter\Sothebys\FeedPropertyIterator;
use Test\AppBundle\Import_\Adapter\Sothebys\Mock\HydratorMockStatement;

class FeedPropertyIteratorTest extends \PHPUnit_Framework_TestCase
{
    public function testTraversity()
    {
        $rows = [
            [
                'srl_listing_guid' => '187DE530-576C-4471-B782-4E4C5CE4D6D9',
                'srl_mls_id' => '',
                'srl_listing_id' => 'PGKCZR',
                'srl_listing_status' => 'AC',
                'srl_address1' => '54 Avenue Fresnaye',
                'srl_address2' => '',
                'srl_address3' => '',
                'srl_latitude' => '-33.926590000',
                'srl_longitude' => '18.389080000',
                'srl_bedrooms' => '5',
                'srl_full_bath' => '6',
                'srl_half_bath' => '1',
                'srl_three_quarter_bath' => '',
                'srl_neighborhood_name' => 'Fresnaye',
                'srl_city' => 'Cape Town',
                'srl_country_iso_code' => 'ZA',
                'srl_state_iso_code' => 'WC',
                'srl_postal_code' => '8005',
                'srl_show_address' => 'N',
                'srl_listing_type' => 'Residential Sale',
                'srl_property_type' => 'R',
                'srl_property_subtype' => '44',
                'srl_list_price' => '35000000.0000',
                'srl_show_list_price' => 'Y',
                'srl_expiration_date' => '03/26/2017',
                'srl_currency_code' => 'ZAR',
                'srl_year_built' => '',
                'srl_building_area' => '',
                'srl_building_area_uom' => '',
                'srl_lot_size' => '',
                'srl_lot_size_uom' => '',
                'srl_source_listing_url' => 'http://www.sothebysrealty.com/id/PGKCZR',
                'srl_last_update_date' => '04/17/2016 00:15:17.077',
                'srlr_property_remark' => '5 Bedroom (all en suite) mansion an entertainers dream! Study, lunge, dining room, family room (TV/Gym rooms, bar and 2 outdoor entertainers decks (braai) with sea view. 3 garages 2 maids rooms / staff accommodation, 2 pools Fresnaye property grew 108 percent from 2007 to 2014.',
                'srlr_language_code' => 'EN',
                'srlpf_feature_group_key' => '11',
                'srlpf_feature_key' => '155',
                'srom_url' => 'http://m.sothebysrealty.com/236i0/065y67fx2dppm12qejjgms8ra1i',
                'srom_image_sequence_no' => '12',
                'srom_last_update_date' => '02/25/2016 08:26:01.740',
                'srlvid_url' => null,
                'srlvid_image_sequence_no' => null,
                'srlvid_last_update_date' => null,
                'sa_agent_key' => '4604258',
            ],
            [
                'srl_listing_guid' => '187DE530-576C-4471-B782-4E4C5CE4D6D9',
                'srl_mls_id' => '',
                'srl_listing_id' => 'PGKCZR',
                'srl_listing_status' => 'AC',
                'srl_address1' => '54 Avenue Fresnaye',
                'srl_address2' => '',
                'srl_address3' => '',
                'srl_latitude' => '-33.926590000',
                'srl_longitude' => '18.389080000',
                'srl_bedrooms' => '5',
                'srl_full_bath' => '6',
                'srl_half_bath' => '1',
                'srl_three_quarter_bath' => '',
                'srl_neighborhood_name' => 'Fresnaye',
                'srl_city' => 'Cape Town',
                'srl_country_iso_code' => 'ZA',
                'srl_state_iso_code' => 'WC',
                'srl_postal_code' => '8005',
                'srl_show_address' => 'N',
                'srl_listing_type' => 'Residential Sale',
                'srl_property_type' => 'R',
                'srl_property_subtype' => '44',
                'srl_list_price' => '35000000.0000',
                'srl_show_list_price' => 'Y',
                'srl_expiration_date' => '03/26/2017',
                'srl_currency_code' => 'ZAR',
                'srl_year_built' => '',
                'srl_building_area' => '',
                'srl_building_area_uom' => '',
                'srl_lot_size' => '',
                'srl_lot_size_uom' => '',
                'srl_source_listing_url' => 'http://www.sothebysrealty.com/id/PGKCZR',
                'srl_last_update_date' => '04/17/2016 00:15:17.077',
                'srlr_property_remark' => '5 Bedroom (all en suite) mansion an entertainers dream! Study, lunge, dining room, family room (TV/Gym rooms, bar and 2 outdoor entertainers decks (braai) with sea view. 3 garages 2 maids rooms / staff accommodation, 2 pools Fresnaye property grew 108 percent from 2007 to 2014.',
                'srlr_language_code' => 'EN',
                'srlpf_feature_group_key' => '11',
                'srlpf_feature_key' => '161',
                'srom_url' => 'http://m.sothebysrealty.com/236i0/065y67fx2dppm12qejjgms8ra1i',
                'srom_image_sequence_no' => '12',
                'srom_last_update_date' => '02/25/2016 08:26:01.740',
                'srlvid_url' => null,
                'srlvid_image_sequence_no' => null,
                'srlvid_last_update_date' => null,
                'sa_agent_key' => '4604258',
            ],
            [
                'srl_listing_guid' => '187DE530-576C-4471-B782-4E4C5CE4D6D9',
                'srl_mls_id' => '',
                'srl_listing_id' => 'PGKCZR',
                'srl_listing_status' => 'AC',
                'srl_address1' => '54 Avenue Fresnaye',
                'srl_address2' => '',
                'srl_address3' => '',
                'srl_latitude' => '-33.926590000',
                'srl_longitude' => '18.389080000',
                'srl_bedrooms' => '5',
                'srl_full_bath' => '6',
                'srl_half_bath' => '1',
                'srl_three_quarter_bath' => '',
                'srl_neighborhood_name' => 'Fresnaye',
                'srl_city' => 'Cape Town',
                'srl_country_iso_code' => 'ZA',
                'srl_state_iso_code' => 'WC',
                'srl_postal_code' => '8005',
                'srl_show_address' => 'N',
                'srl_listing_type' => 'Residential Sale',
                'srl_property_type' => 'R',
                'srl_property_subtype' => '44',
                'srl_list_price' => '35000000.0000',
                'srl_show_list_price' => 'Y',
                'srl_expiration_date' => '03/26/2017',
                'srl_currency_code' => 'ZAR',
                'srl_year_built' => '',
                'srl_building_area' => '',
                'srl_building_area_uom' => '',
                'srl_lot_size' => '',
                'srl_lot_size_uom' => '',
                'srl_source_listing_url' => 'http://www.sothebysrealty.com/id/PGKCZR',
                'srl_last_update_date' => '04/17/2016 00:15:17.077',
                'srlr_property_remark' => '5 Bedroom (all en suite) mansion an entertainers dream! Study, lunge, dining room, family room (TV/Gym rooms, bar and 2 outdoor entertainers decks (braai) with sea view. 3 garages 2 maids rooms / staff accommodation, 2 pools Fresnaye property grew 108 percent from 2007 to 2014.',
                'srlr_language_code' => 'EN',
                'srlpf_feature_group_key' => '11',
                'srlpf_feature_key' => '164',
                'srom_url' => 'http://m.sothebysrealty.com/236i0/065y67fx2dppm12qejjgms8ra1i',
                'srom_image_sequence_no' => '12',
                'srom_last_update_date' => '02/25/2016 08:26:01.740',
                'srlvid_url' => null,
                'srlvid_image_sequence_no' => null,
                'srlvid_last_update_date' => null,
                'sa_agent_key' => '4604258',
            ],
            [
                'srl_listing_guid' => '0001F233-1721-43EE-99EC-EA50E0A034DC',
                'srl_mls_id' => '20162316',
                'srl_listing_id' => 'NGNSCM',
                'srl_listing_status' => 'AC',
                'srl_address1' => 'E16',
                'srl_address2' => '',
                'srl_address3' => '',
                'srl_latitude' => '34.933254242',
                'srl_longitude' => '-82.960403442',
                'srl_bedrooms' => '',
                'srl_full_bath' => '',
                'srl_half_bath' => '',
                'srl_three_quarter_bath' => '',
                'srl_neighborhood_name' => 'The Cliffs at Keowee Falls',
                'srl_city' => 'Salem',
                'srl_country_iso_code' => 'US',
                'srl_state_iso_code' => 'SC',
                'srl_postal_code' => '29676',
                'srl_show_address' => 'Y',
                'srl_listing_type' => 'Residential Sale',
                'srl_property_type' => 'LL',
                'srl_property_subtype' => '18',
                'srl_list_price' => '345000.0000',
                'srl_show_list_price' => 'Y',
                'srl_expiration_date' => '08/19/2016',
                'srl_currency_code' => 'USD',
                'srl_year_built' => '',
                'srl_building_area' => '',
                'srl_building_area_uom' => '',
                'srl_lot_size' => '2.42',
                'srl_lot_size_uom' => 'AC',
                'srl_source_listing_url' => 'http://www.sothebysrealty.com/id/NGNSCM',
                'srl_last_update_date' => '05/10/2016 14:26:00.437',
                'srlr_property_remark' => 'This private, 2.42 acre custom home site is conveniently located for easy ingress and egress and only minutes from the new $3mm Falls South amenities and highway 11 market. Enjoy a level building site and year-round vistas of emerald green Lake Keowee and the mountains from custom home\'s deck  outside living areas. A winding walk to the shoreline reveals a quiet and private cove location and a covered slip dock awaiting the arrival of your pleasure craft for cruising Lake Keowee\'s crystal clear waters. Impressively dotted with Oaks, Maples and other hardwoods, this home site is far from ordinary.',
                'srlr_language_code' => 'EN',
                'srlpf_feature_group_key' => '25',
                'srlpf_feature_key' => '1046',
                'srom_url' => 'http://m.sothebysrealty.com/236i0/fzgzv74tnqtbm9y9ggkds3ebv0i',
                'srom_image_sequence_no' => '4',
                'srom_last_update_date' => '05/10/2016 14:26:00.480',
                'srlvid_url' => null,
                'srlvid_image_sequence_no' => null,
                'srlvid_last_update_date' => null,
                'sa_agent_key' => '4030489',
            ],
        ];

        $output = [
            [
                'listing_guid' => '187DE530-576C-4471-B782-4E4C5CE4D6D9',
                'mls_id' => '',
                'listing_id' => 'PGKCZR',
                'listing_status' => 'AC',
                'address1' => '54 Avenue Fresnaye',
                'address2' => '',
                'address3' => '',
                'latitude' => '-33.926590000',
                'longitude' => '18.389080000',
                'bedrooms' => '5',
                'full_bath' => '6',
                'half_bath' => '1',
                'three_quarter_bath' => '',
                'neighborhood_name' => 'Fresnaye',
                'city' => 'Cape Town',
                'country_iso_code' => 'ZA',
                'state_iso_code' => 'WC',
                'postal_code' => '8005',
                'show_address' => 'N',
                'listing_type' => 'Residential Sale',
                'property_type' => 'R',
                'property_subtype' => '44',
                'list_price' => '35000000.0000',
                'show_list_price' => 'Y',
                'expiration_date' => '03/26/2017',
                'currency_code' => 'ZAR',
                'year_built' => '',
                'building_area' => '',
                'building_area_uom' => '',
                'lot_size' => '',
                'lot_size_uom' => '',
                'source_listing_url' => 'http://www.sothebysrealty.com/id/PGKCZR',
                'last_update_date' => '04/17/2016 00:15:17.077',
                'descriptions' => [
                    [
                        'property_remark' => '5 Bedroom (all en suite) mansion an entertainers dream! Study, lunge, dining room, family room (TV/Gym rooms, bar and 2 outdoor entertainers decks (braai) with sea view. 3 garages 2 maids rooms / staff accommodation, 2 pools Fresnaye property grew 108 percent from 2007 to 2014.',
                        'language_code' => 'EN',
                    ],
                ],
                'prop_features' => [
                    [
                        'group_key' => '11',
                        'key' => '155',
                    ],
                    [
                        'group_key' => '11',
                        'key' => '161',
                    ],
                    [
                        'group_key' => '11',
                        'key' => '164',
                    ],
                ],
                'photos' => [
                    [
                        'url' => 'http://m.sothebysrealty.com/236i0/065y67fx2dppm12qejjgms8ra1i',
                        'image_sequence_no' => '12',
                        'last_update_date' => '02/25/2016 08:26:01.740',
                    ],
                ],
                'videos' => [],
                'agents' => [
                    [
                        'agent_key' => '4604258',
                    ],
                ],
            ],
            [
                'listing_guid' => '0001F233-1721-43EE-99EC-EA50E0A034DC',
                'mls_id' => '20162316',
                'listing_id' => 'NGNSCM',
                'listing_status' => 'AC',
                'address1' => 'E16',
                'address2' => '',
                'address3' => '',
                'latitude' => '34.933254242',
                'longitude' => '-82.960403442',
                'bedrooms' => '',
                'full_bath' => '',
                'half_bath' => '',
                'three_quarter_bath' => '',
                'neighborhood_name' => 'The Cliffs at Keowee Falls',
                'city' => 'Salem',
                'country_iso_code' => 'US',
                'state_iso_code' => 'SC',
                'postal_code' => '29676',
                'show_address' => 'Y',
                'listing_type' => 'Residential Sale',
                'property_type' => 'LL',
                'property_subtype' => '18',
                'list_price' => '345000.0000',
                'show_list_price' => 'Y',
                'expiration_date' => '08/19/2016',
                'currency_code' => 'USD',
                'year_built' => '',
                'building_area' => '',
                'building_area_uom' => '',
                'lot_size' => '2.42',
                'lot_size_uom' => 'AC',
                'source_listing_url' => 'http://www.sothebysrealty.com/id/NGNSCM',
                'last_update_date' => '05/10/2016 14:26:00.437',
                'descriptions' => [
                    [
                        'property_remark' => 'This private, 2.42 acre custom home site is conveniently located for easy ingress and egress and only minutes from the new $3mm Falls South amenities and highway 11 market. Enjoy a level building site and year-round vistas of emerald green Lake Keowee and the mountains from custom home\'s deck  outside living areas. A winding walk to the shoreline reveals a quiet and private cove location and a covered slip dock awaiting the arrival of your pleasure craft for cruising Lake Keowee\'s crystal clear waters. Impressively dotted with Oaks, Maples and other hardwoods, this home site is far from ordinary.',
                        'language_code' => 'EN',
                    ],
                ],
                'prop_features' => [
                    [
                        'group_key' => '25',
                        'key' => '1046',
                    ],
                ],
                'photos' => [
                    [
                        'url' => 'http://m.sothebysrealty.com/236i0/fzgzv74tnqtbm9y9ggkds3ebv0i',
                        'image_sequence_no' => '4',
                        'last_update_date' => '05/10/2016 14:26:00.480',
                    ],
                ],
                'videos' => [],
                'agents' => [
                    [
                        'agent_key' => '4030489',
                    ],
                ],
            ],
        ];

        $stmt = new HydratorMockStatement($rows);
        $it = new FeedPropertyIterator($stmt);
        foreach ($it as $key => $item) {
            $this->assertEquals($output[$key], $item);
        }
    }

    public function testEmptySet()
    {
        $rows = [];

        $stmt = new HydratorMockStatement($rows);
        $it = new FeedPropertyIterator($stmt);

        $i = 0;
        foreach ($it as $item) {
            ++$i;
        }
        $this->assertEquals(0, $i);
    }
}
