export default {
  ROOM_SEARCH: 'ROOM_SEARCH',
  ROOM_SELECT: 'ROOM_SELECT',
  ROOM_UNSELECT: 'ROOM_UNSELECT',
  ROOM_COLLECTION_LOAD_SUCCESS: 'ROOM_COLLECTION_LOAD_SUCCESS',
  ROOM_DETAILS_LOAD_SUCCESS: 'ROOM_DETAILS_LOAD_SUCCESS',
  ROOM_ONLINE_UPDATE: 'ROOM_ONLINE_UPDATE',
  UPDATE_ROOM_DETAILS: 'UPDATE_ROOM_DETAILS',
};
