const Constants = {
	SET_MOBILE_DEVICE: "SET_MOBILE_DEVICE",
	SET_DESKTOP_DEVICE: "SET_DESKTOP_DEVICE",
	SHOW_NOTIFICATION: "SHOW_NOTIFICATION",
	HIDE_NOTIFICATION: "HIDE_NOTIFICATION",
	ACCEPT_COOKIES: "ACCEPT_COOKIES",
	REJECT_COOKIES: "REJECT_COOKIES",
	TOGGLE_IS_PRO: "TOGGLE_IS_PRO"
};

export default Constants;