# IMPORTANT: please use downcased cities
LONDON_POSTCODE_PREFIXES = %w(
  WD3 WD4 WD5 WD6 WD7 WD17 WD18 WD19 WD23 WD24 WD25 AL2 HA0 HA1 HA2 HA3 HA4 HA5 HA6 HA7 HA8 HA9 UB1 UB2 UB3 UB4 UB5 UB6 UB7 UB8 UB9 UB10 UB11 UB18
  TW1 TW2 TW3 TW4 TW5 TW6 TW7 TW8 TW9 TW10 TW11 TW12 TW13 TW14 TW15 TW16 TW17 TW18 TW19 TW20 KT1 KT2 KT3 KT4 KT5 KT6 KT7 KT8 KT8 KT9 KT10 KT11 KT12
  KT13 KT14 KT15 KT16 KT17 KT18 KT19 KT20 KT21 KT22 SM1 SM2 SM3 SM4 SM5 SM6 SM7 CR0 CR2 CR3 CR4 CR5 CR6 CR7 CR8 CR9 BR1 BR2 BR3 BR4 BR5 BR6 BR7 BR8
  DA1 DA5 DA6 DA7 DA8 DA14 DA15 DA16 DA17 DA18 RM1 RM2 RM3 RM4 RM5 RM6 RM7 RM8 RM9 RM10 RM11 RM12 RM13 RM14 RM15 RM19 RM20 IG1 IG2 IG3 IG4 IG5 IG6
  IG7 IG8 IG9 IG10 IG11 CM16 EN1 EN2 EN3 EN4 EN5 EN6 EN8 EN9 NW1 NW2 NW3 NW4 NW5 NW6 NW7 NW8 NW9 NW10 NW11 N1 N2 N3 N4 N5 N6 N7 N8 N9 N10 N11 N12 N13
  N14 N15 N16 N17 N18 N19 N20 N21 N22 E1 E1W E2 E3 E4 E5 E6 E7 E8 E9 E10 E11 E12 E13 E14 E15 E16 E17 E18 SE1 SE2 SE3 SE4 SE5 SE6 SE7 SE8 SE9 SE10 SE11
  SE12 SE13 SE14 SE15 SE16 SE17 SE18 SE19 SE20 SE21 SE22 SE23 SE24 SE25 SE26 SE27 SE28 SW1A SW1E SW1H SW1P SW1V SW1W SW1X SW1Y SW2 SW3 SW4 SW5 SW6 SW7
  SW8 SW9 SW10 SW11 SW12 SW13 SW14 SW15 SW16 SW17 SW18 SW19 SW20 W1A W1B W1C W1D W1E W1F W1G W1H W1J W1K W1S W1T W1U W1W W2 W3 W4 W5 W6 W7 W8 W9 W10
  W11 W12 W13 W14 EC1A EC1M EC1N EC1P EC1R EC1V EC1Y EC2A EC2M EC2N EC2P EC2R EC2V EC2Y EC3A EC3M EC3N EC3P EC3R EC3V EC4A EC4M EC4N EC4P EC4R EC4V
  EC4Y WC1A WC1B WC1E WC1H WC1N WC1R WC1V WC1X WC2A WC2B WC2E WC2H WC2N WC2R
).freeze

Seeds.seed(VehicleVendor, :key, [
  { key: '001', name: '001 CARS (Oxford)',                             city: 'oxford',               postcode_prefixes: [], phone: '01865240000' },
  { key: '1AB', name: '1AB Taxis Darlington CT',                       city: 'darlington',           postcode_prefixes: [], phone: '01325350123' },
  { key: '57T', name: 'Ride Hull (OTG041) CT',                         city: 'hull',                 postcode_prefixes: [], phone: '01482575757' },
  { key: 'A2T', name: 'A2B Taxis Truro',                               city: 'truro',                postcode_prefixes: [], phone: '01872272989' },
  { key: 'ABC', name: 'ABC Taxis Ltd Norwich  CT',                     city: 'norwich',              postcode_prefixes: [], phone: '01603666333' },
  { key: 'ABM', name: 'AB Taxis Ltd CT',                               city: 'melksham',             postcode_prefixes: [], phone: '01225353637' },
  { key: 'AC3', name: 'ACE CARS (Crawley) CT ASAP T/A Metro Cars',     city: 'crawley',              postcode_prefixes: [], phone: '01293415415' },
  { key: 'ACG', name: 'Andy Cars (Gloucester)',                        city: 'gloucester',           postcode_prefixes: [], phone: '01452523000' },
  { key: 'ACL', name: 'Amber Cars (CT)',                               city: 'leeds',                postcode_prefixes: [], phone: '01132311366' },
  { key: 'ACT', name: 'Apple Central Taxis',                           city: 'exeter',               postcode_prefixes: [], phone: '01392666666' },
  { key: 'ACW', name: 'ABC Wolverhampton',                             city: 'wolverhampton',        postcode_prefixes: [], phone: '01902333333' },
  { key: 'AEB', name: 'Eastbourne & Country Taxis Ltd',                city: 'eastbourne',           postcode_prefixes: [], phone: '01323720720' },
  { key: 'AJS', name: 'Aura Journeys SPV',                             city: 'newark',               postcode_prefixes: [], phone: '01636676624', specialized: true },
  { key: 'APC', name: 'Alpha Cars',                                    city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '02084402222' },
  { key: 'ARC', name: 'A2B Radio Cars (Birmingham)',                   city: 'solihull',             postcode_prefixes: [], phone: '01217041000' },
  { key: 'ASS', name: 'Associated Taxis & Couriers',                   city: 'stornaway',            postcode_prefixes: [], phone: '01851702300' },
  { key: 'ATA', name: 'ACE ABC TAXIS',                                 city: 'mansfield',            postcode_prefixes: [], phone: '01623654321' },
  { key: 'ATS', name: 'Saturn Taxis (Stirling)',                       city: 'stirling',             postcode_prefixes: [], phone: '01786811111' },
  { key: 'BAT', name: 'Bruche Airport Transfers SPV',                  city: 'warrington',           postcode_prefixes: [], phone: '' },
  { key: 'BCR', name: 'Radio Cabs (Bridgend)',                         city: 'bridgend',             postcode_prefixes: [], phone: '01656655766' },
  { key: 'BEI', name: 'Beeline [Guildford] CT',                        city: 'guidford',             postcode_prefixes: [], phone: '01483823232' },
  { key: 'BHS', name: 'Brighton & Hove Streamline Ltd',                city: 'brighton',             postcode_prefixes: [], phone: '01273324850' },
  { key: 'BLB', name: 'B-Line Taxis Ltd - Barnstaple',                 city: 'barnstaple',           postcode_prefixes: [], phone: '01271322117' },
  { key: 'BLM', name: 'Blue Line Middleborogh',                        city: 'barnstaple',           postcode_prefixes: [], phone: '01642300300' },
  { key: 'BLT', name: 'Blue Line (Barnsley)',                          city: 'barnsley',             postcode_prefixes: [], phone: '01226244444' },
  { key: 'BLU', name: 'Blue Cabs A/C B0044',                           city: 'international dublin', postcode_prefixes: [], phone: '035318022222' },
  { key: 'BR1', name: 'Brunel Total GT',                               city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '02070685000' },
  { key: 'BRT', name: 'B R Taxis Ltd',                                 city: 'evesham',              postcode_prefixes: [], phone: '01386830066' },
  { key: 'BTX', name: 'Bruces Taxis Ltd',                              city: 'falkirk',              postcode_prefixes: [], phone: '01324636000' },
  { key: 'CAM', name: 'Cameron Exec SPV',                              city: 'glasgow',              postcode_prefixes: [], phone: '07702378627', specialized: true },
  { key: 'CAP', name: 'Capstar SPV',                                   city: 'london',               postcode_prefixes: [], phone: '02085687902', specialized: true },
  { key: 'CAR', name: 'Embarque SPV',                                  city: 'london',               postcode_prefixes: [], phone: '02083267600', specialized: true },
  { key: 'CBB', name: 'C Cabs',                                        city: 'blackpool',            postcode_prefixes: [], phone: '01253292929' },
  { key: 'CC1', name: 'City Car Services',                             city: 'london',               postcode_prefixes: [], phone: '' },
  { key: 'CCA', name: 'Cymru Cabs CT',                                 city: 'aberystwyth',          postcode_prefixes: [], phone: '07951580227' },
  { key: 'CCC', name: 'Chubbs Cabs CT',                                city: 'bangor',               postcode_prefixes: [], phone: '01248353535' },
  { key: 'CCL', name: '1-2 Call Cabs Ltd CT',                          city: 'andover',              postcode_prefixes: [], phone: '01264338833' },
  { key: 'CCS', name: 'City Cabs Salisbury',                           city: 'salisbury',            postcode_prefixes: [], phone: '01722423000' },
  { key: 'CED', name: 'Capital Cars Edinburgh',                        city: 'edinburgh',            postcode_prefixes: [], phone: '01313137777' },
  { key: 'CGS', name: 'SRV Executive Transport',                       city: 'luton',                postcode_prefixes: [], phone: '07760616750' },
  { key: 'CGT', name: 'Craigie\'s Taxis',                              city: 'kirkwall',             postcode_prefixes: [], phone: '01856878787' },
  { key: 'CHM', name: 'Chequers',                                      city: 'london',               postcode_prefixes: [], phone: '02082056789' },
  { key: 'CIT', name: 'City Cabs (Stoke-on-Trent)',                    city: 'stoke on trent',       postcode_prefixes: [], phone: '01782844444' },
  { key: 'CLS', name: 'Club Class Cars(Phon',                          city: 'southport',            postcode_prefixes: [], phone: '07831612555' },
  { key: 'CLT', name: 'Central Taxis Limite CT',                       city: 'telford',              postcode_prefixes: [], phone: '01952501050' },
  { key: 'CML', name: 'Camcab Ltd',                                    city: 'cambridge',            postcode_prefixes: [], phone: '01223704704' },
  { key: 'COL', name: 'Collis Car Hire SPV',                           city: 'east horsley',         postcode_prefixes: [], phone: '01483282010', specialized: true },
  { key: 'COT', name: 'Co-op Taxis',                                   city: 'glasgow',              postcode_prefixes: [], phone: '01389753376' },
  { key: 'CRF', name: 'Crawfords SPV',                                 city: 'london',               postcode_prefixes: [], phone: '442088963030', specialized: true },
  { key: 'CRO', name: 'Croydon Circuit Cars (CT)',                     city: 'croydon',              postcode_prefixes: [], phone: '02086804321' },
  { key: 'CSA', name: 'Adderburys Service C',                          city: 'banbury',              postcode_prefixes: [], phone: '01295230074' },
  { key: 'CST', name: 'Castle Cars Arundal',                           city: 'arundel',              postcode_prefixes: [], phone: '01903884444' },
  { key: 'CTB', name: 'Chelmsford Taxibus CT',                         city: 'chelmsford',           postcode_prefixes: [], phone: '01245350350' },
  { key: 'CTN', name: 'Courtesy Taxis Norwich',                        city: 'norwich',              postcode_prefixes: [], phone: '01603446644' },
  { key: 'CTT', name: 'Middlesborough Borough Taxis t/a Boro Cars',    city: 'middlesborough',       postcode_prefixes: [], phone: '01642222222' },
  { key: 'DAB', name: 'Driven A to B',                                 city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '02038485100' },
  { key: 'DAX', name: 'Xpedite',                                       city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '0208­8383333' },
  { key: 'DCD', name: 'Driven Scotland SPV',                           city: 'edinburgh',            postcode_prefixes: [], phone: '01316645555', specialized: true },
  { key: 'DEE', name: 'Dee Cars SPV',                                  city: 'london',               postcode_prefixes: [], phone: '07956262494', specialized: true },
  { key: 'DGT', name: 'Dragon Taxis - Newport NU01',                   city: 'newport',              postcode_prefixes: [], phone: '01633216216' },
  { key: 'DRG', name: 'Dragon Taxis Ltd (Cardiff)',                    city: 'cardiff',              postcode_prefixes: [], phone: '02920333333' },
  { key: 'DTG', name: 'DG Cars',                                       city: 'nottingham',           postcode_prefixes: [], phone: '01159607607' },
  { key: 'DUR', name: 'COLOUR TAXIS',                                  city: 'durham',               postcode_prefixes: [], phone: '01913712727' },
  { key: 'ECB', name: 'E C Private Hire Ltd (Bradford) CT',            city: 'bradford',             postcode_prefixes: [], phone: '01274689999' },
  { key: 'ECL', name: 'Excel',                                         city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '02033883209' },
  { key: 'ECS', name: 'Elite Car Service',                             city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '02089447000' },
  { key: 'EEZ', name: 'EEZY Cabs M/ton Keynes',                        city: 'milton keynes',        postcode_prefixes: [], phone: '01908218218' },
  { key: 'EMT', name: 'Eastwood Mearns Taxis',                         city: 'glasgow',              postcode_prefixes: [], phone: '01416445353' },
  { key: 'EXM', name: 'Executive Cars (EXM)',                          city: 'manchester',           postcode_prefixes: [], phone: '01612367755' },
  { key: 'EXE', name: 'Executours Ltd',                                city: 'abbotts langley',      postcode_prefixes: [], phone: '07774137910' },
  { key: 'FAK', name: 'Fairway and Kenwood',                           city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '02083714089' },
  { key: 'FCB', name: 'Fon-a-cab',                                     city: 'belfast',              postcode_prefixes: [], phone: '02890333333' },
  { key: 'FLC', name: 'Falcon Taxi',                                   city: 'aylesbury',            postcode_prefixes: [], phone: '01296580000' },
  { key: 'FLE', name: 'Fleet Cars',                                    city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '02089523333' },
  { key: 'FOL', name: 'PORTFOLIO CARS',                                city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '01483771166' },
  { key: 'FOT', name: 'Foyle & Delta Cabs',                            city: 'derry',                postcode_prefixes: [], phone: '02871263905' },
  { key: 'FTX', name: 'Fonetax',                                       city: 'stockport',            postcode_prefixes: [], phone: '01614942020' },
  { key: 'FYL', name: 'Fylde Executive Cars',                          city: 'st annes',             postcode_prefixes: [], phone: '01772632020' },
  { key: 'GGT', name: 'GO GREEN TAXIS',                                city: 'didcot',               postcode_prefixes: [], phone: '01235811100' },
  { key: 'GLH', name: 'GLH',                                           city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '02074904222' },
  { key: 'GMC', name: 'Green Metro Cars',                              city: 'reading',              postcode_prefixes: [], phone: '01189666656' },
  { key: 'GOL', name: 'GO LUTON',                                      city: 'luton',                postcode_prefixes: [], phone: '01582494949' },
  { key: 'GRE', name: 'Greenlight Cars',                               city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '01322777777' },
  { key: 'GTC', name: 'Green Tomato Cars',                             city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '02085680022' },
  { key: 'GTR', name: 'GOLDSTAR CABS CT',                              city: 'peterborough',         postcode_prefixes: [], phone: '01733575555' },
  { key: 'GWT', name: 'Glasgow Taxis',                                 city: 'glasgow',              postcode_prefixes: [], phone: '01414296666' },
  { key: 'HAR', name: 'Blueline Cars Harrog',                          city: 'harrogate',            postcode_prefixes: [], phone: '01423530830' },
  { key: 'HCS', name: 'Hull Cars',                                     city: 'glenn',                postcode_prefixes: [], phone: '01482828282' },
  { key: 'HEM', name: 'Trident Niven',                                 city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '02089633100' },
  { key: 'HIT', name: 'Highfields Taxis',                              city: 'leicester',            postcode_prefixes: [], phone: '01162624004' },
  { key: 'HOT', name: 'County Cars CT',                                city: 'thames henley-on',     postcode_prefixes: [], phone: '01491579696' },
  { key: 'INT', name: 'INTERCITY TRANSPORT',                           city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '02089658080' },
  { key: 'IRD', name: 'iRide London Ltd',                              city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '02074331000' },
  { key: 'ITL', name: 'Island Taxis IT110',                            city: 'st peter port',        postcode_prefixes: [], phone: '01481700500' },
  { key: 'IVT', name: 'Inverness Taxis',                               city: 'inverness',            postcode_prefixes: [], phone: '01463222777' },
  { key: 'JLS', name: 'Joseph Louis Santos SPV',                       city: 'london',               postcode_prefixes: [], phone: '07957431067', specialized: true },
  { key: 'JUT', name: 'JUJ TAXIS',                                     city: 'scunthorpe',           postcode_prefixes: [], phone: '01724711111' },
  { key: 'KEC', name: 'K.E. Cars',                                     city: 'manchester',           postcode_prefixes: [], phone: '01614371100' },
  { key: 'KEN', name: 'Blue Star Taxis Kend',                          city: 'kendal',               postcode_prefixes: [], phone: '' },
  { key: 'LCR', name: 'Lamont Chauffeur Services UK Limited SPV',      city: 'widnes',               postcode_prefixes: [], phone: '07710098225', specialized: true },
  { key: 'LFC', name: 'London Film Cars Ltd SPV',                      city: 'london',               postcode_prefixes: [], phone: '07976752207', specialized: true },
  { key: 'LOC', name: 'LOCATION CARS',                                 city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '02078341177' },
  { key: 'LPH', name: 'Lancaster',                                     city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '442037524916' },
  { key: 'LX',  name: 'Luxicabs Limited',                              city: 'jersey',               postcode_prefixes: [], phone: '01534887000' },
  { key: 'MC',  name: 'Metro Taxis Carlisle',                          city: 'carlisle',             postcode_prefixes: [], phone: '01228522088' },
  { key: 'MCA', name: 'Manchester Cars',                               city: 'manchester',           postcode_prefixes: [], phone: '01612366521' },
  { key: 'MCR', name: 'Macclesfield Cars',                             city: 'macclesfield',         postcode_prefixes: [], phone: '01625421111' },
  { key: 'MFC', name: 'Mayfair Cars CT',                               city: 'northampton',          postcode_prefixes: [], phone: '01604471444' },
  { key: 'MPS', name: 'Aqua Cars Ltd',                                 city: 'southsea',             postcode_prefixes: [], phone: '02392818123' },
  { key: 'MSL', name: 'Milllers of Preston a/c 578',                   city: 'preston',              postcode_prefixes: [], phone: '01772884000' },
  { key: 'MTC', name: 'Teletaxis CT',                                  city: 'dundee',               postcode_prefixes: [], phone: '01382825825' },
  { key: 'MTL', name: 'Metro Taxis Ltd Stockport',                     city: 'stockport',            postcode_prefixes: [], phone: '01614808000' },
  { key: 'MTX', name: 'Mantax Manchester',                             city: 'manchester',           postcode_prefixes: [], phone: '01612303333' },
  { key: 'N&B', name: 'Norfolk & Beyond',                              city: 'norfolk',              postcode_prefixes: [], phone: '01953455203' },
  { key: 'NAC', name: 'Need-A-Cab',                                    city: 'plymouth',             postcode_prefixes: [], phone: '01752666222' },
  { key: 'NEW', name: 'Blue Line Taxis AC/NMW01',                      city: 'newcastle upon tyne',  postcode_prefixes: [], phone: '01912626666' },
  { key: 'NML', name: 'Nexus Move Ltd',                                city: 'ashton-under-lyne',    postcode_prefixes: [], phone: '1613302090' },
  { key: 'NOD', name: 'Noda Taxis Ltd',                                city: 'newcastle upon tyne',  postcode_prefixes: [], phone: '01912221888' },
  { key: 'OYS', name: 'Oyster Cabs Ltd',                               city: 'swansea',              postcode_prefixes: [], phone: '01792367777' },
  { key: 'PAR', name: 'Parker Car Service',                            city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '02083804450' },
  { key: 'PCD', name: 'Persona Chauffeurs SPV',                        city: 'high peak',            postcode_prefixes: [], phone: '07704921826', specialized: true },
  { key: 'PDK', name: 'Production Desk Finance Purposes Only',         city: 'london',               postcode_prefixes: [], phone: '',            specialized: true },
  { key: 'PRC', name: 'Miracle Taxis Ltd t/a Premier Cars & Checkers', city: 'reading',              postcode_prefixes: [], phone: '01189500500' },
  { key: 'PRE', name: 'Premier Taxis Cardiff',                         city: 'cardiff',              postcode_prefixes: [], phone: '02920565656' },
  { key: 'PRT', name: 'Perth Radio Taxis CT',                          city: 'perth',                postcode_prefixes: [], phone: '01738580058' },
  { key: 'PTC', name: 'Tower Cab LTD CT',                              city: 'plymouth',             postcode_prefixes: [], phone: '01752252525' },
  { key: 'QEC', name: 'Q Executive Cars SPV',                          city: 'london',               postcode_prefixes: [], phone: '02088943987', specialized: true },
  { key: 'QMC', name: 'Q Despatch Ltd',                                city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '02074249559' },
  { key: 'RCL', name: 'Radio Cars Liverpool',                          city: 'liverpool',            postcode_prefixes: [], phone: '01513213333' },
  { key: 'RCM', name: 'Radio Cars Manchester',                         city: 'manchester',           postcode_prefixes: [], phone: '01619452000' },
  { key: 'REG', name: 'Regal Cars (London)',                           city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '02072298884' },
  { key: 'REX', name: 'Rays Exec SPV',                                 city: 'london',               postcode_prefixes: [], phone: '07932604435', specialized: true },
  { key: 'RGC', name: 'Viceroy Cars  Ltd',                             city: 'banstead',             postcode_prefixes: [], phone: '01737360006' },
  { key: 'RGT', name: 'Cabco United Taxis CT',                         city: 'cambridge',            postcode_prefixes: [], phone: '' },
  { key: 'RJC', name: 'Radio J Cabs',                                  city: 'blackpool',            postcode_prefixes: [], phone: '01253293222' },
  { key: 'ROL', name: 'Royal Cars (Oxford)',                           city: 'oxford',               postcode_prefixes: [], phone: '01865778866' },
  { key: 'ROY', name: 'Royal Cars Middlesborough',                     city: 'stockton on tees',     postcode_prefixes: [], phone: '01642666666' },
  { key: 'RRR', name: 'Roadrunner',                                    city: 'horley',               postcode_prefixes: [], phone: '' },
  { key: 'RSH', name: 'Radio Taxis Southampton Ltd',                   city: 'southampton',          postcode_prefixes: [], phone: '02380666666' },
  { key: 'RTA', name: 'Rainbow Cars (Aberdeen) Ltd',                   city: 'aberdeen',             postcode_prefixes: [], phone: '01224878787' },
  { key: 'RTF', name: 'Radio Taxis Limited (Fareham)',                 city: 'fareham',              postcode_prefixes: [], phone: '01329282282' },
  { key: 'RTS', name: 'Radio Cars (Swindon)',                          city: 'swindon',              postcode_prefixes: [], phone: '01793644272' },
  { key: 'S7',  name: 'S7 Chauffeurs SPV',                             city: 'london',               postcode_prefixes: [], phone: '02074584202', specialized: true },
  { key: 'SAM', name: 'SAMS CARS',                                     city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '02072544545' },
  { key: 'SCP', name: 'Prestige Chauffeur Services SPV',               city: 'worcester',            postcode_prefixes: [], phone: '08704866823', specialized: true },
  { key: 'SCS', name: 'Southern Chauffeur Services SPV',               city: 'southampton',          postcode_prefixes: [], phone: '07771694578', specialized: true },
  { key: 'SCT', name: 'Sheffield City Taxis',                          city: 'sheffield',            postcode_prefixes: [], phone: '01142393939' },
  { key: 'SIA', name: 'Star in a Car SPV',                             city: 'manchester',           postcode_prefixes: [], phone: '08456123863', specialized: true },
  { key: 'SIM', name: 'Simpsons SPV',                                  city: 'london',               postcode_prefixes: [], phone: '02076130066', specialized: true },
  { key: 'SIN', name: 'LA Sinclair (Taxi Service)',                    city: 'shetland',             postcode_prefixes: [], phone: '01595694617' },
  { key: 'SKT', name: 'Sketch Cars SPV',                               city: 'london',               postcode_prefixes: [], phone: '07976275356', specialized: true },
  { key: 'SKY', name: 'SKYEX',                                         city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '02073845555' },
  { key: 'SLK', name: 'STREAMLINE KENT',                               city: 'kent',                 postcode_prefixes: [], phone: '01622750000' },
  { key: 'SLM', name: 'Starline Minicabs (Chichester)',                city: 'chichester',           postcode_prefixes: [], phone: '01243531666' },
  { key: 'SLV', name: 'Silverline Cars Bristlol SPV',                  city: 'bristol',              postcode_prefixes: [], phone: '01454313227', specialized: true },
  { key: 'SLX', name: 'Streamline Taxis [Leeds]',                      city: 'leeds',                postcode_prefixes: [], phone: '' },
  { key: 'SLY', name: 'Streamline York CT',                            city: 'york',                 postcode_prefixes: [], phone: '1904656565' },
  { key: 'SOV', name: 'Sovereign',                                     city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '02075316000' },
  { key: 'SPR', name: 'Network Cars Glasgow',                          city: 'glasgow',              postcode_prefixes: [], phone: '01415481110' },
  { key: 'STB', name: 'Southern Taxis Brighton',                       city: 'brighton',             postcode_prefixes: [], phone: '01273225109' },
  { key: 'TCC', name: 'The Car Company',                               city: 'birmingham',           postcode_prefixes: [], phone: '07956595253' },
  { key: 'TFS', name: '24/7 Cars Bedford CT',                          city: 'bedford',              postcode_prefixes: [], phone: '01234511247' },
  { key: 'TIG', name: 'Tiger Taxis',                                   city: 'wycombe high',         postcode_prefixes: [], phone: '01494461111' },
  { key: 'TRA', name: 'Travelstar UK - CT SPV',                        city: 'wiltshire',            postcode_prefixes: [], phone: '01380726664', specialized: true },
  { key: 'TRU', name: 'Trusted Cars',                                  city: 'buckingham',           postcode_prefixes: [], phone: '01280848206' },
  { key: 'TVH', name: 'TravelHire',                                    city: 'london',               postcode_prefixes: LONDON_POSTCODE_PREFIXES, phone: '02085600008' },
  { key: 'UCL', name: '24x7 Taxis (Stratford upon Avon)',              city: 'stratford upon avon',  postcode_prefixes: [], phone: '01789444444' },
  { key: 'VBS', name: 'V Cars Bristol CT',                             city: 'bristol',              postcode_prefixes: [], phone: '01179252626' },
  { key: 'VBT', name: 'V Cars (Bath) CT',                              city: 'bath',                 postcode_prefixes: [], phone: '01225464646' },
  { key: 'VCB', name: 'Value Cabs Ltd',                                city: 'belfast',              postcode_prefixes: [], phone: '02890809080' },
  { key: 'VCC', name: 'V Cars (Swindon) CT',                           city: 'swindon',              postcode_prefixes: [], phone: '01793701701' },
  { key: 'VHT', name: 'Victor Assoc Ltd T/A Lightning Car Hire SPV',   city: 'sevenoaks',            postcode_prefixes: [], phone: '',            specialized: true },
  { key: 'VLB', name: 'Virgin Limobike Ltd SPV (Motorbike Taxi)',      city: 'london',               postcode_prefixes: [], phone: '02031764441', specialized: true },
  { key: 'VPS', name: 'VipSec Executive Chauffeur Services CT SPV',    city: 'belfast',              postcode_prefixes: [], phone: '02895439356', specialized: true },
  { key: 'WAP', name: 'Wrexham And Prestige',                          city: 'wrexham',              postcode_prefixes: [], phone: '01978290034' },
  { key: 'WCD', name: 'Worldwide Chauffeur Drive',                     city: 'london',               postcode_prefixes: [], phone: '' },
  { key: 'WFC', name: 'Wakefield Cars CT',                             city: 'wakefield',            postcode_prefixes: [], phone: '01924380000' },
  { key: 'WIN', name: 'Windsor Cars',                                  city: 'berkshire',            postcode_prefixes: [], phone: '01753677677' },
  { key: 'WOC', name: 'Wooburn Cars',                                  city: 'wycombe high',         postcode_prefixes: [], phone: '01628531144' },
  { key: 'WRI', name: 'Wright Taxis',                                  city: 'dumbarton',            postcode_prefixes: [], phone: '01389761111' },
  { key: 'WRT', name: 'Streamline Warrens Taxis Bournemouth',          city: 'bournemouth',          postcode_prefixes: [], phone: '01202555511' },
  { key: 'WTC', name: 'Westside Taxis (Crew',                          city: 'crewe',                postcode_prefixes: [], phone: '01270211222' },
  { key: 'WTT', name: 'Western Taxis',                                 city: 'derby',                postcode_prefixes: [], phone: '01332331331' },
  { key: 'XDT', name: 'Xpert Taxis Ltd (2208) CT',                     city: 'dublin',               postcode_prefixes: [], phone: '0035316670777' },
  { key: 'qbt', name: 'Benchmark Exec Newca CT',                       city: 'newcastle upon tyne',  postcode_prefixes: [], phone: '' }
])

vehicle_vendors_vehicles_mapping = {
  '1AB' => ['MPV_Standard', 'Saloon_Standard'],
  '57T' => ['MPV_Standard', 'Saloon_Standard'],
  'A2T' => ['MPV_Standard', 'Saloon_Standard'],
  'ABC' => ['MPV_Standard', 'Saloon_Standard'],
  'ABM' => ['Saloon_Standard'],
  'AC3' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'ACG' => ['MPV_Standard', 'Saloon_Standard'],
  'ACL' => ['MPV_Standard', 'Saloon_Standard'],
  'ACT' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'ACW' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'AEB' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard', 'Taxi_Standard'],
  'AJS' => ['Saloon_Corporate'],
  'APC' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'ARC' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'ASS' => ['MPV_Standard', 'Saloon_Standard'],
  'ATA' => ['Saloon_Standard'],
  'ATS' => ['MPV_Standard', 'Saloon_Standard'],
  'BCR' => ['Saloon_Standard'],
  'BEI' => ['MPV_Standard', 'Saloon_Standard'],
  'BHS' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard', 'Taxi_Standard'],
  'BLB' => ['MPV_Standard', 'Saloon_Standard'],
  'BLM' => ['MPV_Standard', 'Saloon_Standard'],
  'BLT' => ['Saloon_Standard'],
  'BLU' => ['MPV_Standard', 'Saloon_Standard'],
  'BR1' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'BRT' => ['MPV_Standard', 'Saloon_Standard'],
  'BTX' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'CAM' => ['Saloon_Corporate'],
  'CAP' => ['MPV_Standard', 'Saloon_Corporate'],
  'CAR' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'CBB' => ['Saloon_Standard'],
  'CC1' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'CCA' => ['MPV_Standard', 'Saloon_Standard'],
  'CCC' => ['MPV_Standard', 'Saloon_Standard'],
  'CCL' => ['MPV_Standard', 'Saloon_Standard'],
  'CCS' => ['MPV_Standard', 'Saloon_Standard'],
  'CED' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'CGS' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'CGT' => ['MPV_Standard', 'Saloon_Standard', 'Taxi_Standard'],
  'CHM' => ['MPV_Standard', 'Saloon_Standard'],
  'CIT' => ['Saloon_Standard'],
  'CLS' => ['MPV_Standard', 'Saloon_Standard'],
  'CLT' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'CML' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'COL' => ['Saloon_Standard'],
  'COT' => ['MPV_Standard', 'Saloon_Standard'],
  'CRF' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'CRO' => ['MPV_Standard', 'Saloon_Standard'],
  'CSA' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'CST' => ['MPV_Standard', 'Saloon_Standard'],
  'CTB' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard', 'Taxi_Standard'],
  'CTN' => ['MPV_Standard', 'Saloon_Standard'],
  'CTT' => ['Saloon_Standard'],
  'DAB' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'DAX' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'DCD' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'DEE' => ['Saloon_Corporate'],
  'DGT' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'DRG' => ['MPV_Standard', 'Saloon_Standard'],
  'DTG' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard', 'Taxi_Standard'],
  'DUR' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard', 'Taxi_Standard'],
  'ECB' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard', 'Taxi_Standard'],
  'ECL' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'ECS' => ['MPV_Standard', 'Saloon_Standard'],
  'EEZ' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'EMT' => ['Saloon_Standard'],
  'EXE' => ['Saloon_Standard'],
  'EXM' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'FAK' => ['MPV_Standard', 'Saloon_Standard'],
  'FCB' => ['MPV_Standard', 'Saloon_Standard'],
  'FLC' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard', 'Taxi_Standard'],
  'FLE' => ['MPV_Standard', 'Saloon_Standard'],
  'FOL' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'FOT' => ['Saloon_Standard'],
  'FTX' => ['MPV_Standard'],
  'FYL' => ['MPV_Standard', 'Saloon_Standard'],
  # 'GBH' => ['Taxi_Standard'],
  # 'GED' => ['Taxi_Standard'],
  # 'GGG' => ['Taxi_Standard'],
  'GGT' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'GLH' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'GMC' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard', 'Taxi_Standard'],
  # 'GMR' => ['Taxi_Standard'],
  'GOL' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard', 'Taxi_Standard'],
  'GRE' => ['MPV_Standard', 'Saloon_Standard'],
  'GTC' => ['MPV_Standard', 'Saloon_Standard'],
  'GTR' => ['MPV_Standard', 'Saloon_Standard'],
  # 'GTZ' => ['Saloon_Standard', 'Taxi_Standard'],
  'GWT' => ['MPV_Standard', 'Taxi_Standard'],
  'HAR' => ['MPV_Standard', 'Saloon_Standard'],
  'HCS' => ['MPV_Standard', 'Saloon_Standard'],
  'HEM' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'HIT' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard', 'Taxi_Standard'],
  'HOT' => ['Saloon_Standard'],
  'INT' => ['MPV_Standard', 'Saloon_Standard'],
  'IRD' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'ITL' => ['MPV_Standard', 'Saloon_Standard'],
  'IVT' => ['MPV_Standard', 'Saloon_Standard', 'Taxi_Standard'],
  'JLS' => ['Saloon_Corporate', 'Saloon_Standard'],
  'JUT' => ['Saloon_Standard'],
  'KEN' => ['MPV_Standard', 'Saloon_Standard'],
  'LFC' => ['MPV_Standard', 'Saloon_Standard'],
  'LOC' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'LPH' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'LX ' => ['MPV_Standard', 'Saloon_Standard', 'Taxi_Standard'],
  'MC ' => ['MPV_Standard', 'Saloon_Standard'],
  'MCA' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'MCR' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard', 'Taxi_Standard'],
  'MFC' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'MPS' => ['MPV_Standard', 'Saloon_Standard'],
  'MSL' => ['MPV_Standard', 'Saloon_Standard'],
  'MTC' => ['Saloon_Standard'],
  'MTL' => ['MPV_Standard', 'Saloon_Standard', 'Taxi_Standard'],
  'MTX' => ['MPV_Standard', 'Taxi_Standard'],
  'N&B' => ['Saloon_Standard'],
  'NAC' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'NEW' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'NML' => ['MPV_Standard', 'Saloon_Standard'],
  'NOD' => ['MPV_Standard', 'Saloon_Standard'],
  'OYS' => ['MPV_Standard', 'Saloon_Standard'],
  'PAR' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'PCD' => ['MPV_Standard', 'Saloon_Standard'],
  'PDK' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'PRC' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'PRE' => ['MPV_Standard', 'Saloon_Standard'],
  'PRT' => ['MPV_Standard', 'Saloon_Standard'],
  'PTC' => ['MPV_Standard', 'Saloon_Standard'],
  'QEC' => ['Saloon_Corporate'],
  'QMC' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'RCL' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard', 'Taxi_Standard'],
  'RCM' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'REG' => ['MPV_Standard', 'Saloon_Standard'],
  'REX' => ['Saloon_Standard'],
  'RGC' => ['Saloon_Standard'],
  'RGT' => ['MPV_Standard', 'Saloon_Standard'],
  'RJC' => ['MPV_Standard', 'Saloon_Standard'],
  'ROL' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard', 'Taxi_Standard'],
  'ROY' => ['Saloon_Standard', 'Taxi_Standard'],
  'RRR' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'RSH' => ['MPV_Standard', 'Saloon_Standard'],
  'RTA' => ['MPV_Standard', 'Saloon_Standard'],
  'RTF' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'RTS' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'S7' => ['Saloon_Corporate'],
  'SAM' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'SCS' => ['Saloon_Standard'],
  'SCT' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard', 'Taxi_Standard'],
  'SIA' => ['Saloon_Corporate', 'Saloon_Standard'],
  'SIM' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'SIN' => ['Saloon_Standard'],
  'SKT' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'SKY' => ['MPV_Standard', 'Saloon_Standard'],
  'SLK' => ['MPV_Standard', 'Saloon_Standard'],
  'SLM' => ['Saloon_Standard'],
  'SLV' => ['MPV_Standard', 'Saloon_Standard'],
  'SLX' => ['MPV_Standard', 'Saloon_Standard'],
  'SLY' => ['MPV_Standard', 'Saloon_Standard'],
  'SOV' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'SPR' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'STB' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'TCC' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  # 'TEG' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard', 'Taxi_Standard'],
  'TFS' => ['MPV_Standard', 'Saloon_Standard'],
  'TIG' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'TRA' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'TRU' => ['MPV_Standard', 'Saloon_Standard'],
  'TVH' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'UCL' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard', 'Taxi_Standard'],
  'VBS' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'VBT' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'VCB' => ['MPV_Standard', 'Saloon_Standard'],
  'VCC' => ['MPV_Standard', 'Saloon_Standard'],
  'VHT' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'VLB' => ['Saloon_Standard'],
  'WAP' => ['MPV_Standard', 'Saloon_Standard'],
  'WCD' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'WFC' => ['MPV_Standard', 'Saloon_Standard'],
  'WIN' => ['MPV_Standard', 'Saloon_Standard'],
  'WOC' => ['MPV_Standard', 'Saloon_Standard'],
  'WRI' => ['MPV_Standard', 'Saloon_Standard'],
  'WRT' => ['Saloon_Standard', 'Taxi_Standard'],
  'WTC' => ['MPV_Standard', 'Saloon_Standard'],
  'WTT' => ['Saloon_Corporate', 'Saloon_Standard'],
  'XDT' => ['MPV_Standard', 'Saloon_Corporate', 'Saloon_Standard'],
  'qbt' => ['Saloon_Corporate']
}

ot_values = %w'Saloon_Standard MPV_Standard Saloon_Corporate Taxi_Standard MPV_Standard_Black'
vehicle_ids = DB[:vehicles].where(value: ot_values).select_hash(:value, :id)

vehicle_vendor_ids = DB[:vehicle_vendors].select_hash(:key, :id)

vehicle_vendors_vehicles_mapping.each do |vendor_key, vehicle_keys|
  vendor_id = vehicle_vendor_ids[vendor_key]

  next if vendor_id.blank?

  Seeds.seed_once(DB[:vehicle_vendors_vehicles], :vehicle_id, :vehicle_vendor_id,
    vehicle_keys.map{ |key| {vehicle_id: vehicle_ids[key], vehicle_vendor_id: vendor_id} }
  )
end
