#!groovy
pipeline {
  options {
    disableConcurrentBuilds()
    buildDiscarder(logRotator(numToKeepStr: '10'))
  }
  agent {
    node {
      label 'buildfarm'
    }
  }
  tools {
    nodejs 'NodeJs'
  }
  environment {
    DEV_TOKEN_SECRET = credentials('AWS_DEV_ACCESS_SECRET')
    DEV_MIXPANEL_KEY = credentials('DEV_MIXPANEL_KEY')

    PROD_MIXPANEL_KEY = credentials('PROD_MIXPANEL_KEY')
    PROD_UHC_TOKEN_SECRET = credentials('PROD_UHC_AWS_ACCESS_SECRET')
    PROD_ANT_TOKEN_SECRET = credentials('PROD_ANT_AWS_ACCESS_SECRET')

    AUTH0_UHC_CLIENT_ID = '4NsWAoo6Gxd9KPKBvokzgJf2HEhZs3o5'
    AUTH0_UHC_DOMAIN = 'login-uhc.benrevo.com'
    AUTH0_UHC_DOMAIN_LOGIN = 'https://login.auth0.com/api/v2'

    AUTH0_ANT_CLIENT_ID = 'FgY2ws560TOUTaVQaGeC2vzZa61UAzBG'
    AUTH0_ANT_DOMAIN = 'login-anthem.benrevo.com'
    AUTH0_ANT_DOMAIN_LOGIN = 'https://login.auth0.com/api/v2'

    DEV_UHC_BENREVO_API_PATH = 'https://dev-api-dashboards-uhc.benrevo.com'
    DEV_ANT_BENREVO_API_PATH = 'https://dev-api-dashboards-anthem.benrevo.com'

    STAGE_UHC_BENREVO_API_PATH = 'https://stage-api-dashboards-uhc.benrevo.com'
    STAGE_ANT_BENREVO_API_PATH = 'https://stage-api-dashboards-anthem.benrevo.com'

    PROD_UHC_BENREVO_API_PATH = 'https://api-dashboards-uhc.benrevo.com'
    PROD_ANT_BENREVO_API_PATH = 'https://api-dashboards-anthem.benrevo.com'

    DEV_TOKEN_ID = 'AKIAIEV2Q2CEUNPABDKA'
    PROD_UHC_TOKEN_ID = 'AKIAJMGGUG3HSUXCOGBA'
    PROD_ANT_TOKEN_ID = 'AKIAILFFQT66VOH6U4YA'

    COVERALLS_REPO_TOKEN = credentials('DASHBOARD_SITE_COVERALLS_REPO_TOKEN')
    COVERALLS_SERVICE_NAME = 'Jenkins'

    NPM_TOKEN = credentials('NPM_TOKEN')
    NODE_OPTIONS = "--max-old-space-size=2048"
  }
  stages {
    stage('Setup') {
      parallel {
        stage('UHC') {
          steps {
            ws("${BUILD_TAG}uhc") {
              wrap([$class: 'BuildUser']) {
                slackSend message: "Starting build: ${env.JOB_NAME} ${env.BUILD_DISPLAY_NAME} caused by ${env.BUILD_USER_ID}."
              }
              checkout(
                [
                  $class: 'GitSCM',
                  branches: [[name: '${BRANCH_NAME}']],
                  doGenerateSubmoduleConfigurations: false,
                  extensions: [],
                  submoduleCfg: [],
                  userRemoteConfigs: [[
                    credentialsId: '81e0269c-8b0b-4eeb-97f2-03da4cb75100',
                    url: 'https://github.com/BenRevo/benrevo-dashborad-site.git'
                  ]]
                ]
              )
              sh '''
npm install
              '''
            }
          }
        }
        stage('Anthem') {
          steps {
            ws("${BUILD_TAG}ant") {
              wrap([$class: 'BuildUser']) {
                slackSend message: "Starting build: ${env.JOB_NAME} ${env.BUILD_DISPLAY_NAME} caused by ${env.BUILD_USER_ID}."
              }
              checkout(
                [
                  $class: 'GitSCM',
                  branches: [[name: '${BRANCH_NAME}']],
                  doGenerateSubmoduleConfigurations: false,
                  extensions: [],
                  submoduleCfg: [],
                  userRemoteConfigs: [[
                    credentialsId: '81e0269c-8b0b-4eeb-97f2-03da4cb75100',
                    url: 'https://github.com/BenRevo/benrevo-dashborad-site.git'
                  ]]
                ]
              )
              sh '''
npm install
              '''
            }
          }
        }
      }
    }
    stage('Test') {
      parallel {
        stage('UHC') {
          steps {
            ws("${BUILD_TAG}uhc") {
              sh '''
export CARRIER="UHC"
npm test
              '''
            }
          }
        }
        stage('Anthem') {
          steps {
            ws("${BUILD_TAG}ant") {
              sh '''
export CARRIER="ANTHEM"
npm test
              '''
            }
          }
        }
      }
    }
    stage('Build') {
      parallel {
        stage('UHC') {
          steps {
            ws("${BUILD_TAG}uhc") {
              sh '''
#!/bin/bash -xe

export CARRIER="UHC"
export BENREVO_PATH="/uhc/"
export AUTH0_CLIENT_ID=$AUTH0_UHC_CLIENT_ID
export AUTH0_DOMAIN=$AUTH0_UHC_DOMAIN
export AUTH0_DOMAIN_LOGIN=$AUTH0_UHC_DOMAIN_LOGIN
export CARRIER_PLACEHOLDER="uhc"

if [ "${GIT_BRANCH}" = "develop" ]
then
    export MIXPANEL_KEY=$DEV_MIXPANEL_KEY
    export BENREVO_API_PATH=$DEV_UHC_BENREVO_API_PATH
fi

if [ "${GIT_BRANCH}" = "stage" ]
then
    export MIXPANEL_KEY=$DEV_MIXPANEL_KEY
    export BENREVO_API_PATH=$STAGE_UHC_BENREVO_API_PATH
fi

if [ "${GIT_BRANCH}" = "master" ]
then
    export MIXPANEL_KEY=$PROD_MIXPANEL_KEY
    export BENREVO_API_PATH=$PROD_UHC_BENREVO_API_PATH
fi

export PATH=$PATH:$HOME/.local/bin
npm run build
              '''
            }
          }
        }
        stage('Anthem') {
          steps {
            ws("${BUILD_TAG}ant") {
              sh '''
#!/bin/bash -xe

export CARRIER="ANTHEM"
export BENREVO_PATH="/anthem/"
export AUTH0_CLIENT_ID=$AUTH0_ANT_CLIENT_ID
export AUTH0_DOMAIN=$AUTH0_ANT_DOMAIN
export AUTH0_DOMAIN_LOGIN=$AUTH0_ANT_DOMAIN_LOGIN
export CARRIER_PLACEHOLDER="anthem"

if [ "${GIT_BRANCH}" = "develop" ]
then
    export MIXPANEL_KEY=$DEV_MIXPANEL_KEY
    export BENREVO_API_PATH=$DEV_ANT_BENREVO_API_PATH
fi

if [ "${GIT_BRANCH}" = "stage" ]
then
    export MIXPANEL_KEY=$DEV_MIXPANEL_KEY
    export BENREVO_API_PATH=$STAGE_ANT_BENREVO_API_PATH
fi

if [ "${GIT_BRANCH}" = "master" ]
then
    export MIXPANEL_KEY=$PROD_MIXPANEL_KEY
    export BENREVO_API_PATH=$PROD_ANT_BENREVO_API_PATH
fi

export PATH=$PATH:$HOME/.local/bin
npm run build
              '''
            }
          }
        }
      }
    }
    stage('Dockerize') {
      parallel {
        stage('UHC') {
          steps {
            ws("${BUILD_TAG}uhc") {
              sh '''
#!/bin/bash -xe

export CARRIER="UHC"
export CARRIER_PLACEHOLDER="uhc"
export BENREVO_PATH="/uhc/"

if [ "${GIT_BRANCH}" = "develop" ]
then
    export DOCKER_BUILD_NAME="fe-dashboard-uhc"
    export DOCKER_TAG_NAME="434704177489.dkr.ecr.us-east-1.amazonaws.com/fe-dashboard-uhc:latest"
    export AWS_REGION_NAME="us-east-1"
    export AWS_DEPLOY_NAME="fe-dashboard-uhc"
    export AWS_ACCESS_KEY_ID=$DEV_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$DEV_TOKEN_SECRET
    export DEPLOY_FILE_PATH="dev"
    export NPM_TOKEN=$NPM_TOKEN
fi

if [ "${GIT_BRANCH}" = "stage" ]
then
    export DOCKER_BUILD_NAME="fe-dashboard-uhc-stage"
    export DOCKER_TAG_NAME="434704177489.dkr.ecr.us-east-1.amazonaws.com/fe-dashboard-uhc-stage:latest"
    export AWS_REGION_NAME="us-east-1"
    export AWS_DEPLOY_NAME="fe-dashboard-uhc-stage"
    export AWS_ACCESS_KEY_ID=$DEV_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$DEV_TOKEN_SECRET
    export DEPLOY_FILE_PATH="stage"
    export NPM_TOKEN=$NPM_TOKEN
fi

if [ "${GIT_BRANCH}" = "master" ]
then
    export DOCKER_BUILD_NAME="fe-dashboard-uhc"
    export DOCKER_TAG_NAME="252508284068.dkr.ecr.us-west-2.amazonaws.com/prd-br-uhc-dashboard:latest"
    export AWS_REGION_NAME="us-west-2"
    export AWS_DEPLOY_NAME="fe-dashboard-uhc"
    export AWS_ACCESS_KEY_ID=$PROD_UHC_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$PROD_UHC_TOKEN_SECRET
    export DEPLOY_FILE_PATH="prod"
    export NPM_TOKEN=$NPM_TOKEN
fi

export PATH=$PATH:$HOME/.local/bin

if [ "$(aws sts get-caller-identity | grep -c 'UserId')" -eq 1 ]
then
    echo "##### Successful authorization from AWS"
fi

mkdir -p ./.elasticbeanstalk/
mkdir -p ./.ebextensions/

cp ./internals/deploy/01_nginx.config ./.ebextensions/01_nginx.config
cp ./internals/deploy/$CARRIER_PLACEHOLDER/$DEPLOY_FILE_PATH/config.yml ./.elasticbeanstalk/config.yml
cp ./internals/deploy/$CARRIER_PLACEHOLDER/$DEPLOY_FILE_PATH/Dockerrun.aws.json ./Dockerrun.aws.json

docker build -t $DOCKER_BUILD_NAME --build-arg NPM_TOKEN=$NPM_TOKEN .

docker tag $DOCKER_BUILD_NAME:latest $DOCKER_TAG_NAME
eval $(aws ecr get-login --no-include-email --region "${AWS_REGION_NAME}")
docker push $DOCKER_TAG_NAME
              '''
            }
          }
        }
        stage('Anthem') {
          steps {
            ws("${BUILD_TAG}ant") {
              sh '''
#!/bin/bash -xe

export CARRIER="ANTHEM"
export CARRIER_PLACEHOLDER="anthem"
export BENREVO_PATH="/anthem/"

if [ "${GIT_BRANCH}" = "develop" ]
then
    export DOCKER_BUILD_NAME="fe-dashboard-anthem"
    export DOCKER_TAG_NAME="434704177489.dkr.ecr.us-east-1.amazonaws.com/fe-dashboard-anthem:latest"
    export AWS_REGION_NAME="us-east-1"
    export AWS_DEPLOY_NAME="fe-dashboard-anthem"
    export AWS_ACCESS_KEY_ID=$DEV_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$DEV_TOKEN_SECRET
    export DEPLOY_FILE_PATH="dev"
    export NPM_TOKEN=$NPM_TOKEN
fi

if [ "${GIT_BRANCH}" = "stage" ]
then
    export DOCKER_BUILD_NAME="fe-dashboard-anthem-stage"
    export DOCKER_TAG_NAME="434704177489.dkr.ecr.us-east-1.amazonaws.com/fe-dashboard-anthem-stage:latest"
    export AWS_REGION_NAME="us-east-1"
    export AWS_DEPLOY_NAME="fe-dashboard-anthem-stage"
    export AWS_ACCESS_KEY_ID=$DEV_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$DEV_TOKEN_SECRET
    export DEPLOY_FILE_PATH="stage"
    export NPM_TOKEN=$NPM_TOKEN
fi

if [ "${GIT_BRANCH}" = "master" ]
then
    export DOCKER_BUILD_NAME="fe-anthem-dashboard"
    export DOCKER_TAG_NAME="218450561239.dkr.ecr.us-west-2.amazonaws.com/prod-br-anthem-dashboard:latest"
    export AWS_REGION_NAME="us-west-2"
    export AWS_DEPLOY_NAME="fe-anthem-dashboard"
    export AWS_ACCESS_KEY_ID=$PROD_ANT_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$PROD_ANT_TOKEN_SECRET
    export DEPLOY_FILE_PATH="prod"
    export NPM_TOKEN=$NPM_TOKEN
fi

export PATH=$PATH:$HOME/.local/bin

if [ "$(aws sts get-caller-identity | grep -c 'UserId')" -eq 1 ]
then
    echo "##### Successful authorization from AWS"
fi

mkdir -p ./.elasticbeanstalk/
mkdir -p ./.ebextensions/

cp ./internals/deploy/01_nginx.config ./.ebextensions/01_nginx.config
cp ./internals/deploy/$CARRIER_PLACEHOLDER/$DEPLOY_FILE_PATH/config.yml ./.elasticbeanstalk/config.yml
cp ./internals/deploy/$CARRIER_PLACEHOLDER/$DEPLOY_FILE_PATH/Dockerrun.aws.json ./Dockerrun.aws.json

docker build -t $DOCKER_BUILD_NAME --build-arg NPM_TOKEN=$NPM_TOKEN .

docker tag $DOCKER_BUILD_NAME:latest $DOCKER_TAG_NAME
eval $(aws ecr get-login --no-include-email --region "${AWS_REGION_NAME}")
docker push $DOCKER_TAG_NAME
              '''
            }
          }
        }
      }
    }
    stage('Deploy') {
      parallel {
        stage('UHC') {
          steps {
            ws("${BUILD_TAG}uhc") {
              sh '''
#!/bin/bash -xe

export CARRIER="UHC"
export CARRIER_PLACEHOLDER="uhc"

if [ "${GIT_BRANCH}" = "develop" ]
then
    export AWS_REGION_NAME="us-east-1"
    export AWS_DEPLOY_NAME="fe-dashboard-uhc"
    export AWS_ACCESS_KEY_ID=$DEV_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$DEV_TOKEN_SECRET
fi

if [ "${GIT_BRANCH}" = "stage" ]
then
    export AWS_REGION_NAME="us-east-1"
    export AWS_DEPLOY_NAME="fe-dashboard-uhc-stage"
    export AWS_ACCESS_KEY_ID=$DEV_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$DEV_TOKEN_SECRET
fi

if [ "${GIT_BRANCH}" = "master" ]
then
    export AWS_REGION_NAME="us-west-2"
    export AWS_DEPLOY_NAME="fe-dashboard-uhc"
    export AWS_ACCESS_KEY_ID=$PROD_UHC_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$PROD_UHC_TOKEN_SECRET
fi

if [ "$(aws sts get-caller-identity | grep -c 'UserId')" -eq 1 ]
then
    echo "##### Successful authorization from AWS"
fi

eb deploy $AWS_DEPLOY_NAME --label "$BUILD_TAG:$CARRIER_PLACEHOLDER" --verbose --staged
              '''
            }
          }
        }
        stage('Anthem') {
          steps {
            ws("${BUILD_TAG}ant") {
              sh '''
#!/bin/bash -xe

export CARRIER="ANTHEM"
export CARRIER_PLACEHOLDER="anthem"

if [ "${GIT_BRANCH}" = "develop" ]
then
    export AWS_REGION_NAME="us-east-1"
    export AWS_DEPLOY_NAME="fe-dashboard-anthem"
    export AWS_ACCESS_KEY_ID=$DEV_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$DEV_TOKEN_SECRET
fi

if [ "${GIT_BRANCH}" = "stage" ]
then
    export AWS_REGION_NAME="us-east-1"
    export AWS_DEPLOY_NAME="fe-dashboard-anthem-stage"
    export AWS_ACCESS_KEY_ID=$DEV_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$DEV_TOKEN_SECRET
fi

if [ "${GIT_BRANCH}" = "master" ]
then
    export AWS_REGION_NAME="us-west-2"
    export AWS_DEPLOY_NAME="fe-anthem-dashboard"
    export AWS_ACCESS_KEY_ID=$PROD_ANT_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$PROD_ANT_TOKEN_SECRET
fi

if [ "$(aws sts get-caller-identity | grep -c 'UserId')" -eq 1 ]
then
    echo "##### Successful authorization from AWS"
fi

if [ "${GIT_BRANCH}" = "develop" ]
then
    eb deploy $AWS_DEPLOY_NAME --label "$BUILD_TAG:$CARRIER_PLACEHOLDER" --verbose --staged
fi
              '''
            }
          }
        }
      }
    }
  }
  post {
    failure {
      wrap([$class: 'BuildUser']) {
        slackSend color: "danger", message: "Build failed: ${JOB_NAME} ${BUILD_DISPLAY_NAME} caused by ${env.CHANGE_AUTHOR}. Build results: ${RUN_DISPLAY_URL}"
        emailext body: '${JOB_NAME} ${BUILD_DISPLAY_NAME} - failed: Check console output at ${RUN_DISPLAY_URL} to view the results.', recipientProviders: [[$class: 'CulpritsRecipientProvider']], subject: 'Build failed: ${JOB_NAME} ${BUILD_DISPLAY_NAME}'
      }
    }
    success {
      wrap([$class: 'BuildUser']) {
        slackSend color: "good", message: "Build success: ${JOB_NAME} ${BUILD_DISPLAY_NAME} caused by ${env.CHANGE_AUTHOR}. Build results: ${RUN_DISPLAY_URL}"
        emailext body: '${JOB_NAME} ${BUILD_DISPLAY_NAME} - success: Check console output at ${RUN_DISPLAY_URL} to view the results.', recipientProviders: [[$class: 'CulpritsRecipientProvider']], subject: 'Build success: ${JOB_NAME} ${BUILD_DISPLAY_NAME}'
      }
    }
  }
}
