export const LOAD_CARRIERS = 'app/Home/LOAD_CARRIERS';
export const LOAD_CARRIERS_SUCCESS = 'app/Home/LOAD_CARRIERS_SUCCESS';
export const LOAD_CARRIERS_ERROR = 'app/Home/LOAD_CARRIERS_ERROR';

export const LOAD_BROKERS = 'app/Home/LOAD_BROKERS';
export const LOAD_BROKERS_SUCCESS = 'app/Home/LOAD_BROKERS_SUCCESS';
export const LOAD_BROKERS_ERROR = 'app/Home/LOAD_BROKERS_ERROR';

export const LOAD_CLIENTS = 'app/Home/LOAD_CLIENTS';
export const LOAD_CLIENTS_SUCCESS = 'app/Home/LOAD_CLIENTS_SUCCESS';
export const LOAD_CLIENTS_ERROR = 'app/Home/LOAD_CLIENTS_ERROR';

export const CHANGE_CARRIERS = 'app/Home/CHANGE_CARRIERS';
export const CHANGE_BROKERS = 'app/Home/CHANGE_BROKERS';
export const CHANGE_CLIENTS = 'app/Home/CHANGE_CLIENTS';
export const CHANGE_CURRENT_BROKER = 'app/Home/CHANGE_CURRENT_BROKER';
export const CHANGE_CURRENT_MEMBERS = 'app/Home/CHANGE_CURRENT_MEMBERS';

export const SET_ROUTE_ERROR = 'app/Home/SET_ROUTE_ERROR';
export const UPDATE_CLIENT = 'app/Home/UPDATE_CLIENT';

export const GET_CLIENTS_BY_NAME = 'app/Home/GET_CLIENTS_BY_NAME';
export const UPDATE_CLIENT_NAME_SEARCH_TEXT = 'app/Home/UPDATE_CLIENT_NAME_SEARCH_TEXT';
