ha_article_like_add:
    path:  /{id}/like
    defaults:
      _controller: AppBundle:Api\Like:add
      entity: 'AppBundle\Entity\Social\Article'
      key: 'token'
    methods:  [POST]

ha_article_like_remove:
    path:  /{id}/like
    defaults:
      _controller: AppBundle:Api\Like:remove
      entity: 'AppBundle\Entity\Social\Article'
      key: 'token'
    methods:  [DELETE]
