export const FETCH_TIMELINE = 'FETCH_TIMELINE';
export const FETCH_TIMELINE_SUCCEEDED = 'FETCH_TIMELINE_SUCCEEDED';
export const FETCH_TIMELINE_FAILED = 'FETCH_TIMELINE_FAILED';

export const INIT_TIMELINE = 'INIT_TIMELINE';
export const INIT_TIMELINE_SUCCEEDED = 'INIT_TIMELINE_SUCCEEDED';
export const INIT_TIMELINE_FAILED = 'INIT_TIMELINE_FAILED';

export const UPDATE_PROJECT_TIME = 'UPDATE_PROJECT_TIME';
export const UPDATE_PROJECT_TIME_SUCCEEDED = 'UPDATE_PROJECT_TIME_SUCCEEDED';
export const UPDATE_PROJECT_TIME_FAILED = 'UPDATE_PROJECT_TIME_FAILED';

export const UPDATE_COMPLETED = 'UPDATE_COMPLETED';
export const UPDATE_COMPLETED_SUCCEEDED = 'UPDATE_COMPLETED_SUCCEEDED';
export const UPDATE_COMPLETED_FAILED = 'UPDATE_COMPLETED_FAILED';

export const TIMELINE_COMPLETE = 'TIMELINE_COMPLETE';
export const TIMELINE_CLEAR = 'TIMELINE_CLEAR';

export const COMPLETED = 'Completed';
export const IN_PROGRESS = 'In progress';
export const PROJECT_TIME = 'projectedTime';
