AllCops:
  TargetRubyVersion: 2.4

  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'spec/**/*'
    - 'config/initializers/*'
    - 'config/routes.rb'
    - 'bin/*'
    - 'vendor/**/*'
    - 'ui/**/*'
Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/ClassLength:
  CountComments: false
  Max: 300

Metrics/LineLength:
  Max: 120
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https

Style/ClassAndModuleChildren:
  Enabled: false

Rails/Validation:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/MethodLength:
  Max: 30
  Exclude:
    - db/migrate/*

Lint/HandleExceptions:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/SpaceInsideBrackets:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
