source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.1.4'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.7'
gem 'bcrypt', '~> 3.1.7'
gem 'rack-cors'
gem 'performify', '~> 0.5.0'
gem 'pundit'
gem 'jwt'
gem 'parascope'
gem 'sidekiq'
gem 'sidekiq-cron'
gem 'rollbar'
gem 'rolify'
gem 'kaminari-activerecord'
gem 'pg_search'
gem 'bullet'
gem 'wkhtmltopdf-binary'
gem 'wicked_pdf'
gem 'rubyzip'
gem 'carrierwave'
gem 'rmagick'
gem 'avatarly'
gem 'paper_trail'
gem 'leaderboard'

gem 'rest-client'
gem 'config'
gem 'dotenv-rails'

gem 'newrelic_rpm'

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'mailcatcher'
  gem 'capistrano', '~> 3.6'
  gem 'capistrano-rails', '~> 1.3'
  gem 'capistrano-sidekiq'
  gem 'capistrano3-puma'
  gem 'annotate'
  gem 'rails-erd'
end

group :test do
  gem 'fakeredis', require: 'fakeredis/rspec'
  gem 'timecop'
end

group :development, :test do
  gem 'pry-rails'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'rspec-rails', '~> 3.5'
  gem 'factory_bot_rails'
  gem 'database_cleaner'
  gem 'rswag'
  gem 'rubocop', require: false
  gem 'ffaker'
  gem 'vcr'
  gem 'webmock'
end

group :production do
  gem 'tzinfo-data'
  gem 'fog-aws'
end
