import React from 'react';
import PropTypes from 'prop-types';
import { Grid, Segment, Header, Image } from 'semantic-ui-react';
import Helmet from 'react-helmet';
import { Link } from 'react-router';
import Benrevo from '../../assets/img/svg/benrevo.svg';

class Terms extends React.Component { // eslint-disable-line react/prefer-stateless-function
  static propTypes = {};

  render() {
    return (
      <div>
        <Helmet
          title="Terms of Use"
          meta={[
            { name: 'description', content: 'Description of Terms of Use' },
          ]}
        />
        <Grid stackable container className="terms section-wrap">
          <Grid.Column width={16}>
            <Grid stackable as={Segment} className="gridSegment">
              <Grid.Row>
                <Grid.Column width={16} textAlign="center" >
                  <Header as="h1" className="rfpPageHeading">Terms of Use</Header>
                </Grid.Column>
              </Grid.Row>
              <Grid.Row>
                <Grid.Column width={16}>
                  <div>
                    <h5 className="terms-effective">Effective Date: August 17</h5>
                    <h5>Last Updated Date: August 21, 2017</h5>
                    <p>Please read this Terms of Use Agreement (the <b>“Terms of Use”</b>) carefully.  These Terms of Use govern your use ofthe website(s) that link to these Terms of Use (each a <b>“Site”</b> and collectively, the <b>“Sites”</b>), and hosted services enabled or available via the Site (the <b>“Services”</b>) that are offered by BenRevo, Inc. (the <b>“Company”</b> or <b>“we”</b>). </p>

                    <p>BY CLICKING ON THE “I ACCEPT” BUTTON, COMPLETING THE REGISTRATION PROCESS, AND/ORACCESSING THE SITE YOU REPRESENT THAT (1) YOU HAVE READ, UNDERSTAND, AND AGREE TO BE BOUND BY THE TERMS OF USE, (2) YOU ARE OF LEGAL AGE TO FORM A BINDING CONTRACT WITH THE COMPANY, AND (3) YOU HAVE THE AUTHORITY TO ENTER INTO THE TERMS OF USE PERSONALLY OR ON BEHALF OF THE COMPANY YOU HAVE NAMED AS THE USER, AND TO BIND THAT COMPANY TO THE TERMS OF USE.  THE TERM <b>“YOU”</b> REFERS TO THE INDIVIDUAL OR LEGAL ENTITY, AS APPLICABLE, IDENTIFIED AS THE USER WHEN YOU REGISTERED ON THE SERVICES. <b>IF YOU DO NOT AGREE TO BE BOUND BY THE TERMS OF USE, YOU MAY NOT ACCESS OR USE THESERVICES.</b> </p>
                    <p><b>THE TERMS OF USE INCLUDE A CLASS ACTION WAIVER AND A WAIVER OF JURY TRIALS, AND REQUIRE BINDING ARBITRATION ON AN INDIVIDUAL BASIS TO RESOLVE DISPUTES.</b></p>
                    <p>Your use of, and participation in certain Services may be subject to additional terms (“Supplemental Terms”) and such Supplemental Terms will either be listed in these Terms or will be presented to you for your acceptance when you sign up to use the supplement Service.  If these Terms of Use and inconsistent with the Supplemental Terms, the Supplemental Terms will control with respect to such Service.  These Terms of Use and any applicable Supplemental Terms are referred to herein as the <b>“Terms”.</b></p>
                    <p>PLEASE NOTE THAT THE TERMS ARE SUBJECT TO CHANGE BY THE COMPANY IN ITS SOLE DISCRETION AT ANY TIME.  When changes are made, the Company will make a new copy of the Terms of Use available on the Site.  We will also update the “Last Updated” date at the top of the Terms of Use.  If we make any material changes, and you have registered with us to create an Account (as defined in Section 2.1 below), we will also send an e-mail to you at the last e-mail address you provided to us pursuant to the Terms.  Any changes to the Terms will be effective immediately for new users of the Service, and will be effective thirty (30) days after posting notice of such changes on the Site for existing users, provided that any material changes shall be effective for users who have an Account with us upon the earlier of thirty (30) days after posting notice of such changes on the Site or thirty (30) days after dispatch of an e-mail notice of such changes to Registered Users (defined in Section 2.1 below).  The Company may require you to provide consent to the updated Terms in a specified manner before further use of theService is permitted.  If you do not agree to any change(s) after receiving a notice of such change(s), you shall stop using the Services.  Otherwise, your continued use of the Services constitutes your acceptance of such change(s).  PLEASE REGULARLY CHECK THE SITE TO VIEW THE THEN-CURRENT TERMS. </p>

                    <ol>
                      <li><span>1.</span><b>Use of the Services.</b> Our Service acts as a venue to connect insurance brokers with insurance carriers. While the Services enable Users to communicate with other Users, the Company is not a party to any transaction or other agreement between Users, and each User is solely responsible for their interactions with other Users of the Services. The Site(s), the Services and the information and content available in the Site(s), and the Services (collectively, the “Company Properties”) are protected by copyright laws throughout the world. Unless otherwise specified by the Company in a separate license, your right to use any Company Properties is subject to the Terms.</li>
                      <ol>
                        <li><span>1.1</span><b>Certain Restrictions.</b> The rights granted to you in the Terms are subject to the following restrictions: (a) you shall not license, sell, rent, lease, transfer, assign, reproduce, distribute, host or otherwise commercially exploit the Company Properties or any portion of the Company Properties; (b) you shall not frame or utilize framing techniques to enclose any trademark, logo, or other Company Properties (including images, text, page layout or form) of the Company; (c) you shall not use any metatags or other “hidden text” using Company’s name or trademarks; (d) you shall not modify, translate, adapt, merge, make derivative works of, disassemble, decompile, reverse compile or reverse engineer any part of the Company Properties except to the extent the foregoing restrictions are expressly prohibited by applicable law; (e) access the Company Properties in order to build a similar or competitive website, application or service; (f) except as expressly stated herein, no part of the Company Properties may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means; and (g) you shall not remove or destroy any copyright notices or other proprietary markings contained on or in the Company Properties. Any future release, update or other addition to the Company Properties shall be subject to the Terms. The Company, its suppliers and service providers reserve all rights not granted in the Terms. Any unauthorized use of the Company Properties terminates the licenses granted by the Company pursuant to the Terms.</li>
                        <li><span>1.2</span><b>Necessary Equipment and Software.</b> You must provide all equipment and software necessary to connect to the Company Properties. You are solely responsible for any fees, including Internet connection or mobile fees, that you incur when accessing the Company Properties.</li>
                      </ol>

                      <li><span>2.</span><b>Registration</b></li>
                      <ol>
                        <li><span>2.1</span><b>Registering Your Account.</b> In order to access certain features of the Company Properties you may be required to become a Registered User.  For purposes of the Terms, a <b>“Registered User”</b> is a user of the Services (<b>“User”</b>) who has registered an account on the Site(<b>“Account”</b>).</li>
                        <li><span>2.2</span><b>Registration Data.</b> In registering for use of the Services you agree to (1) provide true, accurate, current and complete information about yourself as prompted by the Site’s registration form (the <b>“Registration Data”</b>); and (2) maintain and promptly update the Registration Data to keep it true, accurate, current and complete.  You represent that you are (x) at least thirteen (13) years old; (y) of legal age to form a binding contract; and (z) not a person barred from using the Company Properties under the laws of the United States, your place of residence or any other applicable jurisdiction.  You are responsible for all activities that occur under your Account.   You may not share your Account or password with anyone, and you agree to (a) notify the Company immediately of any unauthorized use of your password or any other breach of security at <Link href="mailto:support@benrevo.com">support@benrevo.com</Link>; and (b) exit from your Account at the end of each session.  If you provide any information that is untrue, inaccurate, not current or incomplete, or the Company has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, the Company has the right to suspend or terminate your Account and refuse any and all current or future use of the Company Properties (or any portion thereof).  You agree not to create an Account using a false identity or information, or on behalf of someone other than yourself.  You agree that you shall not have more than one Account per platform at any given time.  You agree not to create an Account or use the Company Properties if you have been previously removed by the Company, or if you have been previously banned from any of the Company Properties.</li>
                      </ol>
                      <li><span>3.</span><b>Responsibility for Content</b></li>
                      <ol>
                        <li><span>3.1</span><b>Types of Content.</b> You acknowledge that all information, data, text and/or other materials accessible through the Company Properties (<b>“Content”</b>) is the sole responsibility of the party from whom such Content originated. This means that you, and not the Company, are entirely responsible for all Content that you upload, post, e-mail, transmit or otherwise make available (<b>“Make Available”</b>) through the Company Properties (<b>“Your Content”</b>), and that you and other Users of the Company Properties, and not the Company, are similarly responsible for all Content they Make Available through the Company Properties (<b>“User Content”</b>).</li>
                        <li><span>3.2</span><b>No Obligation to Pre-Screen Content.</b> You acknowledge that the Company has no obligation to pre-screen Content (including, but not limited to, User Content), although the Company reserves the right in its sole discretion to pre-screen, refuse or remove any Content. By entering into the Terms, you hereby provide your irrevocable consent to such monitoring. You acknowledge and agree that you have no expectation of privacy concerning the transmission of Your Content, including without limitation chat, text, or voice communications. In the event that the Company pre-screens, refuses or removes any Content, you acknowledge that the Company will do so for the Company’s benefit, not yours. Without limiting the foregoing, the Company shall have the right to remove any Content that violates the Terms or is otherwise objectionable.</li>
                        <li><span>3.3</span><b>Storage.</b> Unless expressly agreed to by the Company in writing elsewhere, the Company has no obligation to store any of Your Content that you Make Available on the Company Properties. The Company has no responsibility or liability for the deletion or accuracy of any Content, including Your Content; the failure to store, transmit or receive transmission of Content; or the security, privacy, storage, or transmission of other communications originating with or involving use of the Company Properties. You agree that the Company retains the right to create reasonable limits on the Company’s use and storage of the Content, including Your Content, such as limits on file size, storage space, processing capacity, and similar limits described in the web pages accompanying the Services and as otherwise determined by the Company in its sole discretion.</li>
                      </ol>
                      <li><span>4.</span><b>Ownership</b></li>
                      <ol>
                        <li><span>4.1</span><b>Company Properties.</b> You agree that the Company and its suppliers own all rights, title and interest in the Company Properties. You will not remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Company Properties. Company’s stylized name <Image className="benrevo-logo" src={Benrevo} /> and other related graphics, logos, service marks and trade names used on or in connection with the Company Properties are the trademarks of the Company and may not be used without permission in connection with any third-party products or services. Other trademarks, service marks and trade names that may appear on or in the Company Properties are the property of their respective owners.</li>
                        <li><span>4.2</span><b>Your Account.</b> Notwithstanding anything to the contrary herein, you acknowledge and agree that you shall have no ownership or other property interest in your Account, and you further acknowledge and agree that all rights in and to your Account are and shall forever be owned by and inure to the benefit of the Company.</li>
                        <li><span>4.3</span><b>License to Your Content.</b> You grant the Company a fully paid, royalty-free, perpetual, irrevocable, worldwide, royalty-free, non-exclusive and fully sublicensable right (including any moral rights) and license to use, license, distribute, reproduce, modify, adapt, publicly perform, and publicly display, Your Content (in whole or in part) for the purposes of operating, and providing the Company Properties to you and other Users. You warrant that the holder of any worldwide intellectual property right, including moral rights, in Your Content, has completely and effectively waived all such rights and validly and irrevocably granted to you the right to grant the license stated above. You agree that you, not the Company, are responsible for all of Your Content that you Make Available on or in the Company Properties.</li>
                        <li><span>4.4</span><b>Feedback.</b> You agree that submission of any ideas, suggestions, documents, and/or proposals to the Company through its suggestion, feedback, wiki, forum or similar pages (“Feedback”) is at your own risk and that the Company has no obligations (including without limitation obligations of confidentiality) with respect to such Feedback. You represent and warrant that you have all rights necessary to submit the Feedback. You hereby grant to the Company a fully paid, royalty-free, perpetual, irrevocable, worldwide, non-exclusive, and fully sublicensable right and license to use, reproduce, perform, display, distribute, adapt, modify, re-format, create derivative works of, and otherwise commercially or non-commercially exploit in any manner, any and all Feedback, and to sublicense the foregoing rights, in connection with the operation and maintenance of the Company Properties.</li>
                      </ol>
                      <li><span>5.</span><b>User Conduct.</b> In connection with your use of the Company Properties, you shall not:</li>
                      <ol>
                        <li><span>5.1.</span>Make Available any Content that (i) is unlawful, tortious, defamatory, vulgar, obscene, libelous, or racially, ethnically or otherwise objectionable; (ii) violates, or encourages any conduct that would violate, any applicable law or regulation or would give rise to civil liability; (iii) promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group; (iv) is violent or threatening, or promotes violence or actions that are threatening to any other person; or (v) promotes illegal or harmful activities;</li>
                        <li><span>5.2</span>Harm minors in any way;</li>
                        <li><span>5.3</span>Impersonate any person or entity, including, but not limited to, the Company personnel, or falsely state or otherwise misrepresent your affiliation with a person or entity;</li>
                        <li><span>5.4</span>Make available any Content that you do not have a right to Make Available under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under non-disclosure agreements);</li>
                        <li><span>5.5</span>Make Available any Content that infringes the rights of any person or entity, including without limitation, any patent, trademark, trade secret, copyright, privacy, publicity or other proprietary or contractual rights;</li>
                        <li><span>5.6</span>Intentionally or unintentionally violate any applicable local, state, national or international law or regulation, or any order of a court;</li>
                        <li><span>5.7</span>Register for more than one Account or register for an Account on behalf of an individual other than yourself; </li>
                        <li><span>5.8</span>Stalk or otherwise harass any other User of our Company Properties; or</li>
                        <li><span>5.9</span>Advocate, encourage or assist any third party in doing any of the foregoing activities in this section.</li>
                      </ol>
                      <li><span>6.</span><b>Interactions with Other Users</b></li>
                      <ol>
                        <li><span>6.1</span><b>User Responsibility.</b> You are solely responsible for your interactions with other Users of the Services and any other parties with whom you interact through the Services; provided, however, that the Company reserves the right, but has no obligation, to intercede in such disputes. You agree that the Company will not be responsible for any liability incurred as the result of such interactions.</li>
                        <li><span>6.2</span><b>Content Provided by Other Users.</b> The Company Properties may contain User Content provided by other Users. The Company is not responsible for and does not control User Content. The Company has no obligation to review or monitor, and does not approve, endorse or make any representations or warranties with respect to User Content. You use all User Content and interact with other Users at your own risk.</li>
                      </ol>
                      <li><span>7.</span><b>Third-Party Websites &amp; Ads.</b> The Company Properties may contain links to third-party websites (<b>“Third-Party Websites”</b>). When you click on a link to a Third-Party Website, we will not warn you that you have left the Company Properties and are subject to the terms and conditions (including privacy policies) of another website or destination. Such Third-Party Websites are not under the control of the Company. The Company is not responsible for any Third-Party Websites. The Company provides these Third-Party Websites only as a convenience and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third-Party Websites, or their products or services. You use all links in Third-Party Websites at your own risk. When you leave our Website, our Terms and policies no longer govern. You should review applicable terms and policies, including privacy and data gathering practices, of any Third-Party Websites, and should make whatever investigation you feel necessary or appropriate before proceeding with any transaction with any third party. </li>
                      <li><span>8.</span><b>Indemnification.</b> You agree to indemnify and hold the Company, its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (collectively, the <b>“Company Parties”</b>) harmless from any losses, costs, liabilities and expenses (including reasonable attorneys’ fees) relating to or arising out of: (a) your use of, or inability to use, the Company Properties; (b) your violation of the Terms; or (c) your violation of any applicable laws, rules or regulations. The Company reserves the right, at its own cost, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will fully cooperate with the Company in asserting any available defenses. You agree that the provisions in this section will survive any termination of your Account, the Terms or your access to the Company Properties.</li>
                      <li><span>9.</span><b>Disclaimer of Warranties</b></li>
                      <ol>
                        <li><span>9.1</span><b>As Is.</b> YOU EXPRESSLY UNDERSTAND AND AGREE THAT TO THE EXTENT PERMITTED BY APPLICABLE LAW, YOUR USE OF THE COMPANY PROPERTIES IS AT YOUR SOLE RISK, AND THE COMPANY PROPERTIES ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS, WITH ALL FAULTS. COMPANY PARTIES EXPRESSLY DISCLAIM ALL WARRANTIES, REPRESENTATIONS, AND CONDITIONS OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.</li>

                        <ol>
                          <li><span>(a)</span>THE COMPANY PARTIES MAKE NO WARRANTY, REPRESENTATION OR CONDITION THAT: (1) THE COMPANY PROPERTIES WILL MEET YOUR REQUIREMENTS; (2) YOUR USE OF THE COMPANY PROPERTIES WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE; (3) THE RESULTS THAT MAY BE OBTAINED FROM USE OF THE COMPANY PROPERTIES WILL BE ACCURATE OR RELIABLE; OR (4) ANY ERRORS IN THE COMPANY PROPERTIES WILL BE CORRECTED. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM COMPANY OR THROUGH THE COMPANY PROPERTIES WILL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN.</li>
                        </ol>
                        <li><span>9.2</span><b>No Liability for Conduct of Third Parties.</b> YOU ACKNOWLEDGE AND AGREE THAT THE COMPANY PARTIES ARE NOT LIABLE, AND YOU AGREE NOT TO SEEK TO HOLD THE COMPANY PARTIES LIABLE, FOR THE CONDUCT OF THIRD PARTIES AND THAT THE RISK OF INJURY FROM SUCH THIRD PARTIES RESTS ENTIRELY WITH YOU.</li>
                      </ol>
                      <li><span>10.</span><b>Limitation of Liability</b></li>
                      <ol>
                        <li><span>10.1</span><b>Disclaimer of Certain Damages.</b> YOU UNDERSTAND AND AGREE THAT IN NO EVENT SHALL COMPANY PARTIES BE LIABLE FOR ANY LOSS OF PROFITS, REVENUE OR DATA, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN CONNECTION WITH THE COMPANY PROPERTIES, OR DAMAGES OR COSTS DUE TO LOSS OF PRODUCTION OR USE, BUSINESS INTERRUPTION, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, OR PERSONAL OR PROPERTY DAMAGE OR EMOTIONAL DISTRESS, WHETHER OR NOT COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, ARISING OUT OF OR IN CONNECTION WITH THE TERMS, OR FROM ANY COMMUNICATIONS, INTERACTIONS OR MEETINGS WITH OTHER USERS OF THE COMPANY PROPERTIES, ON ANY THEORY OF LIABILITY, RESULTING FROM: (1) THE USE OR INABILITY TO USE THE COMPANY PROPERTIES; (2) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED FOR TRANSACTIONS ENTERED INTO THROUGH THE COMPANY PROPERTIES; (3) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR DATA; (4) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE COMPANY PROPERTIES; OR (5) ANY OTHER MATTER RELATED TO THE COMPANY PROPERTIES, WHETHER BASED ON WARRANTY, COPYRIGHT, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL THEORY.</li>
                        <li><span>10.2</span><b>Cap on Liability.</b> UNDER NO CIRCUMSTANCES WILL THE COMPANY PARTIES BE LIABLE TO YOU FOR MORE THAN THE GREATER OF: (A) THE AMOUNT PAID BY YOU TO THE COMPANY FOR SERVICES PROVIDED BY THE SITE DURING THE TWELVE (12) MONTH PERIOD IMMEDIATELY PRECEDING THE EVENT(S) GIVING RISE TO A CLAIM; OR (B) FIFTY DOLLARS ($50).</li>
                        <li><span>10.3</span><b>User Content.</b> THE COMPANY PARTIES ASSUME NO RESPONSIBILITY FOR THE TIMELINESS, DELETION, MIS-DELIVERY OR FAILURE TO STORE ANY CONTENT (INCLUDING, BUT NOT LIMITED TO, YOUR CONTENT AND USER CONTENT), USER COMMUNICATIONS OR PERSONALIZATION SETTINGS.</li>
                        <li><span>10.4</span><b>Basis of the Bargain.</b>THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN COMPANY AND YOU. CERTAIN JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MIGHT HAVE ADDITIONAL RIGHTS.</li>
                      </ol>
                      <li><span>11.</span><b>Term and Termination </b></li>
                      <ol>
                        <li><span>11.1</span><b>Term.</b> The Terms commence on the date when you accept them (as described in the preamble above) and remain in full force and effect while you use the Company Properties, unless terminated earlier in accordance with the Terms.</li>
                        <li><span>11.2</span><b> Termination of Services by Company.</b>If you have materially breached any provision of the Terms, or if the Company is required to do so by law (e.g., where the provision of the Services is, or becomes, unlawful), the Company has the right to, immediately and without notice, suspend or terminate any Services provided to you. You agree that all terminations for cause shall be made in the Company’s sole discretion and that the Company shall not be liable to you or any third party for any termination of your Account.</li>
                        <li><span>11.3</span><b>Termination of Services by You.</b> If you want to terminate the Services provided by the Company, you may do so by (a) notifying the Company at any time and (b) closing your Account for all of the Services that you use. Your notice should be sent, in writing, to the Company's address set forth below. </li>
                        <li><span>11.4</span><b>Effect of Termination.</b> Termination of any Service includes removal of access to such Service and barring of further use of the Service. Termination of all Services also includes deletion of your password and all related information, files and Content associated with or inside your Account (or any part thereof), including Your Content. Upon termination of any Service, your right to use such Service will automatically terminate immediately. You understand that any termination of Services may involve deletion of Your Content associated therewith from our live databases. The Company will not have any liability whatsoever to you for any suspension or termination, including for deletion of Your Content. All provisions of the Terms which by their nature should survive, shall survive termination of Services, including without limitation, ownership provisions, warranty disclaimers, and limitation of liability.</li>
                      </ol>
                      <li><span>12.</span><b>Remedies</b></li>
                      <ol>
                        <li><span>12.1</span><b>Violations.</b> If the Company becomes aware of any possible violations by you of the Terms, the Company reserves the right to investigate such violations. If, as a result of the investigation, the Company believes that criminal activity has occurred, the Company reserves the right to refer the matter to, and to cooperate with, any and all applicable legal authorities. The Company is entitled, except to the extent prohibited by applicable law, to disclose any information or materials on or in the Company Properties, including Your Content, in the Company’s possession in connection with your use of the Company Properties, to (1) comply with applicable laws, legal process or governmental request; (2) enforce the Terms, (3) respond to any claims that Your Content violates the rights of third parties, (4) respond to your requests for customer service, or (5) protect the rights, property or personal safety of the Company, its Users or the public, and all enforcement or other government officials, as the Company in its sole discretion believes to be necessary or appropriate.</li>
                        <li><span>12.2</span><b>Breach.</b> In the event that the Company determines, in its sole discretion, that you have breached any portion of the Terms, or have otherwise demonstrated conduct inappropriate for the Company Properties, the Company reserves the right to:</li>
                        <ol>
                          <li><span>(a)</span>Warn you via e-mail (to any e-mail address you have provided to the Company) that you have violated the Terms;</li>
                          <li><span>(b)</span>Delete and/or discontinue delivery or transmission of any of Your Content provided by you or your agent(s) to the Company Properties;</li>
                          <li><span>(c)</span>Discontinue your registration(s) with the any of the Company Properties;</li>
                          <li><span>(d)</span>Notify and/or send Content to and/or fully cooperate with the proper law enforcement authorities for further action; and/or</li>
                          <li><span>(e)</span>Pursue any other action which the Company deems to be appropriate.</li>
                        </ol>
                        <li><span>12.3</span><b>No Subsequent Registration.</b> If your registration(s) with or ability to access the Company Properties is discontinued by the Company due to your violation of any portion of the Terms or for conduct otherwise inappropriate for the community, then you agree that you shall not attempt to re-register with or access the Company Properties or any Company community through use of a different member name or otherwise.</li>
                      </ol>
                      <li><span>13.</span><b>International Users.</b> The Company Properties can be accessed from countries around the world and may contain references to services and content that are not available in your country. These references do not imply that the Company intends to announce such services or content in your country. The Company Properties are controlled and offered by the Company from its facilities in the United States of America. The Company makes no representations that the Company Properties are appropriate or available for use in other locations. Those who access or use the Company Properties from other jurisdictions do so at their own volition and are responsible for compliance with local law.</li>
                      <li><span>14.</span><b>General Provisions</b></li>
                      <ol>
                        <li><span>14.1</span><b>Electronic Communications.</b> The communications between you and the Company use electronic means, whether you visit the Company Properties or send the Company e-mails, or whether the Company posts notices on the Company Properties or communicates with you via e-mail. For contractual purposes, you (1) consent to receive communications from the Company in an electronic form; and (2) agree that all terms and conditions, agreements, notices, disclosures, and other communications that the Company provides to you electronically satisfy any legal requirement that such communications would satisfy if it were to be in writing. The foregoing does not affect your statutory rights.</li>
                        <li><span>14.2</span><b>Release.</b> You hereby release the Company Parties and their successors from claims, demands, any and all losses, damages, rights, and actions of any kind, including personal injuries, death, and property damage, that is either directly or indirectly related to or arises from your use of the Company Properties, including but not limited to, any interactions with or conduct of other Users or third-party websites of any kind arising in connection with or as a result of the Terms or your use of the Company Properties. If you are a California resident, you hereby waive California Civil Code Section 1542, which states, “A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which, if known by him must have materially affected his settlement with the debtor.</li>
                        <li><span>14.3</span><b>Assignment.</b> The Terms, and your rights and obligations hereunder, may not be assigned, subcontracted, delegated or otherwise transferred by you without the Company’s prior written consent, and any attempted assignment, subcontract, delegation, or transfer in violation of the foregoing will be null and void.</li>
                        <li><span>14.4</span><b>Force Majeure.</b> The Company shall not be liable for any delay or failure to perform resulting from causes outside its reasonable control, including, but not limited to, acts of God, war, terrorism, riots, embargos, acts of civil or military authorities, fire, floods, accidents, strikes or shortages of transportation facilities, fuel, energy, labor or materials.</li>
                        <li><span>14.5</span>Questions, Complaints, Claims.If you have any questions, complaints or claims with respect to the Company Properties, please <br /> <Link to="contact">Contact Us</Link>.  We will do our best to address your concerns.  If you feel that your concerns have been addressed incompletely, we invite you to let us know for further investigation.</li>
                        <li><span>14.6</span><b>Limitations Period.</b> YOU AND THE COMPANY AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE TERMS, THE COMPANY PROPERTIES OR THE CONTENT MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.</li>
                        <li><span>14.7</span><b>Arbitration Agreement; Class Waiver; Waiver of Trial by Jury.</b> Please read this Arbitration Agreement carefully. It is part of your contract with Company and affects your rights. It contains procedures for <i>MANDATORY BINDING ARBITRATION AND A CLASS ACTION WAIVER.</i></li>
                        <ol>
                          <li><span>(a)</span><i>Applicability of Arbitration Agreement.</i> All claims and disputes (excluding claims for injunctive or other equitable relief as set forth below) in connection with the Terms or the use of any product or service provided by the Company that cannot be resolved informally or in small claims court shall be resolved by binding arbitration on an individual basis under the terms of this Arbitration Agreement. This Arbitration Agreement applies to you and the Company, and to any subsidiaries, affiliates, agents, employees, predecessors in interest, successors, and assigns, as well as all authorized or unauthorized users or beneficiaries of services or goods provided under the Terms.</li>
                          <li><span>(b)</span><i>Notice Requirement and Informal Dispute Resolution.</i> Before either party may seek arbitration, the party must first send to the other party a written Notice of Dispute (<b>“Notice”</b>) describing the nature and basis of the claim or dispute, and the requested relief. A Notice to the Company should be sent to: 101 West Broadway Suite 200, Attn:BenRevo Inc., San Diego CA, 92101. After the Notice is received, you and the Company may attempt to resolve the claim or dispute informally. If you and the Company do not resolve the claim or dispute within 30 days after the Notice is received, either party may begin an arbitration proceeding. The amount of any settlement offer made by any party may not be disclosed to the arbitrator until after the arbitrator has determined the amount of the award, if any, to which either party is entitled.</li>
                          <li><span>(c)</span><i>Arbitration Rules.</i> Arbitration shall be initiated through the American Arbitration Association (<b>“AAA”</b>), an established alternative dispute resolution provider (<b>“ADR Provider”</b>) that offers arbitration as set forth in this section. If AAA is not available to arbitrate, the parties shall agree to select an alternative ADR Provider. The rules of the ADR Provider shall govern all aspects of this arbitration, including but not limited to the method of initiating and/or demanding arbitration, except to the extent such rules are in conflict with the Terms. The AAA Consumer Arbitration Rules governing the arbitration are available online at www.adr.org or by calling the AAA at 1-800-778-7879. The arbitration shall be conducted by a single, neutral arbitrator. Any claims or disputes where the total amount of the award sought is less than Ten Thousand U.S. Dollars (US $10,000.00 ) may be resolved through binding non-appearance-based arbitration, at the option of the party seeking relief. For claims or disputes where the total amount of the award sought is Ten Thousand U.S. Dollars (US $10,000.00) or more, the right to a hearing will be determined by the Arbitration Rules. Any hearing will be held in a location within 100 miles of your residence, unless you reside outside of the United States, and unless the parties agree otherwise. Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. Each party shall bear its own costs (including attorney’s fees) and disbursements arising out of the arbitration, and shall pay an equal share of the fees and costs of the ADR Provider.</li>
                          <li><span>(d)</span><i>Additional Rules for Non-appearance Based Arbitration:</i> If non-appearance arbitration is elected, the arbitration shall be conducted by telephone, online and/or based solely on written submissions; the specific manner shall be chosen by the party initiating the arbitration. The arbitration shall not involve any personal appearance by the parties or witnesses unless otherwise mutually agreed by the parties.</li>
                          <li><span>(e)</span><i>Time Limits.</i>If you or the Company pursue arbitration, the arbitration action must be initiated and/or demanded within the statute of limitations (i.e., the legal deadline for filing a claim) and within any deadline imposed under the AAA Rules for the pertinent claim.</li>
                          <li><span>(f)</span><i>Authority of Arbitrator.</i>The arbitrator, and not any federal, state or local court or agency shall have exclusive authority to (a) determine the scope and enforceability of this Arbitration Agreement and (b) resolve any dispute related to the interpretation, applicability, enforceability or formation of this Arbitration Agreement including, but not limited to any claim that all or any part of this Arbitration Agreement is void or voidable.  The arbitration will decide the rights and liabilities, if any, of you and Company.   The arbitration proceeding will not be consolidated with any other matters or joined with any other cases or parties.  The arbitrator shall have the authority to grant motions dispositive of all or part of any claim. The arbitrator shall have the authority to award monetary damages and to grant any non-monetary remedy or relief available to an individual under applicable law, the arbitral forum’s rules, and the Agreement (including the Arbitration Agreement). The arbitrator shall issue a written award and statement of decision describing the essential findings and conclusions on which the award is based, including the calculation of any damages awarded.  The arbitrator has the same authority to award relief on an individual basis that a judge in a court of law would have. The award of the arbitrator is final and binding upon you and us.</li>
                          <li><span>(g)</span><i>Waiver of Jury Trial.</i>THE PARTIES HEREBY WAIVE THEIR CONSTITUTIONAL AND STATUTORY RIGHTS TO GO TO COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR A JURY, instead electing that all claims and disputes shall be resolved by arbitration under this Arbitration Agreement. Arbitration procedures are typically more limited, more efficient and less costly than rules applicable in court and are subject to very limited review by a court. In the event any litigation should arise between you and the Company in any state or federal court in a suit to vacate or enforce an arbitration award or otherwise, YOU AND THE COMPANY WAIVE ALL RIGHTS TO A JURY TRIAL, instead electing that the dispute be resolved by a judge.</li>
                          <li><span>(h)</span><i>Waiver of Class or Consolidated Actions.</i> ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED OR LITIGATED ON AN INDIVIDUAL BASIS AND NOT ON A CLASS BASIS, AND CLAIMS OF MORE THAN ONE CUSTOMER OR USER CANNOT BE ARBITRATED OR LITIGATED JOINTLY OR CONSOLIDATED WITH THOSE OF ANY OTHER CUSTOMER OR USER. Notwithstanding anything to the contrary herein, (a) representative action for public injunctive relief may be arbitrated on a class basis and (b) in the event that the foregoing sentence is deemed invalid or unenforceable with respect to a particular class or dispute for recovery of damages, neither you nor we are entitled to arbitration and instead claims and disputes shall be resolved in a court as set forth in Section 14.8.</li>
                          <li><span>(i)</span><i>Confidentiality.</i>All aspects of the arbitration proceeding, including but not limited to the award of the arbitrator and compliance therewith, shall be strictly confidential. The parties agree to maintain confidentiality unless otherwise required by law. This Paragraph shall not prevent a party from submitting to a court of law any information necessary to enforce this Agreement, to enforce an arbitration award, or to seek injunctive or equitable relief.</li>
                          <li><span>(j)</span><i>Severability.</i>If any part or parts of this Arbitration Agreement are found under the law to be invalid or unenforceable by a court of competent jurisdiction, then such specific part or parts shall be of no force and effect and shall be severed and the remainder of the Agreement shall continue in full force and effect.</li>
                          <li><span>(k)</span><i>Right to Waive.</i>Any or all of the rights and limitations set forth in this Agreement may be waived by the party against whom the claim is asserted. Such waiver shall not waive or effect any other portion of this Agreement.</li>
                          <li><span>(l)</span><i>Survival of Agreement.</i> This Arbitration Agreement will survive the termination of your relationship with Company.</li>
                          <li><span>(j)</span><i>Courts.</i>In any circumstances where the foregoing Agreement permits the parties to litigate in court, the parties hereby agree to submit to the personal jurisdiction of the courts located within San Francisco, California, for such purpose.</li>
                        </ol>
                        <li><span>14.8</span><b>Governing Law.</b> The Terms and any action related thereto will be governed and interpreted by and under the laws of the State of California, consistent with the Federal Arbitration Act, without giving effect to any principles that provide for the application of the law of another jurisdiction. The United Nations Convention on Contracts for the International Sale of Goods does not apply to this Agreement.</li>
                        <li><span>14.9</span><b>Notice.</b> Where the Company requires that you provide an e-mail address, you are responsible for providing the Company with your most current e-mail address. In the event that the last e-mail address you provided to the Company is not valid, or for any reason is not capable of delivering to you any notices required/ permitted by the Terms, the Company’s dispatch of the e-mail containing such notice will nonetheless constitute effective notice. You may give notice to the Company at the following address: 101 West Broadway Suite 200, Attn:BenRevo Inc., San Diego CA, 92101. Such notice shall be deemed given when received by the Company by letter delivered by nationally recognized overnight delivery service or first class postage prepaid mail at the above address.</li>
                        <li><span>14.10</span><b>Waiver.</b> Any waiver or failure to enforce any provision of the Terms on one occasion will not be deemed a waiver of any other provision or of such provision on any other occasion.</li>
                        <li><span>14.11</span><b>Severability.</b> If any provision of the Terms is, for any reason, held to be invalid or unenforceable, the other provisions of the Terms will remain enforceable, and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law.</li>
                        <li><span>14.12</span><b>Export Control.</b> You may not use, export, import, or transfer the Company Properties except as authorized by U.S. law, the laws of the jurisdiction in which you obtained the Company Properties, and any other applicable laws. In particular, but without limitation, the Company Properties may not be exported or re-exported (a) into any United States embargoed countries, or (b) to anyone on the U.S. Treasury Department’s list of Specially Designated Nationals or the U.S. Department of Commerce’s Denied Person’s List or Entity List. By using the Company Properties, you represent and warrant that (i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties. You also will not use the Company Properties for any purpose prohibited by U.S. law, including the development, design, manufacture or production of missiles, nuclear, chemical or biological weapons. You acknowledge and agree that products, services or technology provided by Company are subject to the export control laws and regulations of the United States. You shall comply with these laws and regulations and shall not, without prior U.S. government authorization, export, re-export, or transfer the Company products, services or technology, either directly or indirectly, to any country in violation of such laws and regulations.</li>
                        <li><span>14.13</span><b>Consumer Complaints.</b> In accordance with California Civil Code §1789.3, you may report complaints to the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs by contacting them in writing at 400 R Street, Sacramento, CA 95814, or by telephone at (800) 952-5210.</li>
                        <li><span>14.14</span><b>Entire Agreement.</b> The Terms are the final, complete and exclusive agreement of the parties with respect to the subject matter hereof and supersedes and merges all prior discussions between the parties with respect to such subject matter.</li>
                      </ol>
                    </ol>
                  </div>
                </Grid.Column>
              </Grid.Row>
            </Grid>
          </Grid.Column>
        </Grid>
      </div>
    );
  }
}

export default Terms;
