source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

gem 'rails', '5.2.0'
gem 'pg', '1.0.0'
gem 'puma', '3.11.4'
gem 'dotenv-rails', '2.5.0'
gem 'config', '1.7.0'

group :development, :test do
  gem 'rspec-rails', '3.7.2'
  gem 'factory_bot_rails', '4.8.2'
  gem 'pry'
  gem 'pry-nav'
  gem 'pry-rails'
  gem 'pry-remote'
end

group :development do
  gem 'listen', '3.1.5'
  gem 'spring', '2.0.2'
  gem 'spring-watcher-listen', '2.0.1'
end

github 'gettuk/service_contract', branch: 'master' do
  gem 'gett-core'
end
