#!groovy
pipeline {
  options {
    disableConcurrentBuilds()
    buildDiscarder(logRotator(numToKeepStr: '10'))
    overrideIndexTriggers(true)
  }
  agent {
    node {
      label 'buildfarm'
    }
  }
  tools {
    maven 'maven'
  }
  environment {
    DB_URL = 'jdbc:mysql://rds-unittest.cbogremexott.us-east-1.rds.amazonaws.com:3306/br_dev'
    DB_USERNAME = 'root'
    DB_PASSWORD = credentials('UNIT_TEST_DB_PASSWORD')
    DB_DATA_ENCRYPTION_ENABLED = 'false'
    DB_DATA_ENCRYPTION_PASSWORD = credentials('UNIT_TEST_DB_ENCRYPTION_PASSWORD')
    HSM_IP = '172.31.64.149'
    HSM_PARTITION = 'PARTITION_1'

    DEV_TOKEN_ID = 'AKIAIEV2Q2CEUNPABDKA'
    DEV_TOKEN_SECRET = credentials('AWS_DEV_ACCESS_SECRET')
    HSM_USER = 'br_app'
    HSM_PASSWORD = credentials('HSM_PASSWORD')

    PROD_ANT_TOKEN_ID = 'AKIAILFFQT66VOH6U4YA'
    PROD_ANT_TOKEN_SECRET = credentials('PROD_ANT_AWS_ACCESS_SECRET')
    PROD_ANT_HSM_IP = '10.50.3.203'
    PROD_ANT_HSM_PASSWORD = credentials('PROD_ANT_HSM_PASSWORD')

    PROD_UHC_TOKEN_ID = 'AKIAJMGGUG3HSUXCOGBA'
    PROD_UHC_TOKEN_SECRET = credentials('PROD_UHC_AWS_ACCESS_SECRET')
    PROD_UHC_HSM_IP = '10.50.3.140'
    PROD_UHC_HSM_PASSWORD = credentials('PROD_UHC_HSM_PASSWORD')

    COVERALLS_REPO_TOKEN = credentials('DASHBOARD_SERVICE_COVERALLS_REPO_TOKEN')
    COVERALLS_SERVICE_NAME = 'Jenkins'
  }
  stages {
    stage('Setup') {
      parallel {
        stage('UHC') {
          steps {
            ws("${BUILD_TAG}uhc") {
              wrap([$class: 'BuildUser']) {
                slackSend message: "Starting build: ${JOB_NAME} ${BUILD_DISPLAY_NAME} caused by ${env.CHANGE_AUTHOR}: ${RUN_DISPLAY_URL}"
              }
              checkout([
                $class: 'GitSCM',
                branches: [[name: '${BRANCH_NAME}']],
                doGenerateSubmoduleConfigurations: false,
                extensions: [],
                submoduleCfg: [],
                userRemoteConfigs: [[
                  credentialsId: '81e0269c-8b0b-4eeb-97f2-03da4cb75100',
                  url: 'https://github.com/BenRevo/be-dashboards-service.git'
                ]]
              ])
            }
          }
        }
        stage('Anthem') {
          steps {
            ws("${BUILD_TAG}ant") {
              checkout([
                $class: 'GitSCM',
                branches: [[name: '${BRANCH_NAME}']],
                doGenerateSubmoduleConfigurations: false,
                extensions: [],
                submoduleCfg: [],
                userRemoteConfigs: [[
                  credentialsId: '81e0269c-8b0b-4eeb-97f2-03da4cb75100',
                  url: 'https://github.com/BenRevo/be-dashboards-service.git'
                ]]
              ])
            }
          }
        }
      }
    }
    stage('Resolve') {
      steps {
        sh '''
#!/bin/bash -xe

export AWS_REGION="us-east-1"
export AWS_REGION_NAME="us-east-1"
export AWS_ACCESS_KEY_ID=$DEV_TOKEN_ID
export AWS_SECRET_ACCESS_KEY=$DEV_TOKEN_SECRET

mvn clean install -q -B -U -DskipTests=true -Dsilent=true -s .s3.settings.xml
        '''
      }
    }
    stage('Test UHC') {
      steps {
        ws("${BUILD_TAG}uhc") {
          sh '''
#!/bin/bash -xe
export APP_CARRIER="UHC"

if [ "${GIT_BRANCH}" = "develop" ]
then
    export APP_ENV="dev"
    export AWS_REGION="us-east-1"
    export AWS_REGION_NAME="us-east-1"
    export AWS_ACCESS_KEY_ID=$DEV_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$DEV_TOKEN_SECRET
fi

if [ "${GIT_BRANCH}" = "stage" ]
then
    export APP_ENV="dev"
    export AWS_REGION="us-east-1"
    export AWS_REGION_NAME="us-east-1"
    export AWS_ACCESS_KEY_ID=$DEV_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$DEV_TOKEN_SECRET
fi

if [ "${GIT_BRANCH}" = "master" ]
then
    export APP_ENV="prod"
    export AWS_REGION="us-west-2"
    export AWS_REGION_NAME="us-west-2"
    export AWS_ACCESS_KEY_ID=$PROD_UHC_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$PROD_UHC_TOKEN_SECRET
fi

mvn clean install -pl carriers/uhc -am -amd -s .s3.settings.xml -B -V
          '''
          jacoco exclusionPattern: '**/test*', execPattern: '**/build/reports/target/jacoco-aggregate/**.exec'
        }
      }
    }
    stage('Test Anthem') {
      steps {
        ws("${BUILD_TAG}ant") {
          sh '''
#!/bin/bash -xe
export APP_CARRIER="ANTHEM_BLUE_CROSS"

if [ "${GIT_BRANCH}" = "develop" ]
then
    export APP_ENV="dev"
    export AWS_REGION="us-east-1"
    export AWS_REGION_NAME="us-east-1"
    export AWS_ACCESS_KEY_ID=$DEV_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$DEV_TOKEN_SECRET
fi

if [ "${GIT_BRANCH}" = "stage" ]
then
    export APP_ENV="dev"
    export AWS_REGION="us-east-1"
    export AWS_REGION_NAME="us-east-1"
    export AWS_ACCESS_KEY_ID=$DEV_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$DEV_TOKEN_SECRET
fi

if [ "${GIT_BRANCH}" = "master" ]
then
    export APP_ENV="prod"
    export AWS_REGION="us-west-2"
    export AWS_REGION_NAME="us-west-2"
    export AWS_ACCESS_KEY_ID=$PROD_ANT_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$PROD_ANT_TOKEN_SECRET
fi

mvn clean install -pl carriers/anthem -am -amd -s .s3.settings.xml -B -V
          '''
          jacoco exclusionPattern: '**/test*', execPattern: '**/build/reports/target/jacoco-aggregate/**.exec'
        }
      }
    }
    /*stage('Dependency Check') {
      steps {
        dependencyCheckAnalyzer([
          datadir: "/var/jenkins_home/.m2/repository/org/owasp/dependency-check-data/",
          hintsFile: "",
          includeCsvReports: false,
          includeHtmlReports: false,
          includeJsonReports: false,
          includeVulnReports: false,
          isAutoupdateDisabled: false,
          outdir: "",
          scanpath: "",
          skipOnScmChange: false,
          skipOnUpstreamChange: false,
          suppressionFile: "",
          zipExtensions: 'zip,jar'
        ])
      }
    }*/
    stage('Deploy') {
      parallel {
        stage('UHC') {
          steps {
            ws("${BUILD_TAG}uhc") {
              sh '''
#!/bin/bash -xe

export CARRIER="UHC"
export CARRIER_PLACEHOLDER="uhc"
mkdir ./.elasticbeanstalk

if [ "${GIT_BRANCH}" = "develop" ]
then
    export AWS_REGION_NAME="us-east-1"
    export AWS_DEPLOY_NAME="be-dashboards-uhc"
    export AWS_ACCESS_KEY_ID=$DEV_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$DEV_TOKEN_SECRET

    cp ./internal/deploy/dev/uhc/config.yml ./.elasticbeanstalk/
fi

if [ "${GIT_BRANCH}" = "stage" ]
then
    export AWS_REGION_NAME="us-east-1"
    export AWS_DEPLOY_NAME="be-dashboards-uhc-stage"
    export AWS_ACCESS_KEY_ID=$DEV_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$DEV_TOKEN_SECRET

    cp ./internal/deploy/stage/uhc/config.yml ./.elasticbeanstalk/
fi

if [ "${GIT_BRANCH}" = "master" ]
then
    export AWS_REGION_NAME="us-west-2"
    export AWS_DEPLOY_NAME="be-uhc-dashboard"
    export AWS_ACCESS_KEY_ID=$PROD_UHC_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$PROD_UHC_TOKEN_SECRET

    cp ./internal/deploy/prod/uhc/config.yml ./.elasticbeanstalk/
fi

if [ "$(aws sts get-caller-identity | grep -c 'UserId')" -eq 1 ]
then
    echo "##### Successful authorization from AWS"
fi

eb deploy $AWS_DEPLOY_NAME --label "$BUILD_TAG:$CARRIER_PLACEHOLDER" --verbose --staged --timeout 60
              '''
            }
          }
        }
        stage('Anthem') {
          steps {
            ws("${BUILD_TAG}ant") {
              sh '''
#!/bin/bash -xe

export CARRIER="ANTHEM_BLUE_CROSS"
export CARRIER_PLACEHOLDER="ant"
mkdir ./.elasticbeanstalk

if [ "${GIT_BRANCH}" = "develop" ]
then
    export AWS_REGION_NAME="us-east-1"
    export AWS_DEPLOY_NAME="be-dashboards-anthem"
    export AWS_ACCESS_KEY_ID=$DEV_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$DEV_TOKEN_SECRET

    cp ./internal/deploy/dev/ant/config.yml ./.elasticbeanstalk/
fi

if [ "${GIT_BRANCH}" = "stage" ]
then
    export AWS_REGION_NAME="us-east-1"
    export AWS_DEPLOY_NAME="be-dashboards-anthem-stage"
    export AWS_ACCESS_KEY_ID=$DEV_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$DEV_TOKEN_SECRET

    cp ./internal/deploy/stage/ant/config.yml ./.elasticbeanstalk/
fi

if [ "${GIT_BRANCH}" = "master" ]
then
    export AWS_REGION_NAME="us-west-2"
    export AWS_DEPLOY_NAME="be-anthem-dashboard"
    export AWS_ACCESS_KEY_ID=$PROD_ANT_TOKEN_ID
    export AWS_SECRET_ACCESS_KEY=$PROD_ANT_TOKEN_SECRET

    cp ./internal/deploy/prod/ant/config.yml ./.elasticbeanstalk/
fi

if [ "$(aws sts get-caller-identity | grep -c 'UserId')" -eq 1 ]
then
    echo "##### Successful authorization from AWS"
fi

if [ "${GIT_BRANCH}" = "develop" ]
then
    eb deploy $AWS_DEPLOY_NAME --label "$BUILD_TAG:$CARRIER_PLACEHOLDER" --verbose --staged --timeout 60
fi    
              '''
            }
          }
        }
      }
    }
  }
  post {
    /*always {
      dependencyCheckPublisher([
        canComputeNew: false,
        defaultEncoding: "",
        healthy: "",
        unHealthy: "",
        pattern: "",
        shouldDetectModules: true
      ])
    }*/
    failure {
      wrap([$class: 'BuildUser']) {
        slackSend color: "danger", message: "Build failed: ${JOB_NAME} ${BUILD_DISPLAY_NAME} caused by ${env.CHANGE_AUTHOR}. Build results: ${RUN_DISPLAY_URL}"
        emailext body: '${JOB_NAME} ${BUILD_DISPLAY_NAME} - failed: Check console output at ${RUN_DISPLAY_URL} to view the results.', recipientProviders: [[$class: 'CulpritsRecipientProvider']], subject: 'Build failed: ${JOB_NAME} ${BUILD_DISPLAY_NAME}'
      }
    }
    success {
      wrap([$class: 'BuildUser']) {
        slackSend color: "good", message: "Build success: ${JOB_NAME} ${BUILD_DISPLAY_NAME} caused by ${env.CHANGE_AUTHOR}. Build results: ${RUN_DISPLAY_URL}"
        emailext body: '${JOB_NAME} ${BUILD_DISPLAY_NAME} - success: Check console output at ${RUN_DISPLAY_URL} to view the results.', recipientProviders: [[$class: 'CulpritsRecipientProvider']], subject: 'Build success: ${JOB_NAME} ${BUILD_DISPLAY_NAME}'
      }
    }
  }
}
