branch-defaults:
  develop:
    environment: PRD-ANT-backendSuperAdmin
environment-defaults:
  PRD-ANT-backendSuperAdmin:
    branch: null
    repository: null
global:
  application_name: PRD-ANT-Backend-SuperAdmin
  default_ec2_keyname: BENREVO-ANTHEM-MASTER
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/64bit Amazon Linux 2017.03 v2.6.0 running Java 8
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
deploy:
  artifact: carriers/anthem/target/anthem-admin-service.zip
