import { IVThemeFontItem } from '@invest.wl/view/src/Theme/V.Theme.types';

export const textStyles: { [T: string]: IVThemeFontItem } = {
  bold32: {
    fontFamily: 'Gilroy-Bold',
    fontSize: 32,
    lineHeight: 32,
    letterSpacing: 0,
  },
  medium32: {
    fontFamily: 'Gilroy-Medium',
    fontSize: 32,
    lineHeight: 32,
    letterSpacing: 0,
  },
  bold28: {
    fontFamily: 'Gilroy-Bold',
    fontSize: 28,
    lineHeight: 28,
    letterSpacing: 0,
  },
  medium24: {
    fontFamily: 'Gilroy-Medium',
    fontSize: 24,
    lineHeight: 24,
    letterSpacing: 0,
  },
  bold22: {
    fontFamily: 'Gilroy-Bold',
    fontSize: 22,
    lineHeight: 22,
    letterSpacing: 0,
  },
  medium20: {
    fontFamily: 'Gilroy-Medium',
    fontSize: 20,
    lineHeight: 20,
    letterSpacing: 0,
  },
  semibold20x104: {
    fontFamily: 'Gilroy-Semibold',
    fontSize: 20,
    lineHeight: 21,
    letterSpacing: 0,
  },
  semibold18x122: {
    fontFamily: 'Gilroy-Semibold',
    fontSize: 18,
    lineHeight: 20,
    letterSpacing: 0,
  },
  medium18: {
    fontFamily: 'Gilroy-Medium',
    fontSize: 18,
    lineHeight: 18,
    letterSpacing: 0,
  },
  regular18: {
    fontFamily: 'Gilroy-Regular',
    fontSize: 18,
    lineHeight: 18,
    letterSpacing: 0,
  },
  regular18x134: {
    fontFamily: 'Gilroy-Regular',
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: 0,
  },
  semibold18: {
    fontFamily: 'Gilroy-Semibold',
    fontSize: 18,
    lineHeight: 18,
    letterSpacing: 0,
  },
  semibold16: {
    fontFamily: 'Gilroy-Semibold',
    fontSize: 16,
    lineHeight: 16,
    letterSpacing: 0,
  },
  semibold16x140: {
    fontFamily: 'Gilroy-Semibold',
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: 0,
  },
  regular16: {
    fontFamily: 'Gilroy-Regular',
    fontSize: 16,
    lineHeight: 16,
    letterSpacing: 0,
  },
  regular16x140: {
    fontFamily: 'Gilroy-Regular',
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: 0,
  },
  semibold14: {
    fontFamily: 'Gilroy-Semibold',
    fontSize: 14,
    lineHeight: 14,
    letterSpacing: 0,
  },
  regular14: {
    fontFamily: 'Gilroy-Regular',
    fontSize: 14,
    lineHeight: 14,
    letterSpacing: 0,
  },
  regular14x140: {
    fontFamily: 'Gilroy-Regular',
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0,
  },
  medium12: {
    fontFamily: 'Gilroy-Medium',
    fontSize: 12,
    lineHeight: 12,
    letterSpacing: 0,
  },
  regular12: {
    fontFamily: 'Gilroy-Regular',
    fontSize: 12,
    lineHeight: 12,
    letterSpacing: 0,
  },
  regular12x140: {
    fontFamily: 'Gilroy-Regular',
    fontSize: 12,
    lineHeight: 17,
    letterSpacing: 0,
  },
  semibold10: {
    fontFamily: 'Gilroy-Semibold',
    fontSize: 10,
    lineHeight: 10,
    letterSpacing: 0,
  },
  medium10: {
    fontFamily: 'Gilroy-Medium',
    fontSize: 10,
    lineHeight: 10,
    letterSpacing: 0,
  },
  regular10: {
    fontFamily: 'Gilroy-Regular',
    fontSize: 10,
    lineHeight: 10,
    letterSpacing: 0,
  },
  /* ==================ExpoBank=================== */
  title2: {
    fontFamily: 'Gilroy-SemiBold',
    fontSize: 28,
    lineHeight: 33,
    letterSpacing: 0.5,
  },
  title3: {
    fontFamily: 'Gilroy-Medium',
    fontSize: 20,
    lineHeight: 23,
    letterSpacing: 0.5,
  },
  title5: {
    fontFamily: 'Gilroy-Bold',
    fontSize: 18,
    lineHeight: 21,
  },
  body1: {
    fontFamily: 'Gilroy-SemiBold',
    fontSize: 18,
    lineHeight: 21,
  },
  body2: {
    fontFamily: 'Gilroy-Bold',
    fontSize: 17,
    lineHeight: 20,
  },
  body3: {
    fontFamily: 'Gilroy-Bold',
    fontSize: 16,
    lineHeight: 19,
    letterSpacing: 0.5,
  },
  body4: {
    fontFamily: 'Gilroy-SemiBold',
    fontSize: 16,
    lineHeight: 19,
    letterSpacing: 0.5,
  },
  body5: {
    fontFamily: 'Gilroy-Medium',
    fontSize: 16,
    lineHeight: 19,
    letterSpacing: 0.5,
    color: '#000',
  },
  body6: {
    fontFamily: 'Gilroy-Regular',
    fontSize: 16,
    lineHeight: 19,
    color: '#000',
  },
  body7: {
    fontFamily: 'Gilroy-Regular',
    fontSize: 16,
    lineHeight: 19,
    color: '#000',
  },
  body8: {
    fontFamily: 'Gilroy-SemiBold',
    fontSize: 15,
    lineHeight: 18,
  },
  body9: {
    fontFamily: 'Gilroy-Medium',
    fontSize: 15,
    lineHeight: 19,
    letterSpacing: 0.5,
  },
  body9link: {
    fontFamily: 'Gilroy-Medium',
    fontSize: 15,
    lineHeight: 19,
    letterSpacing: 0.5,
    textDecorationLine: 'underline',
  },
  body10: {
    fontFamily: 'Gilroy-Medium',
    fontSize: 15,
    lineHeight: 21,
    letterSpacing: 0.5,
  },
  body11: {
    fontFamily: 'Gilroy-Bold',
    fontSize: 14,
    lineHeight: 16,
    letterSpacing: 0.5,
  },
  body12: {
    fontFamily: 'Gilroy-SemiBold',
    fontSize: 14,
    lineHeight: 16,
    letterSpacing: 0.5,
  },
  body13: {
    fontFamily: 'Gilroy-Medium',
    fontSize: 14,
    lineHeight: 18.2,
    letterSpacing: 0.5,
  },
  body14: {
    fontFamily: 'Gilroy-Regular',
    fontSize: 14,
    lineHeight: 16.4,
    letterSpacing: 0.5,
  },
  body15: {
    fontFamily: 'Gilroy-Bold',
    fontSize: 13,
    lineHeight: 18,
  },
  body16: {
    fontFamily: 'Gilroy-SemiBold',
    fontSize: 13,
    lineHeight: 18,
    letterSpacing: 0.25,
  },
  body17: {
    fontFamily: 'Gilroy-Medium',
    fontSize: 13,
    lineHeight: 15.23,
    letterSpacing: 0.25,
  },
  body18: {
    fontFamily: 'Gilroy-Medium',
    fontSize: 12,
    lineHeight: 20,
    letterSpacing: 0.5,
  },
  body19: {
    fontFamily: 'Gilroy-Medium',
    fontSize: 12,
    lineHeight: 14,
  },
  body20: {
    fontFamily: 'Gilroy-Regular',
    fontSize: 12,
    lineHeight: 14,
    letterSpacing: 0.25,
  },
  body21: {
    fontFamily: 'Gilroy-SemiBold',
    fontSize: 11,
    lineHeight: 13,
  },
  body22: {
    fontFamily: 'Gilroy-Medium',
    fontSize: 11,
    lineHeight: 13,
    letterSpacing: 0.25,
  },
  caption2: {
    fontFamily: 'Gilroy-Regular',
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0.25,
  },
};

export type TVThemeFontName = keyof typeof textStyles;
