- name: Update APT package cache
  action: apt update_cache=yes cache_valid_time=3600

- name: Upgrade APT to the lastest packages
  action: apt upgrade=safe

- name: Install Common packages
  apt:
    state: latest
    update_cache: yes
    cache_valid_time: 3600
    pkg: "{{ item }}"
  with_items:
    - htop
    - mc
    - iftop
    - iperf
    - wget
    - screen
    - language-pack-en
    - language-pack-en-base
