const planRatesTemplate = {
  javaclass: 'VoluntaryRateDto',
  ancillaryRateId: null,
  volume: null,
  monthlyCost: null,
  rateGuarantee: null,
  ages: [
    {
      ancillaryRateAgeId: null,
      from: 0,
      to: 29,
      currentEmp: null,
      renewalEmp: null,
      currentEmpTobacco: null,
      renewalEmpTobacco: null,
      currentSpouse: null,
      renewalSpouse: null,
    },
    {
      ancillaryRateAgeId: null,
      from: 30,
      to: 34,
      currentEmp: null,
      renewalEmp: null,
      currentEmpTobacco: null,
      renewalEmpTobacco: null,
      currentSpouse: null,
      renewalSpouse: null,
    },
    {
      ancillaryRateAgeId: null,
      from: 35,
      to: 39,
      currentEmp: null,
      renewalEmp: null,
      currentEmpTobacco: null,
      renewalEmpTobacco: null,
      currentSpouse: null,
      renewalSpouse: null,
    },
    {
      ancillaryRateAgeId: null,
      from: 40,
      to: 44,
      currentEmp: null,
      renewalEmp: null,
      currentEmpTobacco: null,
      renewalEmpTobacco: null,
      currentSpouse: null,
      renewalSpouse: null,
    },
    {
      ancillaryRateAgeId: null,
      from: 45,
      to: 49,
      currentEmp: null,
      renewalEmp: null,
      currentEmpTobacco: null,
      renewalEmpTobacco: null,
      currentSpouse: null,
      renewalSpouse: null,
    },
    {
      ancillaryRateAgeId: null,
      from: 50,
      to: 54,
      currentEmp: null,
      renewalEmp: null,
      currentEmpTobacco: null,
      renewalEmpTobacco: null,
      currentSpouse: null,
      renewalSpouse: null,
    },
    {
      ancillaryRateAgeId: null,
      from: 55,
      to: 59,
      currentEmp: null,
      renewalEmp: null,
      currentEmpTobacco: null,
      renewalEmpTobacco: null,
      currentSpouse: null,
      renewalSpouse: null,
    },
    {
      ancillaryRateAgeId: null,
      from: 60,
      to: 64,
      currentEmp: null,
      renewalEmp: null,
      currentEmpTobacco: null,
      renewalEmpTobacco: null,
      currentSpouse: null,
      renewalSpouse: null,
    },
    {
      ancillaryRateAgeId: null,
      from: 65,
      to: 69,
      currentEmp: null,
      renewalEmp: null,
      currentEmpTobacco: null,
      renewalEmpTobacco: null,
      currentSpouse: null,
      renewalSpouse: null,
    },
    {
      ancillaryRateAgeId: null,
      from: 70,
      to: 85,
      currentEmp: null,
      renewalEmp: null,
      currentEmpTobacco: null,
      renewalEmpTobacco: null,
      currentSpouse: null,
      renewalSpouse: null,
    },
  ],
  employee: true,
  employeeTobacco: true,
  spouse: true,
  spouseBased: null,
  rateEmpADD: null,
  rateSpouseADD: null,
  rateChildLife: null,
  rateChildADD: null,
};

export default planRatesTemplate;
