export enum MessageModalName {
  REGISTERED = 'registered',
  APPLICATION_CREATED = 'applicationCreated',
  APPLICATION_INSTALMENT_CREATED = 'applicationInstalmentCreated',
  APPLICATION_CANCELED = 'applicationCanceled',
  APPLICATION_SENT = 'applicationSent',
  INSURANCE_CALCULATING = 'insuranceCalculating',
  MODEL_SUBSCRIBED = 'modelSubscribed',
  CREDIT_APPLICATION_CREATED = 'creditApplicationCreated',
  INSTALMENT_APPLICATION_SENT = 'instalmentApplicationCreated',
  C2C_CREDIT_APPLICATION_SENT = 'c2cCreditApplicationCreated',
  INSTALMENT_APPLICATION_CANCEL_REQUESTED = 'instalmentApplicationCancelRequested',
  SELL_CREATED = 'sellCreated',
  SELL_CREATED_DEALERS_CLIENTS = 'sellCreatedDealersClients',
  SELL_CREATED_FOR_CLIENTS = 'sellCreatedForClients',
  SELL_EDITED = 'sellEdited',
  SELL_DEACTIVATED = 'sellDeactivated',
  SELL_DELETED = 'sellDeleted',
  DEPOSIT_CREATED = 'depositCreated',
  SAVINGS_ACCOUNT_CREATED = 'savingsAccountCreated',
  SIMPLE_CREDIT_CANCEL_REQUESTED = 'simpleCreditCancelRequested',
  DEBIT_CARD_REQUEST_CREATED = 'debitCardRequestCreated',
  SPECIAL_PROGRAM_REQUEST_CREATED = 'specialProgramRequestCreated',
}
