export enum VehicleSortType {
  PRICE_DESC = 1,
  PRICE_ASC = 2,
  PRODUCTION_YEAR_DESC = 3,
  PRODUCTION_YEAR_ASC = 4,
  MILEAGE_DESC = 5,
  MILEAGE_ASC = 6,
  CREATED_ASC = 7,
  CREATED_DESC = 8,
}
