const Constants = {
	SHOW_EMAIL_INPUT: "SHOW_EMAIL_INPUT",
	HIDE_EMAIL_INPUT: "HIDE_EMAIL_INPUT",
	SUBMIT_EMAIL_SUCCESSFUL: "SUBMIT_EMAIL_SUCCESSFUL",
	FETCH_FAQ_CATEGORIES: "FETCH_FAQ_CATEGORIES",
	FETCH_FAQ_CATEGORIES_SUCCESS: "FETCH_FAQ_CATEGORIES_SUCCESS",
	FETCH_FAQ_CATEGORIES_ERROR: "FETCH_FAQ_CATEGORIES_ERROR"

};

export default Constants;