import { StateModel } from 'store/types';
import {
  APPLICATION_CREDIT_STATUS,
  APPLICATION_INSURANCE_STATUS,
  APPLICATION_INSURANCE_TYPE,
  VEHICLE_SCENARIO,
  VEHICLE_TYPE,
  CreditType,
  SimpleCreditSubtype,
} from '@marketplace/ui-kit/types';
import { INSURANCE_FORM_TYPE, VEHICLE_OWNING_TYPE } from 'types/Insurance';
import { HomeTab } from 'types/Home';
import { ServiceStep } from 'types/Service';
import { VehicleSortType } from 'types/VehicleSortTypes';
import { CREDIT_INFO } from 'constants/credit';
import { CreditStep, SimpleCreditStep } from 'containers/Finance/Credit/types/CreditFormTypes';
import { defaultCity } from 'constants/defaultCity';
import { initialStateSession } from './user';

const initialBaseDefault = {
  loading: false,
  error: null,
  initial: null,
};

const initialListDefault = {
  currentPage: 1,
  sorting: null,
  pageLimit: 30,
};

export const initialState: StateModel = {
  ...initialStateSession,
  notifications: {
    ...initialBaseDefault,
    messages: [],
  },
  home: {
    ...initialBaseDefault,
    activeTab: HomeTab.BUY,
    meta: {
      vehiclesCount: 0,
    },
  },
  vehiclesBestOffers: {
    ...initialBaseDefault,
    items: null,
  },
  specialPrograms: {
    ...initialBaseDefault,
    items: null,
    count: 0,
  },
  specialProgram: {
    ...initialBaseDefault,
    data: {
      id: 0,
      name: '',
      subTitle: '',
      advantages: [
        { title: 'Ставка', valueSmallText: 'от', valueBigText: '4,5%' },
        { title: 'Сумма', valueSmallText: 'до', valueBigText: '3 млн ₽' },
        { title: 'Первый взнос', valueSmallText: 'от', valueBigText: '0%' },
        { title: 'Срок', valueSmallText: 'до', valueBigText: '6 лет' },
      ],
      description: '',
      title: '',
      alias: '',
      imgDesktop: {},
      imgMobile: {},
      link: '',
    },
    vehicles: [],
  },
  vehiclesFilter: {
    ...initialBaseDefault,
    sort: null,
    values: {
      type: null,
      city: '1',
      specialOffers: null,
      brands: null,
      models: null,
      generations: null,
      bodyTypes: null,
      transmissions: null,
      engines: null,
      drives: null,
      colors: null,
      priceFrom: null,
      priceTo: null,
      yearFrom: null,
      yearTo: null,
      powerFrom: null,
      powerTo: null,
      volumeFrom: null,
      volumeTo: null,
      mileageFrom: null,
      mileageTo: null,
      sellerType: null,
      installmentMonths: null,
      installmentMonthlyPaymentFrom: null,
      installmentMonthlyPaymentTo: null,
      salesOfficeId: null,
    },
    data: {
      specialOffers: [],
      brands: [],
      models: [],
      generations: [],
      bodyTypes: [],
      transmissions: [],
      engines: [],
      drives: [],
      colors: [],
      yearFrom: 0,
      yearTo: 0,
      priceFrom: 0,
      priceTo: 0,
      powerFrom: 0,
      powerTo: 0,
      volumeFrom: 0,
      volumeTo: 0,
      mileageFrom: 0,
      mileageTo: 0,
      installmentPayments: {
        12: { min: 0, max: 0 },
        24: { min: 0, max: 0 },
        36: { min: 0, max: 0 },
      },
      salesOfficeId: [],
    },
  },
  vehiclesList: {
    ...initialBaseDefault,
    ...initialListDefault,
    items: [] as any[],
    loadingPage: false,
    errorPage: null,
  },
  vehiclesMeta: {
    meta: {
      count: 0,
      vehiclesCount: 0,
      minPrice: 0,
    },
    ...initialBaseDefault,
  },
  vehicleItem: {
    ...initialBaseDefault,
    vehicle: null,
    availableColors: null,
    pickedColor: null,
  },
  vehicleRelatives: {
    ...initialBaseDefault,
    items: null,
  },
  brand: {
    ...initialBaseDefault,
    brand: null,
  },
  brandsNew: {
    ...initialBaseDefault,
    brands: {
      all: null,
      [VEHICLE_TYPE.NEW]: null,
      [VEHICLE_TYPE.USED]: null,
    },
  },
  aliasCheck: {
    ...initialBaseDefault,
    data: {
      brand: null,
      model: null,
      generation: null,
    },
  },
  blog: {
    ...initialBaseDefault,
    posts: null,
    blogCategories: null,
  },
  dealerPartners: {
    ...initialBaseDefault,
    partners: null,
  },
  vehicleCreate: {
    ...initialBaseDefault,
    lastUpdated: null,
    data: {
      brands: [],
      models: [],
      years: [],
      generations: [],
      bodies: [],
      transmissions: [],
      engines: [],
      drives: [],
      modifications: [],
      conditions: [],
      colors: [],
      optionGroups: [],
      cities: [],
    },
    values: {
      city: null,
      brand: null,
      model: null,
      year: null,
      bodyId: null,
      generationId: null,
      engineId: null,
      driveId: null,
      transmissionId: null,
      modificationId: null,
      condition: null,
      mileage: null,
      vin: null,
      price: null,
      colorId: null,
      videoUrl: null,
      imagesExterior: null,
      imagesInterior: null,
      stsFront: null,
      stsBack: null,
      ownersNumber: null,
    },
    valid: null,
    contacts: {
      firstName: null,
      lastName: null,
      middleName: null,
      meetFrom: 9,
      meetTo: 21,
      email: null,
      phone: null,
      latitude: null,
      longitude: null,
      address: null,
    },
    contactsValid: null,
    scenario: VEHICLE_SCENARIO.USED_AUCTION,
  },
  vehicleCreateData: {
    ...initialBaseDefault,
    catalogType: 'avito',
    params: {},
    data: {
      city: [],
      brand: [],
      model: [],
      year: [],
      generation: [],
      body: [],
      transmission: [],
      engine: [],
      drive: [],
      modification: [],
      color: [],
    },
  },
  vehicleDraftData: {
    ...initialBaseDefault,
    draftData: null,
    isSent: false,
  },
  vehicleCreateOptions: {
    ...initialBaseDefault,
    options: [],
  },
  vehicleCreateStickers: {
    ...initialBaseDefault,
    stickers: [],
  },
  vehicleCreateSellValues: {
    ...initialBaseDefault,
    values: {
      // static
      city: 17849,
      color: null,
      // dynamic
      brand: null,
      model: null,
      year: null,
      body: null,
      generation: null,
      engine: null,
      drive: null,
      transmission: null,
      modification: null,
      // advanced
      condition: null,
      mileage: null,
      vin: null,
      videoUrl: null,
      imagesExterior: null,
      imagesInterior: null,
      stsFront: null,
      stsBack: null,
      ownersNumber: null,
      comment: null,
      // price
      price: null,
      // contacts
      firstName: null,
      lastName: null,
      middleName: null,
      meetFrom: 9,
      meetTo: 21,
      address: null,
      email: null,
      phone: null,
      authSuccess: null,
      // scenario
      isC2B: false,
      isC2C: false,
      stickers: null,
    },
  },
  serviceRequest: {
    ...initialBaseDefault,
    step: ServiceStep.WORK_TYPE,
    values: {
      // static
      city: 17849,
      color: null,
      // dynamic
      workType: null,
      brand: null,
      model: null,
      year: null,
      licensePlate: null,
      vin: null,
      isTruckRequired: false,
      isOwnSpareParts: false,
      date: new Date(),
      time: new Date(),
      ratingFrom: 1,
      classification: null,
      swLat: 55.6881491596507,
      neLat: 55.82338561228506,
      swLong: 37.50881000976562,
      neLong: 37.72578999023437,
      withReview: false,
      withRating: false,
      hasPromotion: false,
      lat: 55.754135,
      long: 37.625101,
      radius: 10,
      istermsOfUseService: true,
      isReceiveServiceOffers: true,
      description: null,
      serviceId: null,
      // contacts
      code: null,
      firstName: null,
      lastName: null,
      middleName: null,
      address: null,
      email: null,
      phone: null,
      authSuccess: null,
    },
  },
  autostat: {
    ...initialBaseDefault,
    data: null,
    params: null,
    paramsAccurate: null,
  },
  sellerInfo: {
    ...initialBaseDefault,
    info: null,
  },
  applications: {
    ...initialBaseDefault,
    items: [],
  },
  userReviews: {
    ...initialBaseDefault,
    currentPage: 1,
    pageLimit: 10,
    items: [],
    totalPages: 1,
  },
  userReview: {
    ...initialBaseDefault,
    data: null,
  },
  insuranceApplication: {
    initiated: false,
    loading: false,
    error: null,
    services: {
      [APPLICATION_INSURANCE_TYPE.CASCO]: {
        loading: false,
        error: null,
        paymentLink: '',
        paymentLinkLoading: false,
      },
      [APPLICATION_INSURANCE_TYPE.OSAGO]: {
        loading: false,
        error: null,
        paymentLink: '',
        paymentLinkLoading: false,
      },
    },
    application: {
      insurance: [
        {
          id: 0,
          type: APPLICATION_INSURANCE_TYPE.CASCO,
          status: APPLICATION_INSURANCE_STATUS.NEW,
          applicationId: 0,
          discount: 0,
          vehicleId: 0,
          number: '',
        },
        {
          id: 0,
          type: APPLICATION_INSURANCE_TYPE.OSAGO,
          status: APPLICATION_INSURANCE_STATUS.NEW,
          applicationId: 0,
          discount: 0,
          vehicleId: 0,
          number: '',
        },
      ],
    },
  },
  insuranceFilterValues: {
    city: 'Moscow',
    formType: INSURANCE_FORM_TYPE.CASCO_OSAGO,
    vehicleType: VEHICLE_TYPE.USED,
    vehicleOwningType: VEHICLE_OWNING_TYPE.OWNED,
  },
  flashMessages: [],
  messageModal: { variant: null, open: false },
  application: {
    container: {
      initial: false,
      loading: false,
      error: null,
    },
    vehicle: {
      initial: false,
      loading: false,
      error: null,
      price: 0,
      specialOffer: {
        id: 0,
        link: '',
        name: '',
        percent: 0,
        vehicleType: 0,
        applicationType: null,
        dealerDiscount: 0,
      },
    },
    simpleCredit: {
      initial: false,
      loading: false,
      error: null,
      initialPayment: 0,
      term: 0,
      monthlyPayment: 0,
      amount: 0,
      rate: 0,
      type: CreditType.SIMPLE,
      subtype: SimpleCreditSubtype.JUST_MONEY,
      vehicleCost: 0,
      status: APPLICATION_CREDIT_STATUS.EXPIRED,
    },
  },
  favourites: {
    ...initialBaseDefault,
    items: [],
  },
  comparisonVehiclesNew: {
    ...initialBaseDefault,
    items: [],
    optionsMap: [],
  },
  comparisonVehiclesUsed: {
    ...initialBaseDefault,
    items: [],
    optionsMap: [],
  },
  comparisonIds: {
    ...initialBaseDefault,
    data: {
      new: [],
      used: [],
    },
  },
  instalmentBrands: {
    ...initialBaseDefault,
    brands: [],
  },
  instalmentBestOffers: {
    ...initialBaseDefault,
    items: null,
  },
  instalmentFilter: {
    ...initialBaseDefault,
    sort: VehicleSortType.PRICE_ASC,
    values: {
      type: null,
      city: '1',
      specialOffers: null,
      brands: null,
      models: null,
      generations: null,
      bodyTypes: null,
      transmissions: null,
      engines: null,
      drives: null,
      colors: null,
      priceFrom: null,
      priceTo: null,
      yearFrom: null,
      yearTo: null,
      powerFrom: null,
      powerTo: null,
      volumeFrom: null,
      volumeTo: null,
      mileageFrom: null,
      mileageTo: null,
      sellerType: null,
      installmentMonths: null,
      installmentMonthlyPaymentFrom: null,
      installmentMonthlyPaymentTo: null,
      cityId: null,
      salesOfficeId: null,
    },
    data: {
      specialOffers: [],
      brands: [],
      models: [],
      generations: [],
      bodyTypes: [],
      transmissions: [],
      engines: [],
      drives: [],
      colors: [],
      yearFrom: 0,
      yearTo: 0,
      priceFrom: 0,
      priceTo: 0,
      powerFrom: 0,
      powerTo: 0,
      volumeFrom: 0,
      volumeTo: 0,
      mileageFrom: 0,
      mileageTo: 0,
      installmentPayments: {
        12: { min: 0, max: 0 },
        24: { min: 0, max: 0 },
        36: { min: 0, max: 0 },
      },
    },
  },
  instalmentList: {
    ...initialBaseDefault,
    ...initialListDefault,
    items: [],
    sorting: VehicleSortType.PRICE_DESC,
    loadingPage: false,
    errorPage: null,
  },
  instalmentMeta: {
    ...initialBaseDefault,
    meta: {
      count: 0,
      vehiclesCount: 0,
      installmentMonths: 0,
      installmentPayment: 0,
      minPrice: 0,
    },
  },
  instalmentOffer: {
    ...initialBaseDefault,
    vehicle: null,
  },
  instalmentRelatives: {
    ...initialBaseDefault,
    items: null,
  },
  advertiseList: {
    ...initialBaseDefault,
    items: [],
    count: 0,
  },
  depositCalculator: {
    ...initialBaseDefault,
    amount: 300000,
    term: 24,
    refill: false,
    withdrawal: false,
    withoutPercentWithdrawal: true,
    depositRate: 0,
    addition: 0,
  },
  depositSubmit: {
    initial: false,
    loading: false,
    error: null,
  },
  debitSubmit: {
    ...initialBaseDefault,
  },
  exchangeRates: {
    rates: {
      date: '',
      eurAck: 0,
      eurBid: 0,
      usdAck: 0,
      usdBid: 0,
    },
    initial: false,
    loading: false,
    error: null,
  },
  financeCreditStandalone: {
    ...initialBaseDefault,
    amount: CREDIT_INFO.defaultStandaloneAmount,
    initialPayment: 0,
    rate: 0,
    term: CREDIT_INFO.c2cVehicleMaxTerm,
    vehiclePrice: CREDIT_INFO.defaultStandaloneAmount,
    monthlyPayment: 0,
    creditStep: SimpleCreditStep.Personal,
  },
  financeCreditVehicle: {
    ...initialBaseDefault,
    vehiclePrice: CREDIT_INFO.defaultStandaloneAmount,
    initialPayment: 0,
    amount: CREDIT_INFO.defaultStandaloneAmount,
    term: CREDIT_INFO.c2cVehicleMaxTerm,
    monthlyPayment: 0,
    creditStep: CreditStep.Personal,
    rate: 0,
  },
  city: {
    ...initialBaseDefault,
    current: defaultCity,
    extraCoverageRadius: 0,
    list: {
      primary: [],
      secondary: [],
    },
    isCityModalOpen: false,
    showCityConfirmation: false,
  },
  links: {
    ...initialBaseDefault,
    items: null,
  },
  debitCards: {
    ...initialBaseDefault,
    items: null,
    item: null,
  },
  breadCrumbs: {
    items: [],
  },
  // createReview: {
  //   ...initialBaseDefault,
  //   lastUpdated: null,
  //   data: {
  //     brands: [],
  //     models: [],
  //     years: [],
  //     generations: [],
  //     bodies: [],
  //     transmissions: [],
  //     engines: [],
  //     drives: [],
  //     modifications: [],
  //     conditions: [],
  //     colors: [],
  //     cities: [],
  //   },
  //   values: {
  //     brand: null,
  //     model: null,
  //     year: null,
  //     body: null,
  //     generation: null,
  //     engine: null,
  //     drive: null,
  //     transmission: null,
  //     modification: null,
  //     mileage: null,
  //     ownershipTerm: null,
  //     cityFuelConsumption: null,
  //     highwayFuelConsumption: null,
  //     photos: null,
  //     text: null,
  //     advantages: null,
  //     drawbacks: null,
  //   },
  //   valid: null,
  // },
  createReviewData: {
    ...initialBaseDefault,
    params: {},
    data: {
      brand: [],
      model: [],
      year: [],
      generation: [],
      body: [],
      transmission: [],
      engine: [],
      drive: [],
      modification: [],
      ownershipTerm: [],
    },
  },
  vehicleReview: {
    ...initialBaseDefault,
    stats: null,
    reviews: [],
    currentPage: 1,
    pageLimit: 10,
    totalPages: 1,
  },
};
