apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "static.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "static.environment" . }}
  template:
    metadata:
      labels:
        {{- include "static.labels" . | nindent 8 }}
      annotations:
      {{- range $key, $value := .Values.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    spec:
{{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
{{- end }}   
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        name: {{ template "static.fullname" . }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        envFrom:
        {{- include "static.envs" .  | trim | nindent 10}}
