apiVersion: v1
kind: Service
metadata:
  name: {{ template "static.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ingress.port }}
      targetPort: {{ .Values.ingress.port }}
      protocol: TCP
      name: {{ template "static.fullname" . }}
  selector:
    {{- include "static.labels" . | nindent 4 }}