module.exports = {
  EU: {
    default: true,
    fulfillmentCode: "NL",
    countryCodes: [
      "AT",
      "AL",
      "AD",
      "BE",
      "BG",
      "BA",
      "HU",
      "DE",
      "GG",
      "GI",
      "GR",
      "DK",
      "JE",
      "IE",
      "IS",
      "ES",
      "IT",
      "LI",
      "LT",
      "LU",
      "MT",
      "MD",
      "MC",
      "NL",
      "NO",
      "IM",
      "VA",
      "PL",
      "PT",
      "MK",
      "RO",
      "SM",
      "RS",
      "SK",
      "SI",
      "FO",
      "FI",
      "FR",
      "HR",
      "ME",
      "CZ",
      "CH",
      "SE",
      "SJ",
      "AX",
      "EE",
    ],
    allowedCurrencies: ["EUR", "USD", "GBP", "CHF"],
    languages: ["ru", "en"],
  },
  US: {
    countryCodes: ["US", "CA"],
    fulfillmentCode: "NL",
    allowedCurrencies: ["USD", "CAD", "EUR"],
    languages: ["ru", "en"],
  },
  BY: {
    countryCodes: ["BY"],
    fulfillmentCode: "BY",
    defaultDomain: "creamly.by",
    allowedCurrencies: ["BYN"],
    languages: ["ru"],
  },
  UA: {
    countryCodes: ["UA"],
    fulfillmentCode: "UA",
    defaultDomain: "creamly.ua",
    allowedCurrencies: ["EUR", "UAH", "USD"],
    languages: ["ru"],
  },
  UK: {
    countryCodes: ["GB"],
    fulfillmentCode: "NL",
    allowedCurrencies: ["GBP", "EUR", "USD", "CHF"],
    languages: ["ru", "en"],
  },
  LV: {
    countryCodes: ["LV"],
    fulfillmentCode: "LV",
    defaultDomain: "creamly.lv",
    allowedCurrencies: ["EUR"],
    languages: ["ru", "en", "lv"],
  },
  RU: {
    countryCodes: ["RU"],
    fulfillmentCode: "BY",
    defaultDomain: "creamly.ru",
    allowedCurrencies: ["RUB"],
    languages: ["ru"],
  },
  KZ: {
    countryCodes: ["KZ"],
    fulfillmentCode: "BY",
    allowedCurrencies: ["EUR", "RUB"],
    languages: ["ru"],
  },
  REST: {
    fulfillmentCode: "NL",
    allowedCurrencies: ["GBP", "EUR", "USD", "CHF", "CAD"],
    languages: ["en", "ru"],
    countryCodes: [
      "AF",
      "DZ",
      // "AS", Американское Самоа
      "AO",
      "AI",
      // "AQ", Антарктида
      "AG",
      "AR",
      "AM",
      "AW",
      "AU",
      "AZ",
      "BS",
      "BH",
      "BD",
      "BB",
      "BZ",
      "BJ",
      "BM",
      "BT",
      "BO",
      "BW",
      "BV",
      "BR",
      "IO",
      "VG",
      "BN",
      "BF",
      "BI",
      "KH",
      "CM",
      "CV",
      "BQ",
      "KY",
      "CF",
      "TD",
      "CL",
      "CN",
      "CX",
      "CC",
      "CO",
      "KM",
      "CG",
      "CD",
      "CK",
      "CR",
      "CI",
      "CU",
      "CW",
      "CY",
      "DJ",
      "DM",
      "DO",
      "EC",
      "EG",
      "SV",
      "GQ",
      "ER",
      "SZ",
      "ET",
      "FK",
      "FJ",
      "GF",
      "PF",
      "TF",
      "GA",
      "GM",
      "GE",
      "GH",
      "GL",
      "GD",
      "GP",
      "GU",
      "GT",
      "GN",
      "GW",
      "GY",
      "HT",
      "HM",
      "HN",
      "HK",
      "IN",
      "ID",
      "IR",
      "IQ",
      "IL",
      "JM",
      "JP",
      "JO",
      "KE",
      "KI",
      "KW",
      "KG",
      "LA",
      "LB",
      "LS",
      "LR",
      "LY",
      "MO",
      "MG",
      "MW",
      "MY",
      "MV",
      "ML",
      "MH",
      "MQ",
      "MR",
      "MU",
      "YT",
      "MX",
      "FM",
      "MN",
      "MS",
      "MA",
      "MZ",
      "MM",
      "NA",
      "NR",
      "NP",
      "NC",
      "NZ",
      "NI",
      "NE",
      "NG",
      "NU",
      "NF",
      "KP",
      "MP",
      "OM",
      "PK",
      "PW",
      "PS",
      "PA",
      "PG",
      "PY",
      "PE",
      "PH",
      "PN",
      "PR",
      "QA",
      "RE",
      "RW",
      "WS",
      "ST",
      "SA",
      "SN",
      "SC",
      "SL",
      "SG",
      "SX",
      "SB",
      "SO",
      "ZA",
      "GS",
      "KR",
      "SS",
      "LK",
      "BL",
      "SH",
      "KN",
      "LC",
      "MF",
      "PM",
      "VC",
      "SD",
      "SR",
      "SY",
      "TW",
      "TJ",
      "TZ",
      "TH",
      "TL",
      "TG",
      "TK",
      "TO",
      "TT",
      "TN",
      // "TR", Турция
      "TM",
      "TC",
      "TV",
      "UM",
      "VI",
      "UG",
      "AE",
      "UY",
      "UZ",
      "VU",
      "VE",
      "VN",
      "WF",
      "EH",
      "YE",
      "ZM",
      "ZW",
    ],
  },
};
