export const GET_CARRIER_EMAILS = 'GET_CARRIER_EMAILS';
export const GET_CARRIER_EMAILS_SUCCESS = 'GET_CARRIER_EMAILS_SUCCESS';
export const GET_CARRIER_EMAILS_ERROR = 'GET_CARRIER_EMAILS_ERROR';

export const UPDATE_CARRIER_EMAILS = 'UPDATE_CARRIER_EMAILS';
export const UPDATE_CARRIER_EMAILS_SUCCESS = 'UPDATE_CARRIER_EMAILS_SUCCESS';
export const UPDATE_CARRIER_EMAILS_ERROR = 'UPDATE_CARRIER_EMAILS_ERROR';

export const CHANGE_APPROVE_CARRIER = 'CHANGE_APPROVE_CARRIER';
export const DELETE_EMAIL_FROM_CARRIER = 'DELETE_EMAIL_FROM_CARRIER';

export const SAVE_EMAILS = 'SAVE_EMAILS';
